#ifndef WM_ARCADE_TARGET_H
#define WM_ARCADE_TARGET_H

#include <stddef.h>
#include <stdint.h>

#include "wm/arcade/wm_arcade_combat.h"

#ifdef __cplusplus
extern "C" {
#endif

/*
 * TABLES.ASM:43 set_target_offsets and :71 get_mode_height, and the grid
 * they both read.
 *
 * "Where on this wrestler is his head right now" is not one number: it
 * depends on which wrestler he is and what he is doing. TABLES.ASM answers
 * it from a [mode block][wrestler][area] grid of X/Y/Z offsets, and
 * set_target_offsets is three lines of index arithmetic over it:
 *
 *     a1 = WRESTLERNUM * 5 + area        ; five areas a wrestler
 *     a1 = a1 * 3 words                  ; x, y, z each
 *     a0 = #mode_table[PLYRMODE]         ; the block for his mode
 *
 * The grid itself is generated by tools/wltarget.py; nothing here is
 * written by hand. 26 PLYRMODEs collapse onto four distinct blocks --
 * standing (which most modes share), on the ground (which mode_dead
 * shares, the source arguing with itself about it in a comment: "This is
 * for dead mode on the ground!?!?!?!"), bouncing/turnbuckle, and
 * head-held.
 */

#define WM_TARGET_WRESTLERS 9
#define WM_TARGET_AREAS 5
#define WM_TARGET_MODES 26

/* PLYR.EQU:384-388. */
#define WM_TGT_HEAD  0
#define WM_TGT_CHEST 1
#define WM_TGT_GROIN 2
#define WM_TGT_KNEES 3
#define WM_TGT_FEET  4

/* ANIM.EQU:179-180, ANI_TARGET's third operand. */
#define WM_ATM_CLOSEST  0
#define WM_ATM_FARTHEST 1

typedef struct {
    int16_t x, y, z;
} wm_target_offset;

/*
 * The grid itself. Returns 0 for an out-of-range wrestler, mode or area,
 * leaving `*out` alone. Slot 7 is Adam Bomb, the cut wrestler, and every
 * block writes him as literal zeroes -- that is the source's own value,
 * not a gap.
 */
int wm_target_offsets(int32_t wrestler_num, int32_t player_mode,
                      int area, wm_target_offset *out);

/* How many distinct blocks the mode table collapses onto. */
size_t wm_target_block_count(void);

/*
 * TABLES.ASM:43 set_target_offsets: aim `actor` at `area` of `target`.
 * Writes the actor's own TGT_XOFF/YOFF/ZOFF. No-op when the grid declines.
 */
void wm_arcade_set_target_offsets(wm_arcade_actor_t *actor,
                                  const wm_arcade_actor_t *target, int area);

/*
 * TABLES.ASM:71 get_mode_height -- how tall this wrestler is in this mode,
 * read out of the same grid `15n + 1` words in, which is his HEAD's Y.
 */
int32_t wm_arcade_get_mode_height(const wm_arcade_actor_t *actor);

/*
 * ANIM.ASM:3753 ANI_TARGET -- "sets leapat target to #TARGET1 or #TARGET2,
 * depending on the value of #MODE", with the source's own example:
 * `ANI_TARGET,TGT_HEAD,TGT_KNEES,ATM_CLOSEST` targets whichever of the
 * victim's head or knees is nearer.
 *
 * Which is nearer is decided by the FLIP BITS, not by distance: if the two
 * wrestlers' OBJ_CONTROL flip bits match, this one is looking at the
 * other's feet, and then the HIGHER area index (feet end) is the closer
 * one; if they differ he is looking at the head and the lower index is.
 * ATM_FARTHEST inverts it.
 *
 * The source's own caveat, kept because it is a real limit: "This assumes
 * that victim is on the ground. If he's not, the results will be screwy."
 * It finishes with tgt_ground, which zeroes TGT_YOFF again.
 */
void wm_arcade_anim_target(wm_arcade_actor_t *actor,
                           const wm_arcade_actor_t *target,
                           int target1, int target2, int mode);

/* ==================================================================== *
 * LIFEBAR.ASM:3444 MOVE_NAME_ANNC -- the move name that flashes up.
 *
 * ANIM.ASM:4389 ANI_DRAW_NAME and HRTSEQ3.ASM's draw_ddt_name are the same
 * call with the same argument: a move index into #message_tbl. Drawing the
 * image needs a renderer; deciding WHETHER to draw it does not, and that
 * decision has three real parts, all translated here.
 * ==================================================================== */

/*
 * SQUARE.ASM:40 square_root and its table. Not an approximation of one:
 * the routine discards its input's low five bits, normalises what is left
 * to at most ten bits by an even shift, looks the result up in a 1024-byte
 * table of "square root of multiples of 32", and shifts the answer back.
 * Every entry in that table is within 1 of the real sqrt(i*32), so the
 * error the game actually sees comes from the shifting, not the data.
 */
#define WM_SQROOT_ENTRIES 1024
extern const uint8_t wm_sqroot_tab[WM_SQROOT_ENTRIES];

/* The routine itself. Max useful input is 262,143; larger values are
   normalised the same way and simply lose more precision. */
int32_t wm_arcade_square_root(uint32_t v);

/* SPECIAL.ASM:141 #dizzy_offsets -- where a wrestler's stars go, per
   "mode" slot (the source's header: "stand, on stomach, on back,?,?").
   Ten rows: the nine roster slots and the referee. */
#define WM_DIZZY_ROWS 10
#define WM_DIZZY_SLOTS 4

typedef struct { int16_t x, y; } wm_dizzy_offset;

extern const wm_dizzy_offset wm_dizzy_offsets[WM_DIZZY_ROWS][WM_DIZZY_SLOTS];

#define WM_MOVE_NAME_COUNT 43

/* `cmpi 41,a10 / jrz #skip` -- index 41 shows even when reduce_bog is on,
   and (as index 32+9) is the one index exempt from the shown-once bit. */
#define WM_MOVE_NAME_ALWAYS 41

/* MOVE_NAME_ANNC's image per index, "" (NULL) where the source writes 0. */
extern const char *const wm_move_name_images[WM_MOVE_NAME_COUNT];

typedef struct {
    /* LIFEBAR.ASM:108 message_flag, 32*2 bits: "Message already displayed
       bit", one word for indices 0-31 and one for 32 and up. */
    uint32_t shown[2];
    /* LIFEBAR.ASM:116 MESSAGE_FLAGS, per PLYR_SIDE: is one already up.
       is_there_one_already reads the OTHER side's (`NOT A1 / SLL 31 / SRL
       27`), so a name on one side blocks the other. */
    uint8_t showing[2];
} wm_move_name_state;

void wm_move_name_init(wm_move_name_state *st);

/*
 * Should this move name be shown? Translates MOVE_NAME_ANNC's own three
 * gates in the source's order: the reduce_bog skip (index 41 exempt), the
 * other side already showing one, and the shown-once bit (index 41 exempt
 * again). Sets the bit when it answers true.
 */
int wm_move_name_should_draw(wm_move_name_state *st, int side, int index,
                            int reduce_bog);

#ifdef __cplusplus
}
#endif
#endif
