#ifndef WM_ARCADE_JJXM_H
#define WM_ARCADE_JJXM_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
 * JJXM.H -- four lines of macro that decide what every attack button in
 * the game actually does.
 *
 *   JJXM_INIT   calla get_opp_plyrmode          ; a0 = the OPPONENT's mode
 *               move  *a13(CLOSEST_XDIST),a1
 *               move  *a13(CLOSEST_ZDIST),a2
 *
 *   JJXM MODE,DX,DZ,LESS,MORE
 *               cmpi MODE_:MODE:,a0 / jrne next
 *               cmpi :DX:,a1 / jrgt :MORE:
 *               cmpi :DZ:,a2 / jrgt :MORE:
 *               jruc :LESS:
 *
 *   JJXM MODE,TARGET                            ; the $isname(DX) arm
 *               cmpi MODE_:MODE:,a0 / jrne next
 *               jruc :TARGET:
 *
 *   JJXM_END    LOCKUP / rets
 *
 * So a press is answered FIRST by what the other wrestler is doing and
 * only then by how far away he is. Three consequences the port did not
 * have before these tables were read out:
 *
 *   - `cmpi X,a1` computes a1-X, so `jrgt MORE` is taken on STRICTLY
 *     GREATER. The near arm is the CLOSED interval, xdist <= DX AND
 *     zdist <= DZ -- not `<`, which is what an approximation reaches
 *     for and what this port used.
 *
 *   - Plenty of rows have no distance test at all and name one target
 *     for the whole mode: Doink's super kick against a RUNNING or
 *     BOUNCING opponent is always the big boot, against an INAIR2 one
 *     always the turnbuckle spin kick, and his super punch against a
 *     HEADHELD one is the pile-driver routine in another section
 *     entirely.
 *
 *   - A mode with NO row falls off the end into JJXM_END, which is
 *     `LOCKUP / rets` -- the button does nothing at all. MODE_CHOKING
 *     (25) has no row in any of the fifty tables.
 *
 * The tables themselves are generated by tools/wljjxm.py straight out of
 * the wrestler .ASM files; there are 1100 rows and a hand-copied row is
 * a bug nobody can see. Target names are kept exactly as the source
 * writes them -- "#punch_hdbutt", "std_punch", "do_pile" -- so any name
 * a caller compares against can be grepped in the original.
 */

typedef struct wm_jjxm_row {
    /* PLYR.EQU:276 MODE_*, the value get_opp_plyrmode returns. */
    uint8_t opp_mode;
    /* The thresholds, or -1 for a row written in the two-argument form
       that names one target for the whole mode. */
    int16_t dx;
    int16_t dz;
    /* Indexes into the table's `targets`. Equal on an unconditional
       row -- and equal on a few conditional ones too, where the source
       wrote a distance test whose two arms are the same label. */
    uint8_t less;
    uint8_t more;
} wm_jjxm_row_t;

typedef struct wm_jjxm_table {
    const char *wrestler;        /* "DOINK" */
    const char *file;            /* "DOINK.ASM" */
    const char *section;         /* the enclosing mode_* label */
    int line;                    /* of the JJXM_INIT */
    /* The local labels this table answers to. One table often serves
       several buttons: mode_running's punch group is reached from
       #punch, #super_punch, #punchkick and #graboh alike. */
    const char *const *entries;
    size_t entry_count;
    const wm_jjxm_row_t *rows;
    size_t row_count;
    const char *const *targets;
    size_t target_count;
} wm_jjxm_table_t;

extern const wm_jjxm_table_t wm_jjxm_tables[];
extern const size_t wm_jjxm_table_count;

/*
 * The table a wrestler's section reaches for a given button label.
 * `entry` is matched against the table's own entry labels, so
 * wm_jjxm_find("DOINK", "mode_running", "#super_punch") finds the
 * clothesline group rather than the mode_normal super punch.
 * NULL when there is no such table.
 */
const wm_jjxm_table_t *wm_jjxm_find(const char *wrestler,
                                    const char *section,
                                    const char *entry);

/*
 * Run the macro: the first row whose mode matches decides, and the
 * answer is a target label. NULL means the table has no row for this
 * mode -- JJXM_END, the press does nothing.
 *
 * `xdist` and `zdist` are CLOSEST_XDIST and CLOSEST_ZDIST, which the
 * source holds as plain integers.
 */
const char *wm_jjxm_select(const wm_jjxm_table_t *table,
                           uint16_t opp_mode,
                           int32_t xdist,
                           int32_t zdist);

#ifdef __cplusplus
}
#endif

#endif /* WM_ARCADE_JJXM_H */
