#ifndef WMANIA_ATTRACT_DATA_H
#define WMANIA_ATTRACT_DATA_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
 * NUM_HINTS, ATTRACT.ASM:3386. Ten, and WHICH_HINT (:3625) holds ten records.
 *
 * This was 5 until the shipped file was read. Five is ATTR.ASM:3482's
 * NUM_HINTS -- the superseded dump -- and the two tables are not a prefix of
 * one another: ATTR runs HNT_2,4,3,7,5 and ATTRACT runs HNT_2,4,3,9,7,5,8,1,
 * 6,A, so the old table also had the WRONG hint at indices 3 and 4 as well as
 * missing half of them.
 */
#define WM_ATTRACT_ACTIVE_HINTS 10u

/* #gen_tip_table (ATTRACT.ASM:1397): four tips of two lines each, with a
   `blank` spacer between each pair, then the 0 terminator. */
#define WM_ATTRACT_GEN_TIP_SLOTS 11u

/* Each xxx_tips table under wrestler_tips (ATTRACT.ASM:2578): three tips of
   two lines each, with two `blank` spacers between them. */
#define WM_ATTRACT_WRES_TIP_LINES 8u

/* #HNT_7 lists eight line pointers; no other body lists more. */
#define WM_ATTRACT_HINT_MAX_LINES 8u
#define WM_ATTRACT_WRESTLERS 8u
#define WM_ATTRACT_BIO_ATTRIBUTES 4u
#define WM_ATTRACT_COPYRIGHT_PAGE1_LINES 9u
#define WM_ATTRACT_COPYRIGHT_PAGE2_LINES 10u

/*
 * Text is represented by original source labels instead of invented copy.
 * The merge can resolve labels through the supplied source-text extraction
 * helper or an existing translated text/asset table.
 */
typedef struct {
    const char *title_label;
    const char *body_label;
    const char *tip_image_symbol;
    const char *mug_image_symbol;
    uint8_t number_image_index;
} WmAttractHint;

typedef struct {
    const char *name;
    /*
     * HALFWIDTH IS IN THE RECORD AND MUST NOT BE APPLIED.
     *
     * ATTRACT.ASM:2176 reads it into a11 under a comment calling it "the
     * halfwidth for current wrestler", but the only code that subtracted it
     * from #bio_center (:2184, :2192) is commented out, and the live path at
     * :2204 writes #bio_center straight into mess_cursx. The abandoned
     * `#bio_halfwidth .equ 87` at :2642 -- a single value for all eight, used
     * by nothing -- is the other half of the same unfinished idea.
     *
     * It is carried because the record carries it. Applying it would put every
     * bio line 77-81 pixels left of where the arcade draws it.
     */
    uint16_t halfwidth;
    const char *from_label;
    uint16_t weight_lbs;
    uint8_t height_ft;
    uint8_t height_in;
    const char *quote_label;
    const char *logo_symbol;
    uint8_t logo_width;
    uint8_t logo_height;
    uint16_t tune_id;
    const char *tips_table_label;
} WmAttractBio;

typedef struct {
    const char *background_symbol;
    const char *title_text_label;
    int16_t title_x;
    int16_t title_y;
    int16_t body_x;
    int16_t body_y;
    int16_t body_line_step;
    uint16_t initial_sleep_ticks;
    uint16_t wait_tsec_num;
    uint16_t wait_tsec_den;
} WmAttractScreenLayout;

extern const WmAttractHint wm_attract_hints[WM_ATTRACT_ACTIVE_HINTS];
extern const WmAttractBio wm_attract_bios[WM_ATTRACT_WRESTLERS];

/*
 * The words of the four table-driven screens, generated by
 * tools/wlattracttext.py and defined in src/generated/attract_text.c. The
 * tables above stay the hand-transcribed asset and measurement half; these
 * carry only what the source stores as text, so neither restates the other.
 *
 * Everything else those screens say is reachable from the labels the tables
 * above already hold -- title_label, from_label, quote_label,
 * wm_attract_general_tip_labels -- through wm_attract_text(). Only the hint
 * bodies and the per-wrestler tips need their own array, because the source
 * reaches those through a second level of pointer table with no fixed names
 * per line.
 */

/*
 * line_count is the hint body's own count word, which NEXT_HINT
 * (ATTRACT.ASM:3545) uses as its DSJS counter: it is how many lines the
 * arcade draws. line_total is how many pointers actually follow that word.
 *
 * They differ for exactly one hint -- index 4, #HNT_7, "SECOND WIND" --
 * which declares 6 and lists 8. Its last two lines are in the ROM and never
 * reach a screen, and the second of them reads "...DOES NOT WORK IF" / "IF
 * YOU DIE OUTSIDE THE RING.", a doubled IF that went unnoticed because
 * nobody could see it. Draw line_count. The rest is kept so the dead data
 * stays visible instead of being quietly dropped.
 */
typedef struct {
    const char *title;
    const char *lines[WM_ATTRACT_HINT_MAX_LINES];  /* NULL past line_total */
    uint8_t line_count;   /* drawn */
    uint8_t line_total;   /* present */
} wm_attract_hint_text;

extern const wm_attract_hint_text
wm_attract_hint_texts[WM_ATTRACT_ACTIVE_HINTS];

/* A `blank` slot is "" and not NULL: swt_loop still steps y by 15 for it. */
extern const char *const
wm_attract_wres_tip_lines[WM_ATTRACT_WRESTLERS][WM_ATTRACT_WRES_TIP_LINES];

/* Source-layout constants. */
extern const WmAttractScreenLayout wm_attract_general_tips_layout;
extern const WmAttractScreenLayout wm_attract_operator_layout;
extern const WmAttractScreenLayout wm_attract_aama_layout;

/* General fixed tip table source labels, terminating with NULL. */
extern const char *const wm_attract_general_tip_labels[];

/* Copyright uses two sequential pages of 9 and 10 labels. */
extern const char *const wm_attract_copyright_page1_labels[
    WM_ATTRACT_COPYRIGHT_PAGE1_LINES];
extern const char *const wm_attract_copyright_page2_labels[
    WM_ATTRACT_COPYRIGHT_PAGE2_LINES];

/* AAMA source labels. */
extern const char *const wm_attract_aama_labels[6];

/*
 * aama_message's six lines are NOT a uniform column, so the generic
 * WmAttractScreenLayout above cannot express them and this table does.
 * ATTRACT.ASM:308-343, one `movi [y,x],a9` and one `movi [colour,0],a6`
 * per line:
 *
 *   ln1   [54+60-20,200]  y  94  x 200  colour >1111
 *   ln2   [54+60,>b1]     y 114  x 177  colour >1111
 *   ln2b  [54+60,>104]    y 114  x 260  colour >0606
 *   ln3   [54+71,200]     y 125  x 200  colour >1111
 *   ln4   [54+82,200]     y 136  x 200  colour >1111
 *   ln5   [54+93,200]     y 147  x 200  colour >1111
 *
 * ln2 and ln2b share a y and sit side by side -- "LIFE-LIKE VIOLENCE"
 * centred on 177 and "- MILD" on 260 -- and ln2b is the one line on any
 * of these screens drawn in a DIFFERENT colour. Every x is a centre,
 * because STRCNRMO_2 is the centred entry point.
 *
 * `colour` is the source's own word. It is kept rather than converted
 * because resolving a TMS palette index to RGB needs the palette this
 * port has not translated; see wmania_attract_data.c.
 */
typedef struct {
    const char *label;
    int16_t x;
    int16_t y;
    uint16_t colour;
} WmAttractAamaLine;

#define WM_ATTRACT_AAMA_LINES 6u
extern const WmAttractAamaLine wm_attract_aama_lines[WM_ATTRACT_AAMA_LINES];

/* aama_message's own boundaries: SLEEPK 2, place, SLEEPK 2 +
   display_unblank, SLEEPK 20, wait_on_butn 4*TSEC (ATTRACT.ASM:352). */
#define WM_ATTRACT_AAMA_SETTLE_TICKS 20
#define WM_ATTRACT_AAMA_WAIT_TSEC 4

/* Bio source-render geometry. */
#define WM_ATTRACT_BIO_BACKGROUND_SYMBOL "biopageBMOD"
#define WM_ATTRACT_BIO_STORY_BACKGROUND_SYMBOL "story_bgnd"
#define WM_ATTRACT_BIO_MUG_TABLE_SYMBOL "wrestler_mugs2"
#define WM_ATTRACT_BIO_ATTRIBUTE_TABLE_SYMBOL "wrestler_attributes"
#define WM_ATTRACT_BIO_ATTRIBUTE_BARS_SYMBOL "attbars"
#define WM_ATTRACT_BIO_ATTRIBUTE_LABEL_SYMBOL "ATT_TXT"
#define WM_ATTRACT_BIO_LOGO_Y 24
#define WM_ATTRACT_BIO_LOGO_X 11
#define WM_ATTRACT_BIO_MUG_Y 0x17a
#define WM_ATTRACT_BIO_MUG_X 0
#define WM_ATTRACT_BIO_MUG_Z 0x0af
#define WM_ATTRACT_BIO_ATTRIBUTE_Y 0xff
#define WM_ATTRACT_BIO_ATTRIBUTE_X 0xae
#define WM_ATTRACT_BIO_ATTRIBUTE_BAR_Y (0xff + 61)
#define WM_ATTRACT_BIO_ATTRIBUTE_BAR_X (0xae + 12)
#define WM_ATTRACT_BIO_ATTRIBUTE_BAR_STEP 8
#define WM_ATTRACT_BIO_TEXT_CENTER_X 100
#define WM_ATTRACT_BIO_TEXT_Y 106
#define WM_ATTRACT_BIO_NORMAL_PREWAIT_TSEC 2
#define WM_ATTRACT_BIO_NORMAL_WAIT_TSEC 6
/*
 * The four bio text runs, as offsets from #bio_center (100) and #bio_y (106).
 *
 * The source lays each out with an explicit mess_cursx/mess_cursy write
 * rather than a column, and the height and weight are each a RUN of four and
 * two prints: the number in wsf14_ascii on one baseline and its unit suffix
 * in wsf10_ascii four pixels lower, chained through @mess_cursx2. This port
 * has one font and no cursx2, so it draws each run as a single string on the
 * number's y -- "6 FT. 1 IN." where the arcade draws "6", " FT. ", "1",
 * " IN." in two sizes. The characters and their order are the source's; the
 * two-size typography is not reproduced.
 */
#define WM_ATTRACT_BIO_FROM_X WM_ATTRACT_BIO_TEXT_CENTER_X
#define WM_ATTRACT_BIO_FROM_Y WM_ATTRACT_BIO_TEXT_Y
#define WM_ATTRACT_BIO_HEIGHT_X (WM_ATTRACT_BIO_TEXT_CENTER_X + 8)
#define WM_ATTRACT_BIO_HEIGHT_Y (WM_ATTRACT_BIO_TEXT_Y + 25)
#define WM_ATTRACT_BIO_WEIGHT_X (WM_ATTRACT_BIO_TEXT_CENTER_X + 16)
#define WM_ATTRACT_BIO_WEIGHT_Y (WM_ATTRACT_BIO_TEXT_Y + 50)
/*
 * RECORDED, NOT APPLIED. The source drops each unit suffix four pixels below
 * its number because the suffix is in the smaller font and this baselines the
 * two. With one font there is nothing to baseline, so the port draws the whole
 * run on the number's y and nothing reads this. It is here so the divergence
 * is a number somebody can check rather than a sentence in a commit message.
 */
#define WM_ATTRACT_BIO_SUFFIX_Y_DROP 4
/* print_string_C2, so this x is a centre and not a left edge. */
#define WM_ATTRACT_BIO_QUOTE_X (WM_ATTRACT_BIO_TEXT_CENTER_X + 15)
#define WM_ATTRACT_BIO_QUOTE_Y (WM_ATTRACT_BIO_TEXT_Y + 96 + 4)
#define WM_ATTRACT_BIO_QUOTE_LINE_STEP 14
/*
 * RECORDED, NOT APPLIED, for the same reason the quote's step IS applied:
 * mess_line_spacing is set to 20 before the from-string (ATTRACT.ASM:2179)
 * and to 14 before the quote (:2286), but no from-string in #bio_data
 * contains a newline, so 20 never gets to do anything. If a re-dump ever
 * gives a hometown two lines, this is the step it takes.
 */
#define WM_ATTRACT_BIO_LINE_STEP 20
/* BLOW_0_TO_1 runs before the SLEEP 2*TSEC; see WM_ATTRACT_BLOW_0_TO_1_TICKS. */

/* show_wres_tips source presentation (ATTRACT.ASM:2588). */
#define WM_ATTRACT_WRES_TIPS_TITLE_LABEL "wt_title_setup"
#define WM_ATTRACT_WRES_TIPS_TITLE_X 135
#define WM_ATTRACT_WRES_TIPS_TITLE_Y 95
/* wt_line1_setup prints through print_string, not print_string_C, so this x
   is a LEFT edge -- the only one of these screens' line columns that is. */
#define WM_ATTRACT_WRES_TIPS_LINE_X 10
#define WM_ATTRACT_WRES_TIPS_FIRST_Y 120
#define WM_ATTRACT_WRES_TIPS_LINE_STEP 15

/* Designer-hint source layout/timing. */
#define WM_ATTRACT_HINT_BACKGROUND_SYMBOL "hstd_mod"
#define WM_ATTRACT_HINT_BAR_SYMBOL "MVEBAR_R"
#define WM_ATTRACT_HINT_SHADOW_SYMBOL "SHADOW01"
#define WM_ATTRACT_HINT_MUG_BACK_SYMBOL "MUGBAK"
#define WM_ATTRACT_HINT_MUG_FRONT_SYMBOL "MUGFRNT"
#define WM_ATTRACT_HINT_TITLE_Y 62
#define WM_ATTRACT_HINT_TITLE_X 200
#define WM_ATTRACT_HINT_BODY_Y 108
#define WM_ATTRACT_HINT_BODY_X 200
#define WM_ATTRACT_HINT_BODY_LINE_STEP 15
#define WM_ATTRACT_HINT_OPEN_SCREEN_A 18
#define WM_ATTRACT_HINT_OPEN_SCREEN_B 6
#define WM_ATTRACT_HINT_PREWAIT_TICKS 80
#define WM_ATTRACT_HINT_WAIT_TSEC 15

/* General-tips exact render/timing structure. */
#define WM_ATTRACT_GENERAL_TIPS_BACKGROUND_SYMBOL "hstd_mod"
#define WM_ATTRACT_GENERAL_TIPS_TITLE_LABEL "gen_tip_mes"
#define WM_ATTRACT_GENERAL_TIPS_BAR_SYMBOL "MVEBAR_R"
#define WM_ATTRACT_GENERAL_TIPS_SHADOW_SYMBOL "SHADOW01"
#define WM_ATTRACT_GENERAL_TIPS_TITLE_Y 10
#define WM_ATTRACT_GENERAL_TIPS_TITLE_X 200
#define WM_ATTRACT_GENERAL_TIPS_FIRST_Y 60
#define WM_ATTRACT_GENERAL_TIPS_LINE_STEP 15
#define WM_ATTRACT_GENERAL_TIPS_PREWAIT_TSEC 1
#define WM_ATTRACT_GENERAL_TIPS_WAIT_TSEC 10
/* #gt_line_setup carries x 200, and the loop calls print_string_C, so the
   lines are centred on the same x as the title. */
#define WM_ATTRACT_GENERAL_TIPS_LINE_X 200

/*
 * The two screen transitions these screens wait inside, in ticks. Neither is
 * drawn here -- both are pixel/palette effects over the whole framebuffer --
 * but both SLEEP, so a port that skipped them would run every screen short.
 *
 * BLOW_0_TO_1 (SCREEN.ASM:139): four SLEEP 1, then ten passes of SLEEP 3 twice,
 * then SLEEP 25. It clears @DISPLAYON on its fourth tick and sets it again at
 * the end, so the screen is blank for all but the first few ticks.
 *
 * CLOSE_SCREEN_LINE / OPEN_SCREEN_LINE (SCREEN.ASM:724 / :692) with DO_HINTS'
 * a8=18, a9=6: GAMSTATE is INAMODE in attract, so MAKE_IT_FAST halves a8 to 9;
 * a9 is positive so DO_LINES takes #BOTTOM_UP, six passes of PRCSLP 6, then
 * EXIT_CLOSE_LINE's PRCSLP a8-a9+2 = 5. OPEN_SCREEN_LINE re-reads a8 from
 * @WHAT_SPEED, which CLOSE_SCREEN_LINE stored as the already-halved 9, so the
 * two cost the same.
 */
#define WM_ATTRACT_BLOW_0_TO_1_TICKS (4 + 10 * (3 + 3) + 25)
#define WM_ATTRACT_SCREEN_LINE_TICKS (6 * 6 + 5)

/* Copyright source presentation. */
#define WM_ATTRACT_COPYRIGHT_FONT_SYMBOL "RD7FONT"
#define WM_ATTRACT_COPYRIGHT_WWF_IMAGE_SYMBOL "SMWWF2"
#define WM_ATTRACT_COPYRIGHT_FIRST_Y 110
#define WM_ATTRACT_COPYRIGHT_X 200
#define WM_ATTRACT_COPYRIGHT_LINE_STEP 12
#define WM_ATTRACT_COPYRIGHT_FADE_STEPS 8
#define WM_ATTRACT_COPYRIGHT_FADE_SETTLE_TICKS 20
#define WM_ATTRACT_COPYRIGHT_PAGE_WAIT_TSEC 3

/* AAMA source presentation. */
#define WM_ATTRACT_AAMA_FONT_SYMBOL "RD7FONT"
#define WM_ATTRACT_AAMA_GRADIENT_ROWS_TOP 31
#define WM_ATTRACT_AAMA_GRADIENT_ROWS_BOTTOM 32
#define WM_ATTRACT_AAMA_FADE_STEPS 8
#define WM_ATTRACT_AAMA_FADE_SETTLE_TICKS 20
#define WM_ATTRACT_AAMA_WAIT_TSEC 4

/*
 * creditscreen (ATTRACT.ASM:793) and the CRD_SCRN2 it wraps (AUDIT.ASM:998).
 *
 * THIS SCREEN IS DIFFERENT IN KIND FROM EVERY OTHER ATTRACT SCREEN. The
 * others display data; this one displays the cabinet's COIN STATE, and this
 * port has none of that state: no credits, no coin inputs, no CMOS
 * adjustments, no pricing tables, no DIP bank, no tamper audit. So its text
 * cannot be read out of a table the way the hints or the bios can -- it has
 * to be EVALUATED, and what it evaluates to depends entirely on settings that
 * do not exist here.
 *
 * So the port shows exactly one state: a factory-set cabinet with no credits
 * in it, which is precisely the state it is in. Everything below is derived
 * from the arcade's own FACTORY_TABLE (AUDIT.ASM:2905) with CRED_P = 0, and
 * the derivation is written out so it can be checked rather than trusted:
 *
 *   ADJFREPL  (19) = 0   -> not free play, so credits_string takes
 *                           #not_freeply and "FREE  PLAY" never shows
 *   ADJPRICE  (1)  = 1   -> GET_CSPT -> CS_POINT(1) -> `DEC a0` -> CSELCT
 *                           entry 0, "USA 1: 1 COIN = 1 CREDIT", whose
 *                           CS_LIST is Q_Q -> the single string C11
 *                           (MENU.ASM:7132) "1 CREDIT / 1 COIN"
 *   ADJ1ST6   (22) = 1   -> TAMPEREDP returns non-zero, so the `JRZ #done`
 *                           after AUDIT.ASM:1272's `calla TAMPEREDP` is
 *                           NOT taken and that one
 *                           pricing line does print
 *   ADJCSTRT  (12) = 2   -> `dec a0` is non-zero, so the PLURAL
 *                           " CREDITS TO START" is chosen
 *   ADJCCONT  (13) = 2   -> likewise " CREDITS TO CONTINUE"
 *   ADJMAXC   (18) = 50  -> 0 < 50, so " (MAXIMUM)" is not appended
 *   CRED_P         = 0   -> 0 / 2 = 0, so #not_ready: "INSERT COINS", and
 *                           none of the four "READY FOR ..." lines nor
 *                           "PRESS  START" is selected
 *
 * The y positions come out of the same evaluation. LN1+4 = 74 for the credit
 * count. The pricing block starts at `140 - (YSPACE0 * a10) / 2` with
 * YSPACE0 = 17 and a10 = 3 (its floor of 2, plus one CS_LIST string, plus
 * nothing for the not-ready case), so 140 - 51/2 = 115; each of the three
 * lines then adds 17 BEFORE printing, giving 132, 149 and 166. The last line
 * resets to LN5+10 = 200 and adds YSPACE = 25, giving 225.
 *
 * TAMPEREDP'S HEADER COMMENT IS WRONG ABOUT ITS OWN POLARITY. ADJUST.ASM:946
 * says "THIS IS NON-ZERO IF ANY OF THE 1ST 6 COIN PARAMETERS HAVE BEEN
 * ADJUSTED", but it returns GET_ADJ(ADJ1ST6) and ADJ1ST6 is documented at
 * AUDIT.ASM:2932 as "NON-ZERO MEANS 1ST 6 UNTOUCHED". Non-zero means NOT
 * tampered. The factory value is 1, so a fresh cabinet shows the pricing
 * line; a cabinet whose coinage has been edited hides it.
 */
#define WM_ATTRACT_CREDIT_X 200
#define WM_ATTRACT_CREDIT_LINES 5u

/* The factory values the lines above are evaluated at, so a test can assert
   them rather than re-deriving them from prose. */
#define WM_ATTRACT_CREDIT_ADJ_CSTRT 2
#define WM_ATTRACT_CREDIT_ADJ_CCONT 2
#define WM_ATTRACT_CREDIT_ADJ_MAXC 50
#define WM_ATTRACT_CREDIT_ADJ_FREPL 0
#define WM_ATTRACT_CREDIT_ADJ_PRICE 1
#define WM_ATTRACT_CREDIT_ADJ_1ST6 1
#define WM_ATTRACT_CREDIT_CREDITS 0

typedef struct {
    const char *text;
    int16_t y;            /* x is always WM_ATTRACT_CREDIT_X, and every line
                             goes through print_string_C or _C2, so it is a
                             centre */
    const char *source_label;   /* which literal, for the citation trail */
} WmAttractCreditLine;

extern const WmAttractCreditLine
wm_attract_credit_lines[WM_ATTRACT_CREDIT_LINES];

/*
 * CRD_SCRN2's timing, from the creditscreen entry (a10 = 1).
 *
 * `SLEEPK 2` puts the text up at tick 2 -- crd_updatetxt runs between the
 * first and second of them. `display_unblank` is at tick 6, after the third.
 * Then `SLEEP 1*TSEC`, and then a 4*TSEC loop that samples buttons, so the
 * screen is skippable from tick 60 and ends on its own at 271.
 *
 * crd_updatetxt RUNS TWICE: once at :1032 and again at #cont (:1057). The
 * second call opens with `KILALL CP_PID1` and `obj_delc TYPTEXT`, so it
 * deletes the text the first call drew and redraws it. The port draws once;
 * the result on screen is the same.
 *
 * THE SECOND WAIT LOOP IS UNREACHABLE FROM HERE. After the 4*TSEC loop,
 * `#ck2` does `move a10,a10 / jrnz KILL_CRD2`, and creditscreen passes
 * a10 = 1, so it always returns there. The `10*TSEC` loop at #lp1 and the
 * KILL_CRD exit that re-CREATEs attract_mode belong to the CRD_SCRN entry
 * (a10 = 0), which nothing in the attract loop uses.
 */
#define WM_ATTRACT_CREDIT_PLACE_TICKS 2
#define WM_ATTRACT_CREDIT_UNBLANK_TICKS 6
#define WM_ATTRACT_CREDIT_SETTLE_TSEC 1
#define WM_ATTRACT_CREDIT_WAIT_TSEC 4
#define WM_ATTRACT_CREDIT_BACKGROUND_SYMBOL "slateBMOD"

/* Operator-message source presentation / dan_test backdrop. */
#define WM_ATTRACT_OPERATOR_BACKGROUND_SYMBOL "SPORTBKBMOD"
#define WM_ATTRACT_OPERATOR_BALL_SYMBOL "BALLD05A"
#define WM_ATTRACT_OPERATOR_FONT_SYMBOL "osgfont_t"
#define WM_ATTRACT_OPERATOR_FIRST_Y 50
#define WM_ATTRACT_OPERATOR_X 200
#define WM_ATTRACT_OPERATOR_LINE_STEP 45
#define WM_ATTRACT_OPERATOR_PREWAIT_TICKS 120
#define WM_ATTRACT_OPERATOR_WAIT_TSEC 6
#define WM_ATTRACT_OPERATOR_BALL_COUNT 32
#define WM_ATTRACT_OPERATOR_BALL_X_LIMIT 400
#define WM_ATTRACT_OPERATOR_BALL_Y_LIMIT 255

#ifdef __cplusplus
}
#endif

#endif
