#ifndef WMANIA_ATTRACT_TEXT_H
#define WMANIA_ATTRACT_TEXT_H

#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
 * The attract screens' own words, out of ATTRACT.ASM's .string literals.
 *
 * wm/arcade/wmania_attract_data.h already carried each screen's layout, its
 * timing and its per-line LABELS in the source's order -- and the label was
 * all it carried. wm_attract_copyright_page1_labels held "copyright_ln1"
 * through "copyright_ln9", the string "copyright_ln1" appeared in exactly one
 * place in the whole tree, and nothing resolved it to text. So a screen whose
 * geometry and cadence were right had nothing to print.
 *
 * Generated by tools/wlattracttext.py, two ways round.
 *
 * aama_message and show_copyright both number their lines #ln1.., and `#`
 * makes those labels local, so those two are scoped per routine and carry a
 * port prefix: resolving "#ln1" by name alone would put "AAMA PARENTAL
 * ADVISORY" at the top of the copyright page.
 *
 * show_gen_tips, show_wres_tips, show_bios and DO_HINTS do not number their
 * lines at all -- they reach them through a pointer table -- and the names
 * those tables hold are unique in ATTRACT.ASM. So those are keyed by the
 * SOURCE label, unprefixed, which is what wm/arcade/wmania_attract_data.h's
 * own title_label / from_label / quote_label / wm_attract_general_tip_labels
 * fields already hold. Before this they held labels nothing resolved.
 *
 * A `\n` inside any of this text is ATTRACT.ASM's control byte 1, which
 * STRING.ASM:515 turns into a cursy step of @mess_line_spacing: a line break
 * inside one source literal, not two literals.
 */
typedef struct {
    const char *label;  /* the port label, e.g. "copyright_ln1" */
    const char *text;   /* ATTRACT.ASM's own .string, verbatim */
} wm_attract_text_entry;

extern const size_t wm_attract_text_count;
const wm_attract_text_entry *wm_attract_text_entries(void);

/* The text for a label, or NULL when the label has none. NULL is the honest
   answer for a screen this port has not extracted yet -- a caller must not
   substitute invented copy for it. */
const char *wm_attract_text(const char *label);

#ifdef __cplusplus
}
#endif
#endif
