#ifndef WMANIA_ATTRACT_TEXT_H
#define WMANIA_ATTRACT_TEXT_H

#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
 * The attract screens' own words, out of ATTRACT.ASM's .string literals.
 *
 * wm/arcade/wmania_attract_data.h already carried each screen's layout, its
 * timing and its per-line LABELS in the source's order -- and the label was
 * all it carried. wm_attract_copyright_page1_labels held "copyright_ln1"
 * through "copyright_ln9", the string "copyright_ln1" appeared in exactly one
 * place in the whole tree, and nothing resolved it to text. So a screen whose
 * geometry and cadence were right had nothing to print.
 *
 * Generated by tools/wlattracttext.py, scoped per routine: aama_message and
 * show_copyright both number their lines #ln1.., and `#` makes those labels
 * local, so resolving by name alone would put "AAMA PARENTAL ADVISORY" at the
 * top of the copyright page.
 */
typedef struct {
    const char *label;  /* the port label, e.g. "copyright_ln1" */
    const char *text;   /* ATTRACT.ASM's own .string, verbatim */
} wm_attract_text_entry;

extern const size_t wm_attract_text_count;
const wm_attract_text_entry *wm_attract_text_entries(void);

/* The text for a label, or NULL when the label has none. NULL is the honest
   answer for a screen this port has not extracted yet -- a caller must not
   substitute invented copy for it. */
const char *wm_attract_text(const char *label);

#ifdef __cplusplus
}
#endif
#endif
