#include <assert.h>
#include <stdio.h>
#include <string.h>
#include "wm_arcade_react4_core.h"
#define FX16(x) ((int32_t)((x)<<16))
typedef struct trace {int anim_calls,snd_calls,impact_calls,off_calls,gidd_calls,triple_calls,grade_calls,rope_calls,shaker_calls,unhandled_calls;wm_arcade_react1_anim_group_t anim;wm_arcade_react1_sound_t snd[8];wm_arcade_react1_impact_t impact;uint16_t triple[8];wm_arcade_move_grade_t grade;wm_arcade_react_anim_tag_t tag;int shaker;} trace_t;
static void t_anim(wm_arcade_actor_t*v,wm_arcade_react1_anim_group_t g,void*u){(void)v;trace_t*t=u;t->anim_calls++;t->anim=g;}
static void t_snd(wm_arcade_actor_t*v,wm_arcade_react1_sound_t s,void*u){(void)v;trace_t*t=u;if(t->snd_calls<8)t->snd[t->snd_calls]=s;t->snd_calls++;}
static void t_imp(wm_arcade_actor_t*a,wm_arcade_actor_t*v,wm_arcade_react1_impact_t i,void*u){(void)a;(void)v;trace_t*t=u;t->impact_calls++;t->impact=i;}
static void t_off(wm_arcade_actor_t*v,void*u){(void)v;((trace_t*)u)->off_calls++;}
static void t_gidd(wm_arcade_actor_t*v,void*u){(void)v;((trace_t*)u)->gidd_calls++;}
static void t_tri(wm_arcade_actor_t*v,uint16_t id,void*u){(void)v;trace_t*t=u;if(t->triple_calls<8)t->triple[t->triple_calls]=id;t->triple_calls++;}
static void t_grade(wm_arcade_actor_t*a,wm_arcade_actor_t*v,wm_arcade_move_grade_t g,void*u){(void)a;(void)v;trace_t*t=u;t->grade_calls++;t->grade=g;}
static wm_arcade_react_anim_tag_t t_tag(const wm_arcade_actor_t*a,void*u){(void)a;return ((trace_t*)u)->tag;}
static void t_rope(void*u){((trace_t*)u)->rope_calls++;}
static void t_shaker(int n,void*u){trace_t*t=u;t->shaker_calls++;t->shaker=n;}
static void t_un(wm_arcade_actor_t*a,wm_arcade_actor_t*v,wm_arcade_reaction_id_t r,void*u){(void)a;(void)v;(void)r;((trace_t*)u)->unhandled_calls++;}
static wm_arcade_react1_callbacks_t cbs(trace_t*t){wm_arcade_react1_callbacks_t c;memset(&c,0,sizeof(c));c.change_anim=t_anim;c.play_sound=t_snd;c.impact=t_imp;c.collisions_off=t_off;c.maybe_gidd_up=t_gidd;c.triple_sound=t_tri;c.move_grade=t_grade;c.attacker_anim_tag=t_tag;c.shake_all_ropes=t_rope;c.shaker2=t_shaker;c.unhandled_reaction=t_un;c.user=t;return c;}
static void actors(wm_arcade_actor_t*a,wm_arcade_actor_t*v){memset(a,0,sizeof(*a));memset(v,0,sizeof(*v));a->active=v->active=1;a->x_int=10;v->x_int=20;a->life=v->life=100;v->player_mode=WM_PMODE_NORMAL;a->anim_mode=v->anim_mode=WM_MODE_CHECKHIT;a->z_fixed=FX16(9);}
static void test_stomp_ignore(void){wm_arcade_actor_t a,v;trace_t t={0};int16_t p=-7;wm_arcade_react1_callbacks_t c=cbs(&t);wm_arcade_react1_context_t x;actors(&a,&v);wm_arcade_react1_context_init(&x,&c);wm_arcade_react4_apply(&a,&v,WM_RXN_STOMP,&p,NULL,&x);assert(p==0&&t.off_calls==1&&t.anim_calls==0);}
static void test_stomp_ground_and_bounces(void){wm_arcade_actor_t a,v;trace_t t={0};int16_t p=-7;wm_arcade_react1_callbacks_t c=cbs(&t);wm_arcade_react1_context_t x;actors(&a,&v);v.player_mode=WM_PMODE_ONGROUND;wm_arcade_react1_context_init(&x,&c);wm_arcade_react4_apply(&a,&v,WM_RXN_STOMP,&p,NULL,&x);assert(p==-7&&t.anim==WM_R1_ANIM_HIT_ON_GROUND&&t.snd[0]==WM_R1_SND_LBOWDROP&&t.triple[0]==0x43&&t.off_calls==2);
 actors(&a,&v);memset(&t,0,sizeof(t));c=cbs(&t);v.player_mode=WM_PMODE_ONGROUND;t.tag=WM_R_ANIMTAG_DNK_BELLY;a.x_vel=FX16(6);wm_arcade_react1_context_init(&x,&c);wm_arcade_react4_apply(&a,&v,WM_RXN_BUTTSTOMP,&p,NULL,&x);assert(a.x_vel==0&&a.y_vel==FX16(5)&&a.z_vel==FX16(1)&&t.rope_calls==1&&t.shaker_calls==1&&t.shaker==8&&t.off_calls==1);
 actors(&a,&v);memset(&t,0,sizeof(t));c=cbs(&t);v.player_mode=WM_PMODE_ONGROUND;t.tag=WM_R_ANIMTAG_LEX_FLYING_GROUND_PUNCH;wm_arcade_react1_context_init(&x,&c);wm_arcade_react4_apply(&a,&v,WM_RXN_STOMP,&p,NULL,&x);assert(a.y_vel==FX16(4)&&a.z_vel==FX16(1));}
static void test_shawn_stomp_sound(void){wm_arcade_actor_t a,v;trace_t t={0};int16_t p=-3;wm_arcade_react1_callbacks_t c=cbs(&t);wm_arcade_react1_context_t x;actors(&a,&v);v.player_mode=WM_PMODE_ONGROUND;t.tag=WM_R_ANIMTAG_SHN_RUN_STOMP;wm_arcade_react1_context_init(&x,&c);wm_arcade_react4_apply(&a,&v,WM_RXN_STOMP,&p,NULL,&x);assert(t.snd_calls==1&&t.snd[0]==WM_R1_SND_SCREAM&&t.triple_calls==0);}
static void test_bstomp(void){wm_arcade_actor_t a,v;trace_t t={0};wm_arcade_react1_callbacks_t c=cbs(&t);wm_arcade_react1_context_t x;actors(&a,&v);v.player_mode=WM_PMODE_INAIR;v.ground_y=10;v.y_int=40;wm_arcade_react1_context_init(&x,&c);wm_arcade_react4_apply(&a,&v,WM_RXN_BSTOMP,NULL,NULL,&x);assert(t.snd_calls==2&&t.snd[0]==WM_R1_SND_SCREAM&&t.snd[1]==WM_R1_SND_SCREAM);assert(t.triple[0]==0x43&&t.anim==WM_R1_ANIM_FALL_BACK&&v.x_vel==FX16(2)&&v.y_vel==-FX16(4));
 actors(&a,&v);memset(&t,0,sizeof(t));c=cbs(&t);a.wrestler_num=5;v.player_mode=WM_PMODE_INAIR;v.ground_y=0;v.y_int=99;wm_arcade_react1_context_init(&x,&c);wm_arcade_react4_apply(&a,&v,WM_RXN_BSTOMP,NULL,NULL,&x);assert(t.anim==WM_R1_ANIM_KNOCKDOWN);}
static void test_bstomp2_combo(void){wm_arcade_actor_t a,v;trace_t t={0};wm_arcade_react1_callbacks_t c=cbs(&t);wm_arcade_react1_context_t x;actors(&a,&v);a.combo_count=1;v.player_mode=WM_PMODE_ONGROUND;v.ground_y=12;v.y_int=30;v.y_vel=FX16(9);uint16_t old=v.obj_control;wm_arcade_react1_context_init(&x,&c);wm_arcade_react4_apply(&a,&v,WM_RXN_BSTOMP2,NULL,NULL,&x);assert(v.obj_control==(uint16_t)(old^WM_OBJ_FLIPH)&&v.y_int==12&&v.y_vel==0);assert(t.grade_calls==1&&t.grade==WM_R_MOVE_NASTY&&t.anim==WM_R1_ANIM_KNOCKDOWN&&t.off_calls==2);}
static void test_hammer_block(void){wm_arcade_actor_t a,v;trace_t t={0};wm_arcade_react1_callbacks_t c=cbs(&t);wm_arcade_react1_context_t x;actors(&a,&v);v.player_mode=WM_PMODE_BLOCK;wm_arcade_react1_context_init(&x,&c);wm_arcade_react4_apply(&a,&v,WM_RXN_HAMMER,NULL,NULL,&x);assert(t.triple[0]==0x45&&t.grade==WM_R_MOVE_NASTY&&t.anim==WM_R1_ANIM_HITBLOCK);}
static void test_spinkick_and_jumpkick(void){wm_arcade_actor_t a,v;trace_t t={0};wm_arcade_react1_callbacks_t c=cbs(&t);wm_arcade_react1_context_t x;actors(&a,&v);v.ground_y=0;v.y_int=19;wm_arcade_react1_context_init(&x,&c);wm_arcade_react4_apply(&a,&v,WM_RXN_SPINKICK,NULL,NULL,&x);assert(t.triple[0]==0x43&&t.grade==WM_R_MOVE_AVERAGE&&t.anim==WM_R1_ANIM_SPINKICK_HEAD_HIT);
 actors(&a,&v);memset(&t,0,sizeof(t));c=cbs(&t);v.ground_y=0;v.y_int=19;wm_arcade_react1_context_init(&x,&c);wm_arcade_react4_apply(&a,&v,WM_RXN_JUMPKICK,NULL,NULL,&x);assert(t.impact_calls==0&&t.snd[0]==WM_R1_SND_KICK&&t.anim==WM_R1_ANIM_JUMPKICK_HEAD_HIT);}
static void test_cline(void){wm_arcade_actor_t a,v;trace_t t={0};wm_arcade_react1_callbacks_t c=cbs(&t);wm_arcade_react1_context_t x;actors(&a,&v);a.attack_mode=WM_AMODE_CLINE;a.x_vel=FX16(5);a.z_vel=FX16(2);wm_arcade_react1_context_init(&x,&c);wm_arcade_react4_apply(&a,&v,WM_RXN_CLINE,NULL,NULL,&x);assert(t.impact==WM_R1_IMPACT_DROP_KICK&&t.snd[0]==WM_R1_SND_FLYKICK);assert(a.z_vel==0&&v.z_fixed==FX16(8)&&v.roll_pos==FX16(8));assert(v.x_vel==FX16(3)&&t.anim==WM_R1_ANIM_FALL_BACK2&&v.getup_time==0&&t.gidd_calls==1);}
static void test_headhold_noop(void){wm_arcade_actor_t a,v,save;trace_t t={0};wm_arcade_react1_callbacks_t c=cbs(&t);wm_arcade_react1_context_t x;actors(&a,&v);save=v;wm_arcade_react1_context_init(&x,&c);assert(wm_arcade_react4_apply(&a,&v,WM_RXN_HEADHOLD,NULL,NULL,&x));assert(memcmp(&v,&save,sizeof(v))==0&&t.off_calls==0);}
int main(void){test_stomp_ignore();test_stomp_ground_and_bounces();test_shawn_stomp_sound();test_bstomp();test_bstomp2_combo();test_hammer_block();test_spinkick_and_jumpkick();test_cline();test_headhold_noop();puts("Stage 6 REACT4 core tests: PASS");return 0;}
