/*
 * ANIM.ASM:1277 ANI_CODE's targets, translated.
 *
 * `_ani_code` is the plainest opcode in the machine -- `move *a4+,a0,L /
 * call a0` -- but it is the single biggest hole in this port's animation
 * VM: 2303 uses across the eight playable wrestlers' sequence files. They
 * collapse to 145 distinct routines, and 66 of those cover 92% of the
 * uses, so the work is bounded by the routines, not by the call sites.
 *
 * What is translated here is the DCSSOUND.ASM leaf sound routines: the ones
 * that pick a real sound index out of a real table -- by RNDRNG0, by
 * WRESTLERNUM, or by RPT_COUNT -- and hand it to triple_sound. Every index
 * and every table below is transcribed from DCSSOUND.ASM, never invented.
 *
 * triple_sound itself (DCSSOUND.ASM:2061) is a four-channel priority mixer
 * over triple_sndtab, and it is NOT translated here: the sound's own index
 * is passed through to wm_anim_env's `sound` callback unchanged, and
 * channel arbitration belongs to a DCSSOUND port rather than to this
 * bridge. The port's audio layer is already a command queue, so an index
 * is exactly what it wants.
 *
 * The announcer speech group (CALL_MISSES, CALL_SPECIAL_MOVE, CALL_SETUP,
 * CALL_ANI_AVERAGE_MOVE, CALL_NASTY_MOVE, CALL_THROWN_OUT,
 * CALL_OTHER_AVERAGE) is not in the registry below, because none of those
 * routines has a body of its own: each is a CREATE of a process that
 * sleeps and then calls ADD_IF_SILENT with its own table and percentage.
 * Both halves are data, generated by tools/wlvoice.py, so they resolve
 * straight out of wm_announce_calls[] -- see announce_call() below.
 */
#include "wm/anim_program.h"
#include "wm/arcade/wm_arcade_combat_defs.h"
#include "wm/arcade/wm_arcade_roster.h"
#include "wm/arcade/wm_arcade_veladd.h"
#include "wm/arcade/wmania_ring_geometry.h"
#include "wm/arcade/wm_arcade_butcount.h"
#include "wm/announce_tables.h"
#include "wm/arcade/wm_arcade_combo.h"
#include "wm/wrestler_sound_tables.h"
#include "wm/arcade/wmania_rope_command.h"
#include "wm/anim_puppet.h"

#include <string.h>

static void play(const wm_anim_env *env, uint16_t call) {
    /* `move a0,a0 / jrz` guards in the source: a zero table entry is "no
       sound", not sound zero. The spare roster slot below relies on it. */
    if (env && env->sound && call != 0u)
        env->sound(env->sound_user, call);
}

/* UTIL.ASM RNDRNG0, 0..max inclusive. With no RNG the source's own "first
   entry" is used rather than a made-up draw. */
static uint32_t rnd0(const wm_anim_env *env, uint32_t max_inclusive) {
    if (!env || !env->rng) return 0u;
    return wm_rng_rndrng0(env->rng, max_inclusive);
}

/*
 * UTIL.ASM:1734 RNDPER: stir RAND, take mul_high(1000, RAND) for a 0..999
 * draw, and `jrhi` -- the event happens when the probability exceeds the
 * draw. RNDRNG0(999) performs the identical stir and the identical
 * mul_high with the identical multiplier (999+1), so it reproduces RNDPER
 * exactly rather than approximating it.
 */
static bool rndper(const wm_anim_env *env, uint32_t per_mille) {
    if (!env || !env->rng) return false;
    return wm_rng_rndrng0(env->rng, 999u) < per_mille;
}

/* A wrestler-indexed table: WRESTLERNUM picks the row. The source indexes
   without a bounds test because WRESTLERNUM is always in range. */
static uint16_t by_wrestler(const wm_arcade_actor_t *actor,
                            const uint16_t *table, size_t n) {
    size_t i;
    if (!actor) return 0u;
    i = (size_t)actor->wrestler_num;
    return (i < n) ? table[i] : 0u;
}

/* ---------------------------------------------------------------- *
 * DCSSOUND.ASM:3999 HIT_THE_MAT -- by far the most-called ANI_CODE
 * routine in the game (339 uses). Two calls: a fixed one, then one of
 * three low-priority mat hits. The source's own commented-out head notes
 * an "outside the ring, use concrete instead" variant that was dropped
 * ("It doesn't sound right"), so there is deliberately no INRING test.
 * ---------------------------------------------------------------- */
static const uint16_t MAT_HITS[3] = { 0x76u, 0x77u, 0x78u };

static void hit_the_mat(wm_arcade_actor_t *actor, const wm_anim_env *env,
int32_t param) {
    (void)param;
    (void)actor;
    play(env, 0x0C1u);
    play(env, MAT_HITS[rnd0(env, 2u)]);
}

/* DCSSOUND.ASM:4020/4029. The source's own comment marks the third bounce
   entry "this one is way too loud"; it is kept as written. */
static const uint16_t SMALL_BOUNCE_SOUNDS[3] = { 0x0C0u, 0x0C2u, 0x00Du };
static const uint16_t SMALL_RUN_SOUNDS[3]    = { 0x0C0u, 0x0C2u, 0x0C0u };

static void small_bounce(wm_arcade_actor_t *actor, const wm_anim_env *env,
int32_t param) {
    (void)param;
    (void)actor;
    play(env, SMALL_BOUNCE_SOUNDS[rnd0(env, 2u)]);
}

static void small_run(wm_arcade_actor_t *actor, const wm_anim_env *env,
int32_t param) {
    (void)param;
    (void)actor;
    play(env, SMALL_RUN_SOUNDS[rnd0(env, 2u)]);
}

/* DCSSOUND.ASM:4045/4057 -- Doink's flame. */
static const uint16_t FLAME_SOUNDS[2]     = { 0x99u, 0x9Au };
static const uint16_t FLAME_HIT_SOUNDS[5] = { 0x9Du, 0x9Eu, 0x9Fu,
                                              0x0A0u, 0x0A1u };

static void do_flame_snd(wm_arcade_actor_t *actor, const wm_anim_env *env,
int32_t param) {
    (void)param;
    (void)actor;
    play(env, FLAME_SOUNDS[rnd0(env, 1u)]);
}

static void do_flame_hit_snd(wm_arcade_actor_t *actor, const wm_anim_env *env,
int32_t param) {
    (void)param;
    (void)actor;
    play(env, FLAME_HIT_SOUNDS[rnd0(env, 4u)]);
}

/* DCSSOUND.ASM:4134 DO_WAIL -- index 7 is the spare roster slot and is a
   real zero in the source, i.e. no sound. */
static const uint16_t WHICH_WAIL[9] = {
    0x25Fu, 0x270u, 0x20Du, 0x20Du, 0x20Du, 0x20Du, 0x20Du, 0u, 0x20Du
};

static void do_wail(wm_arcade_actor_t *actor, const wm_anim_env *env,
int32_t param) {
    (void)param;
    play(env, by_wrestler(actor, WHICH_WAIL, 9u));
}

/*
 * DCSSOUND.ASM:4223 FIND_AND_KILL_ENDLESS and the two routines that start
 * an endless sound. ENDLESS_SOUND is a single global in the source -- one
 * looping sound at a time for the whole machine -- so it is one here too.
 * The kill path walks WHICH_CHANNEL to clear that channel's priority and
 * duration and re-issue the sound to stop it; this port's audio layer has
 * no channel state to clear, so what is modelled is the part that is
 * observable through the same seam: the sound stops being the endless one.
 */
static uint16_t endless_sound;

static void find_and_kill_endless(wm_arcade_actor_t *actor,
                                  const wm_anim_env *env, int32_t param) {
    (void)param;
    (void)actor;
    (void)env;
    endless_sound = 0u;
}

static const uint16_t WHICH_CHOKE[9] = {
    0x21Au, 0x21Au, 0x21Au, 0x21Au, 0x21Au, 0x21Au, 0x21Au, 0u, 0x21Au
};
static const uint16_t WHICH_NONO[9] = {
    0x23Cu, 0x281u, 0x23Cu, 0x23Cu, 0x23Cu, 0x23Cu, 0x219u, 0u, 0x23Cu
};

static void do_choke(wm_arcade_actor_t *actor, const wm_anim_env *env,
int32_t param) {
    (void)param;
    uint16_t call = by_wrestler(actor, WHICH_CHOKE, 9u);
    find_and_kill_endless(actor, env, 0);
    play(env, call);
    endless_sound = call;
}

/* DO_OTHERNONO reads its OWN wrestler number; DO_NONO reads the number of
   the wrestler attached to it (*a13(ATTACH_PROC)), which is the one being
   held -- the two differ only in whose voice objects. */
static void do_othernono(wm_arcade_actor_t *actor, const wm_anim_env *env,
int32_t param) {
    (void)param;
    uint16_t call = by_wrestler(actor, WHICH_NONO, 9u);
    find_and_kill_endless(actor, env, 0);
    play(env, call);
    endless_sound = call;
}

static void do_nono(wm_arcade_actor_t *actor, const wm_anim_env *env,
int32_t param) {
    (void)param;
    const wm_arcade_actor_t *held = actor ? actor->attach_proc : NULL;
    uint16_t call = by_wrestler(held, WHICH_NONO, 9u);
    find_and_kill_endless(actor, env, 0);
    play(env, call);
    endless_sound = call;
}

/*
 * DCSSOUND.ASM:4153 DO_DOINK_SLAM: which taunt he uses depends on how far
 * through the repeat span he is. RPT_COUNT 0 or 1 is the plain slam;
 * otherwise DOINK_WHICH_SLAM[RPT_COUNT-1], and RPT_COUNT-1 >= 4 is silent.
 *
 * The table has three entries but that index can reach 3, one past the end
 * -- in the ROM that reads the first assembled word of the routine after
 * it. Reproducing a value this port cannot know would be inventing data, so
 * that one case plays nothing and says so here.
 */
static const uint16_t DOINK_WHICH_SLAM[3] = { 0x215u, 0x216u, 0x217u };

static void do_doink_slam(wm_arcade_actor_t *actor, const wm_anim_env *env,
int32_t param) {
    (void)param;
    int32_t rpt = actor ? actor->rpt_count : 0;
    if (rpt == 0 || rpt == 1) { play(env, 0x218u); return; }
    if (rpt - 1 >= 4) return;
    if ((size_t)(rpt - 1) < 3u) play(env, DOINK_WHICH_SLAM[rpt - 1]);
}

/*
 * DCSSOUND.ASM:4069-4090, the shove taunts. Each entry point loads a
 * different table and falls into the shared DO_PUSH_SPEECH: a 50%
 * RNDPER(500) gate, then a check that no shove taunt is already running
 * (the source spawns a 60-tick DUMMY_WAIT process and tests a flag), then
 * one line out of that wrestler's table. The word BEFORE each table is its
 * own RNDRNG0 maximum -- `move *A10(-10H),A0` -- so Razor picks between
 * three and everyone else has exactly one.
 */
static const uint16_t RAZOR_WHICH[3] = { 0x27Eu, 0x27Fu, 0x280u };
static const uint16_t DOINK_WHICH[1] = { 0x282u };
static const uint16_t SHAWN_WHICH[1] = { 0x283u };
static const uint16_t BRET_WHICH[1]  = { 0x285u };
static const uint16_t LEX_WHICH[1]   = { 0x286u };

/* The source's razor_swear_exists flag, held for 60 ticks by DUMMY_WAIT.
   Counted down by wm_anim_code_tick so the lockout is real rather than
   permanently open. */
static uint16_t push_speech_lockout;

static void push_speech(const wm_anim_env *env, const uint16_t *table,
                        uint32_t max_inclusive) {
    if (!rndper(env, 500u)) return;
    if (push_speech_lockout) return;
    push_speech_lockout = 60u;
    play(env, table[rnd0(env, max_inclusive)]);
}

static void do_razor_push(wm_arcade_actor_t *a, const wm_anim_env *e,
                          int32_t param)
    { (void)a; (void)param; push_speech(e, RAZOR_WHICH, 2u); }
static void do_doink_push(wm_arcade_actor_t *a, const wm_anim_env *e,
                          int32_t param)
    { (void)a; (void)param; push_speech(e, DOINK_WHICH, 0u); }
static void do_shawn_push(wm_arcade_actor_t *a, const wm_anim_env *e,
                          int32_t param)
    { (void)a; (void)param; push_speech(e, SHAWN_WHICH, 0u); }
static void do_bret_push(wm_arcade_actor_t *a, const wm_anim_env *e,
                          int32_t param)
    { (void)a; (void)param; push_speech(e, BRET_WHICH, 0u); }
static void do_lex_push(wm_arcade_actor_t *a, const wm_anim_env *e,
                          int32_t param)
    { (void)a; (void)param; push_speech(e, LEX_WHICH, 0u); }

/* ================================================================== *
 * The announcer speech group.
 *
 * `CALL_MISSES` and its eleven siblings are all the same three lines --
 * CREATE a SOUND_PID process, SLEEP, ADD_IF_SILENT with a table and a
 * percentage -- so what a call site needs is a delay and two numbers, and
 * wm_announce_calls[] carries all three straight out of DCSSOUND.ASM.
 *
 * The process is modelled as a pending slot counted down by
 * wm_anim_code_tick, which is where the source's other timed sound state
 * (razor_swear_exists above) already lives. GETPRC carries A7-A12 into a
 * created process, so the wrestler number captured at CREATE time is
 * captured here too rather than read again when the call fires.
 * ================================================================== */

/*
 * The source has as many SOUND_PID processes as it has free process slots.
 * Eight in flight is far past what the sequence files can start at once
 * (each is 5-15 ticks long and no animation calls two in a frame), and a
 * full list drops the call rather than overwriting a queued one.
 */
#define WM_ANN_PENDING_SLOTS 8

static struct {
    const wm_announce_table *table;
    wm_announcer_state *announcer;
    WmRng *rng;
    bool (*near_death)(void *user);
    void *user;
    /* GETPRC carries the crowd seam into the created process the same way
       it carries everything else the call needs. */
    void *crowd_user;
    void (*crowd_cheer)(void *user, int flags, int percent);
    void (*crowd_sound)(void *user, int sound, int ticks);
    bool (*crowd_busy)(void *user);
    uint16_t delay;
    uint16_t percent;
    int wrestler;              /* A5, or -1 when this caller never sets it */
} ann_pending[WM_ANN_PENDING_SLOTS];

static void announce_fire(size_t i) {
    wm_announce_ctx ctx;
    memset(&ctx, 0, sizeof(ctx));
    ctx.rng = ann_pending[i].rng;
    ctx.wrestler_num = ann_pending[i].wrestler;
    ctx.anyone_near_death = ann_pending[i].near_death;
    ctx.user = ann_pending[i].user;
    ctx.crowd_user = ann_pending[i].crowd_user;
    ctx.crowd_cheer = ann_pending[i].crowd_cheer;
    ctx.crowd_sound = ann_pending[i].crowd_sound;
    ctx.crowd_busy = ann_pending[i].crowd_busy &&
        ann_pending[i].crowd_busy(ann_pending[i].crowd_user);
    /* Every one of these callers uses ADD_IF_SILENT, not ADD_TO_QUEUE. */
    (void)wm_announce_from_table(ann_pending[i].announcer,
                                 ann_pending[i].table,
                                 ann_pending[i].percent, true, &ctx);
}

/*
 * LIFEBAR.ASM:3687 DO_COMBO_MESS, the most-called ANI_CODE routine in the
 * game at 193 sites. The logic is wm_arcade_do_combo_mess; this is the
 * bridge that hands it the services the env carries.
 */
static void do_combo_mess(wm_arcade_actor_t *actor, const wm_anim_env *env,
                          int32_t param) {
    wm_combo_mess_ctx ctx;
    (void)param;
    memset(&ctx, 0, sizeof(ctx));
    if (env) {
        ctx.sound_user = env->sound_user;
        ctx.sound = env->sound;
        ctx.announcer = env->announcer;
        ctx.award_user = env->award_user;
        ctx.round_award = env->round_award;
    }
    (void)wm_arcade_do_combo_mess(actor, &ctx);
}

/*
 * WRESTLE.ASM:6069 shake_all_ropes -- every bank at once,
 * `ROPE_BOUNCEUD` with the source's own selector of 2. Its NUM_OPPS guard
 * ("no shaking with two or more") is commented out in the source and is
 * left that way here.
 */
static void shake_all_ropes(wm_arcade_actor_t *actor, const wm_anim_env *env,
                            int32_t param) {
    static const int banks[4] = { WM_ROPE_FRONT, WM_ROPE_BACK,
                                  WM_ROPE_LEFT, WM_ROPE_RIGHT };
    size_t i;
    (void)param;
    if (!env || !env->rope_command) return;
    for (i = 0; i < 4; ++i)
        env->rope_command(env->rope_user, banks[i], WM_ROPE_BOUNCE_UD, 2,
                          actor ? actor->z_fixed : 0);
}

/*
 * WRESTLE.ASM:5978 get_leap -- may he lunge, or is he backing off?
 *
 * MODE_STATUS comes off first, and goes back on for "no": standing still
 * (both X and Z velocity zero), or holding the stick the way `mv_tbl` says
 * is AWAY for the direction he is facing. The table is four live rows in
 * sixteen -- NEW_FACING_DIR is only ever 5, 6, 9 or 10 (the source says
 * so in its own comment) -- and it reads a facing of 5 or 6 as "away is
 * right", 9 or 10 as "away is left".
 */
static void get_leap(wm_arcade_actor_t *actor, const wm_anim_env *env,
                     int32_t param) {
    int32_t away;
    (void)env;
    (void)param;
    if (!actor) return;
    actor->anim_mode &= (uint16_t)~WM_MODE_STATUS;

    if (actor->x_vel == 0 && actor->z_vel == 0) {   /* `jrz #novel` */
        actor->anim_mode |= (uint16_t)WM_MODE_STATUS;
        return;
    }
    /*
     * WRESTLE.ASM:6035 mv_tbl, indexed by NEW_FACING_DIR, holding a BIT
     * NUMBER for `btst a0,a1`. Facing up-left or down-left (5, 6), away
     * is right; facing up-right or down-right (9, 10), away is left.
     * Every other row is a literal 0, and `btst 0` is the UP bit -- not a
     * no-op. update_newfacing can only ever produce 5, 6, 9 or 10 (the
     * source says as much in its own comment), so those rows are dead,
     * but they are translated as written rather than as "nothing".
     */
    switch (actor->new_facing_dir) {
    case WM_MOVE_UP_LEFT:   case WM_MOVE_DOWN_LEFT:  away = WM_MOVE_RIGHT; break;
    case WM_MOVE_UP_RIGHT:  case WM_MOVE_DOWN_RIGHT: away = WM_MOVE_LEFT;  break;
    default:                                         away = WM_MOVE_UP;   break;
    }
    if (actor->move_dir & away)
        actor->anim_mode |= (uint16_t)WM_MODE_STATUS;
}

/*
 * WRESTLE2.ASM:3748 hit_nearest -- "set WHOIHIT and victim WHOPINNEDME",
 * and the victim's PINNED bit with them. CLOSEST_NUM is the fixed
 * opponent in this port (see wm/arcade/wm_arcade_closest.h for why), so
 * the process-table walk is the smart target.
 */
static void hit_nearest(wm_arcade_actor_t *actor, const wm_anim_env *env,
                        int32_t param) {
    wm_arcade_actor_t *victim;
    (void)param;
    if (!actor) return;
    victim = actor->smart_target ? actor->smart_target
                                 : (env ? env->opponent : NULL);
    if (!victim) return;
    actor->who_i_hit = victim;
    victim->who_pinned_me = actor;
    victim->status_flags |= (uint32_t)WM_STATUS_PINNED;
}

/*
 * WRESTLE2.ASM:3040 set_tbukl_confine -- climbing a turnbuckle, and
 * whether the ring is allowed to hold you in while you do it.
 *
 * The sweep asks one question of every opponent: is anybody on the other
 * team OUTSIDE the ring? If so this wrestler gets MODE_NOCONFINE, because
 * the attack he is about to launch has to be able to follow them out.
 * Otherwise NOCONFINE comes off -- and, since he may have drifted out
 * already, he is yanked back: INRING cleared, GROUND_Y put back on the
 * mat, Z clamped to RING_TOP, and X clamped to whichever rope line he is
 * on the wrong side of, through calc_line_x.
 *
 * Two details that are easy to lose. Yokozuna skips the sweep outright
 * (`cmpi W_YOKO / jreq #clear_noconfine`) and is always confined. And the
 * "everyone on the enemy side is dead" flag, taken from the CLOSEST
 * opponent's PLYRMODE, does not make the routine give up -- it makes it
 * STOP SKIPPING dead opponents, so a dead man lying outside the ropes
 * still grants NOCONFINE.
 *
 * INRING's polarity is the source's, not this port's: PLYR.EQU:103 says
 * 0 = in the ring, so `jrnz #set_noconfine` fires for a wrestler who is
 * OUT. The port stores the ordinary boolean, so the test flips.
 */
static void set_tbukl_confine(wm_arcade_actor_t *actor, const wm_anim_env *env,
                              int32_t param) {
    wm_arcade_actor_t *opp;
    bool other_team_dead;
    (void)param;
    if (!actor) return;

    if (actor->wrestler_num != WM_ROSTER_YOKO) {
        opp = actor->smart_target ? actor->smart_target
                                  : (env ? env->opponent : NULL);
        /* `a3 is the 'everyone is dead' flag`, from CLOSEST_NUM alone. */
        other_team_dead = opp && opp->player_mode == WM_PMODE_DEAD;
        /* The sweep skips inactive slots, self, and teammates; in a
           1-on-1 match that leaves exactly the opponent. */
        if (opp && opp->active && opp->player_side != actor->player_side &&
            (other_team_dead || opp->player_mode != WM_PMODE_DEAD) &&
            !opp->in_ring) {
            actor->anim_mode |= (uint16_t)WM_MODE_NOCONFINE;
            return;                                /* `#set_noconfine` */
        }
    }

    /* `#clear_noconfine`: "he might have drifted out already, so we gotta
       yank 'em back in." */
    if (!actor->in_ring) {
        actor->in_ring = 1;
        actor->ground_y = WM_MAT_Y;
        if (actor->z_int < WM_RING_TOP) {
            actor->z_int = WM_RING_TOP;
            actor->z_fixed = (int32_t)WM_RING_TOP << 16;
        }
        if (actor->x_int <= WM_RING_X_CENTER) {    /* `jrgt #rt` */
            int32_t x = wm_ring_calc_line_x(
                wm_ring_boundary_seed(WM_RING_BOUNDARY_LEFT_ROPE),
                actor->z_int);
            /* `jrz #xok` -- "bad news. leave it alone." -- and then
               `cmp a0,a2 / jrge #xok`, so he is pushed only when he is
               already left OF the left rope line. */
            if (x != 0 && actor->x_int < x) {
                actor->x_int = x;
                actor->x_fixed = x << 16;
            }
        } else {
            int32_t x = wm_ring_calc_line_x(
                wm_ring_boundary_seed(WM_RING_BOUNDARY_RIGHT_ROPE),
                actor->z_int);
            if (x != 0 && actor->x_int > x) {   /* `jrle #xok` */
                actor->x_int = x;
                actor->x_fixed = x << 16;
            }
        }
    }
    actor->anim_mode &= (uint16_t)~WM_MODE_NOCONFINE;
}

/*
 * DNKSEQ2.ASM:5202 win_announce, the whole of it:
 *
 *     move  a13,a10
 *     CREATE ANNC_PID,announce_rnd_winner
 *     CALLA KILL_PIN_HIM
 *
 * A pin animation calls it the moment the pin sticks. Everything it does
 * is in the process it starts, which is what actually ends the round --
 * so this is a seam onto the match, exactly like the crowd and the ropes.
 * `move a13,a10` is the source handing the process its creator through
 * GETPRC's register carry, which is how announce_rnd_winner knows whose
 * PLYR_SIDE to announce; the port's own set_winner finds him from the
 * roster instead, the same search the source runs a few lines later.
 */
static void win_announce(wm_arcade_actor_t *actor, const wm_anim_env *env,
                         int32_t param) {
    (void)actor;
    (void)param;
    if (!env || !env->win_announce) return;
    env->win_announce(env->round_user);
}

/*
 * DNKSEQ2.ASM:5221 grnd_hit, "FOR USE ONLY IN PINS!"
 *
 * The pinner hits the man he is pinning, and the source argues with
 * itself about whose pointer to use for it -- one comment says use
 * CLOSEST because you do not actually attack during a pin, and the
 * comment below it overrules that: "Un! DO use WHOIHIT, as this is set in
 * all the pin_anims before this function is called." So WHOIHIT it is,
 * and the commented-out CLOSEST_NUM walk is left where it was.
 *
 * Two halves. The victim is put into his own hitonground animation,
 * looked up in `#hit_t` by HIS wrestler number, through the same
 * change_anim1a seam ANI_SLAVEANIM uses. Then the two are aligned in Z --
 * pinner to victim+1.0, victim to victim-1.0, so the pinner draws in
 * front -- unless the PINNER is the Undertaker (`subk 2,a0 / jrz #z`),
 * who is left where he is.
 */
#define WM_GRND_HIT_Z_GAP 0x10000       /* the source's own [1,0] */

static void grnd_hit(wm_arcade_actor_t *actor, const wm_anim_env *env,
                     int32_t param) {
    wm_arcade_actor_t *victim;
    const char *label;
    int32_t z;
    (void)param;

    if (!actor) return;
    victim = actor->who_i_hit;
    if (!victim) return;                          /* `jrz` on a null WHOIHIT */

    label = wm_anim_code_roster_label("grnd_hit", victim->wrestler_num);
    if (label && env && env->change_opp_anim) {
        victim->puppet_frame = 0;      /* he drives himself again now */
        env->change_opp_anim(victim, label, env->slave_user);
    }

    /* "align on target's z, unless we're taker" */
    if (actor->wrestler_num == WM_ROSTER_TAKER) return;

    z = victim->z_fixed;
    actor->z_fixed = z + WM_GRND_HIT_Z_GAP;
    actor->z_int = actor->z_fixed >> 16;
    victim->z_fixed = z - WM_GRND_HIT_Z_GAP;
    victim->z_int = victim->z_fixed >> 16;
}

/*
 * LEXSEQ3.ASM:2619 #setopp_deadanim -- "If killed, don't change anim"
 * (PLYR.EQU:413) on whoever this wrestler is attached to, so a victim who
 * dies mid-move keeps playing the move's own ending instead of being
 * yanked into his death animation. `SF_CLEAR_BITS` clears it again, which
 * is what PLYR.EQU means by "cleared often".
 */
static void setopp_deadanim(wm_arcade_actor_t *actor, const wm_anim_env *env,
                            int32_t param) {
    (void)env;
    (void)param;
    if (!actor || !actor->attach_proc) return;    /* `jrz #rets` */
    actor->attach_proc->status_flags |= (uint32_t)WM_STATUS_DEAD_ANIM;
}

/*
 * CROWD.ASM:1119 DO_CROWD_CHEER, the whole of it:
 *
 *     MOVK  C_OVERIDE|C_LONG,A3
 *     CLR   A4
 *     (falls into crowd_cheer)
 *
 * So the routine is its two arguments -- interrupt whatever the crowd is
 * doing, run the long animation, and no randomness, which makes A4 dead
 * (crowd_cheer only reads it when B_RANDOM is set). crowd_cheer itself
 * walks NUMCROWD members of CROWDDATA setting each one's SCPTR to its
 * CHEER1 or CHEER2 script; that is a sprite subsystem this port has not
 * got, so it is reached through wm_anim_env like triple_sound and the
 * rope commands are.
 */
static void do_crowd_cheer(wm_arcade_actor_t *actor, const wm_anim_env *env,
                           int32_t param) {
    (void)actor;
    (void)param;
    if (!env || !env->crowd_cheer) return;
    env->crowd_cheer(env->crowd_user, WM_CROWD_OVERRIDE | WM_CROWD_LONG, 0);
}

/*
 * DNKSEQ3.ASM:2256 spunch_delay -- skick_delay's twin, with a gate in
 * front of it. The delay check runs only when this is NOT a royal rumble
 * AND either both players are human (PSTATUS==3) or there is exactly one
 * opponent:
 *
 *     move @royal_rumble,a0 / jrnz #ok
 *     move @PSTATUS,a0 / subk 3,a0 / jrz #cont
 *     move @NUM_OPPS,a0 / subk 1,a0 / jrnz #ok
 *
 * skick_delay has the same shape with only the royal-rumble half, and its
 * commented-out lines in the source are this gate -- so the two were
 * written together and one had it disabled.
 *
 * This port starts either the PSTATUS==0 attract match or the
 * single-human #1plyr one and always creates exactly one opponent, so the
 * gate resolves to "check" for every match it can currently run. It is
 * evaluated from wm_anim_env rather than assumed, so that stays true by
 * reading the values rather than by a comment.
 */
#define WM_SPUNCH_WINDOW (2 * 60)
#define WM_PSTATUS_BOTH_HUMAN 3

static void spunch_delay(wm_arcade_actor_t *actor, const wm_anim_env *env,
                         int32_t param) {
    uint32_t previous, now;
    (void)param;
    if (!actor) return;

    if (env && env->royal_rumble) return;                  /* `jrnz #ok` */
    if (!env ||
        !(env->pstatus == WM_PSTATUS_BOTH_HUMAN || env->num_opps == 1))
        return;                                            /* `jrnz #ok` */

    now = env->pcnt;
    previous = actor->last_spunch;
    actor->last_spunch = now;              /* stamped before the compare */
    if ((uint32_t)(now - previous) >= (uint32_t)WM_SPUNCH_WINDOW) return;
    actor->anim_mode |= (uint16_t)WM_MODE_STATUS;
}

/*
 * SHNSEQ3.ASM:3663 #check_xvel -- distinct from the global check_xvel
 * above, and doing something different: push him 2.0 the way he is
 * FACING if he is not already moving that way, and kill the Z drift with
 * it. (The early-out skips the Z clear too, which is why it is written
 * inside the branch rather than after it.)
 */
#define WM_CHECK_XVEL_FACE 0x20000

static void check_xvel_local(wm_arcade_actor_t *actor,
                             const wm_anim_env *env, int32_t param) {
    (void)env;
    (void)param;
    if (!actor) return;
    if (actor->facing_dir & WM_MOVE_RIGHT) {
        if (actor->x_vel > 0) return;         /* `jrp #done0` */
        actor->x_vel = WM_CHECK_XVEL_FACE;
    } else {
        if (actor->x_vel < 0) return;         /* `jrn #done0` */
        actor->x_vel = -WM_CHECK_XVEL_FACE;
    }
    actor->z_vel = 0;
}

/*
 * SHNSEQ3.ASM:2948 #grunt -- `WRSND W_SHAWN,GRABFLING_T1,GRABFLING_T2`.
 * Like LEXSEQ3's DO_GRUNT it names the wrestler outright rather than
 * reading WRESTLERNUM, so it always uses Shawn's row.
 */
#define WM_WRSND_W_SHAWN 4

static void shawn_grunt(wm_arcade_actor_t *actor, const wm_anim_env *env,
                        int32_t param) {
    (void)actor;
    (void)param;
    (void)wm_wrsndx(WM_WRSND_W_SHAWN, WM_WRSND_GRABFLING_T1,
                    WM_WRSND_GRABFLING_T2, env ? env->rng : NULL,
                    env ? env->sound_user : NULL, env ? env->sound : NULL);
}

/* BAMSEQ2.ASM:1347 #hit_ground -- snap him onto the ground he is over. */
static void hit_ground(wm_arcade_actor_t *actor, const wm_anim_env *env,
                       int32_t param) {
    (void)env;
    (void)param;
    if (actor) actor->y_int = actor->ground_y;
}

/*
 * Hold the victim's getup meter off. Two routines share this: YOKSEQ2's
 * `#delay_whoihit` for 55 ticks, and UNDSEQ3's `#set` for eight seconds
 * -- the same body with a different window, so the window is the
 * registry's param.
 */
static void delay_whoihit_param(wm_arcade_actor_t *actor,
                                const wm_anim_env *env, int32_t ticks) {
    (void)env;
    if (actor && actor->who_i_hit) actor->who_i_hit->delay_meter = ticks;
}

/*
 * SHNSEQ2.ASM:1158 #zero_x_4 -- "Don't float if dropping straight down".
 * Kill the X drift unless the opponent is well off to the side.
 */
#define WM_ZERO_X4_SIDE 64

static void zero_x_4(wm_arcade_actor_t *actor, const wm_anim_env *env,
                     int32_t param) {
    (void)env;
    (void)param;
    if (!actor) return;
    if (actor->closest_xdist > WM_ZERO_X4_SIDE) return;   /* `jrgt #ok4` */
    actor->x_vel = 0;
}

/*
 * SHNSEQ3.ASM:316 #no_bk_xvel, and the file-scoping trap once more: the
 * GLOBAL no_bk_xvel kills only OBJ_XVEL, and this local copy kills
 * OBJ_ZVEL as well. The source's own header says when to use it --
 * "zeros the wrestler's x-velocity if he's flying backwards. Useful just
 * after a LEAPAT."
 */
static void no_bk_xvel_local(wm_arcade_actor_t *actor,
                             const wm_anim_env *env, int32_t param) {
    int32_t forward;
    (void)env;
    (void)param;
    if (!actor) return;
    /* Facing-relative: negate when he faces left, so `forward` is always
       "along the way he is pointing". */
    forward = (actor->facing_dir & WM_MOVE_RIGHT) ? actor->x_vel
                                                  : -actor->x_vel;
    if (forward >= 0) return;                 /* `jrnn #ok` */
    actor->x_vel = 0;
    actor->z_vel = 0;                         /* the local copy's extra */
}

/*
 * LEXSEQ3.ASM:2220 #ck_flip -- face into the ring from whichever side he
 * is on, flipping the sprite only when it is not already the right way
 * round. Note the two sides test the flip bit with OPPOSITE senses
 * (`jrz` on the left, `jrnz` on the right), which is what makes each one
 * end up facing inward.
 */
static void ck_flip(wm_arcade_actor_t *actor, const wm_anim_env *env,
                    int32_t param) {
    int32_t facing;
    int flipped;
    (void)env;
    (void)param;
    if (!actor) return;

    flipped = (actor->obj_control & WM_OBJ_FLIPH) != 0;
    if (actor->x_int > WM_RING_X_CENTER) {
        facing = WM_MOVE_LEFT | WM_MOVE_DOWN;
        if (!flipped) {                       /* `jrnz #no_flip` */
            actor->obj_control ^= (uint16_t)WM_OBJ_FLIPH;
            facing ^= (WM_MOVE_LEFT | WM_MOVE_RIGHT);
        }
    } else {
        facing = WM_MOVE_RIGHT | WM_MOVE_DOWN;
        if (flipped) {                        /* `jrz #no_flip` */
            actor->obj_control ^= (uint16_t)WM_OBJ_FLIPH;
            facing ^= (WM_MOVE_LEFT | WM_MOVE_RIGHT);
        }
    }
    actor->facing_dir = facing;
}

/*
 * HRTSEQ3.ASM:2550 #ck_dead_opp -- is the man I am holding dead? Reports
 * through MODE_STATUS, and reads ATTACH_PROC first, falling back to
 * WHOIHIT when the grapple has already been broken.
 */
static void ck_dead_opp(wm_arcade_actor_t *actor, const wm_anim_env *env,
                        int32_t param) {
    const wm_arcade_actor_t *opp;
    (void)env;
    (void)param;
    if (!actor) return;
    opp = actor->attach_proc ? actor->attach_proc : actor->who_i_hit;
    if (!opp) return;
    if (opp->life == 0) actor->anim_mode |= (uint16_t)WM_MODE_STATUS;
}

/*
 * HRTSEQ4.ASM:1134 #set_wrestler_xflip -- the same body as
 * ANI_SET_WRESTLER_XFLIP, reached as a routine instead of an opcode.
 */
static void set_wrestler_xflip_code(wm_arcade_actor_t *actor,
                                    const wm_anim_env *env, int32_t param) {
    (void)env;
    (void)param;
    if (!actor) return;
    if (actor->facing_dir & WM_MOVE_RIGHT)
        actor->obj_control &= (uint16_t)~WM_OBJ_FLIPH;
    else
        actor->obj_control |= (uint16_t)WM_OBJ_FLIPH;
}

/* ================================================================== *
 * The last of the self-contained tail.
 * ================================================================== */

/*
 * UNDSEQ3.ASM:1046 inc_loop -- the Undertaker's chokehold counter. Bump
 * USR_VAR1 and report through MODE_STATUS whether it has run past two:
 * set means "break out", clear means "go round again". Distinct from
 * `#inc_loop`, which is a different routine with its own per-file caps.
 */
#define WM_INC_LOOP_CAP 2

static void und_inc_loop(wm_arcade_actor_t *actor,
                         const wm_anim_env *env, int32_t param) {
    (void)env;
    (void)param;
    if (!actor) return;
    ++actor->usr_var1;
    if (actor->usr_var1 > WM_INC_LOOP_CAP)
        actor->anim_mode |= (uint16_t)WM_MODE_STATUS;      /* #breakout */
    else
        actor->anim_mode &= (uint16_t)~WM_MODE_STATUS;
}

/*
 * DNKSEQ2.ASM:3335 check_xvel -- a global SUBR that seven other files
 * call. It stops a toss that would carry the victim out over the ropes:
 * if he is heading further out from the middle, reverse him to 1.5
 * inward and report it through MODE_STATUS, with the source's own note
 * on why -- "Will land on ropes".
 *
 * The opponent's INRING gate reads `jrnz #ok`, and INRING is 1 for
 * OUTSIDE, so the source does nothing when the opponent is out of the
 * ring -- its comment says exactly that. This port's boolean is
 * inverted, so the test flips.
 */
#define WM_CHECK_XVEL_PUSH 0x18000

static void check_xvel(wm_arcade_actor_t *actor, const wm_anim_env *env,
                       int32_t param) {
    const wm_arcade_actor_t *opp = env ? env->opponent : NULL;
    (void)param;
    if (!actor) return;

    actor->anim_mode &= (uint16_t)~WM_MODE_STATUS;
    /* "don't mess with anything if opponent is ouside the ring" */
    if (!opp || !opp->in_ring) return;

    if (actor->x_int > WM_RING_X_MID) {
        /* `jrn #ok` -- already heading back in, so leave him alone. */
        if (actor->x_vel < 0) return;
        actor->x_vel = -WM_CHECK_XVEL_PUSH;
    } else {
        /* `jrnn #ok` -- likewise on the left. */
        if (actor->x_vel >= 0) return;
        actor->x_vel = WM_CHECK_XVEL_PUSH;
    }
    actor->anim_mode |= (uint16_t)WM_MODE_STATUS;
}

/*
 * `#reduce_dmg` -- MACROS.H:714's SPCDMG: stamp SPECIAL_DAMAGE_TIME with
 * PCNT plus a window and arm NEXT_DAMAGE. Three files, three different
 * pairs, so the constants are the registry's param rather than three
 * bodies: Razor RD_PILEDRIVER (22) for 80 ticks, Shawn D_STOMP2 (6) and
 * the Undertaker D_PUNCH (8), both for 40 -- and both of those carry the
 * same source comment, "Neck breaker may take awhile".
 */
static void reduce_dmg(wm_arcade_actor_t *actor, const wm_anim_env *env,
                       int32_t packed) {
    if (!actor) return;
    actor->special_damage_time = (env ? env->pcnt : 0u) +
                                 (uint32_t)(packed & 0xFFFF);
    actor->next_damage = (int16_t)((packed >> 16) & 0xFFFF);
}
#define WM_SPCDMG(damage, ticks) (((int32_t)(damage) << 16) | (ticks))

/*
 * `#reattach` -- put the grapple back together after a hit broke it, in
 * both directions. Identical in all three files that define it.
 */
static void reattach(wm_arcade_actor_t *actor, const wm_anim_env *env,
                     int32_t param) {
    (void)env;
    (void)param;
    if (!actor || !actor->who_i_hit) return;
    actor->attach_proc = actor->who_i_hit;
    actor->who_i_hit->attach_proc = actor;
}

/*
 * SET_OPP_GRAV_NORM / SET_OPP_GRAV_LOW -- hand the man being held a
 * different fall rate for the length of a move. `param` is the gravity.
 * Both are bare labels, so both are file-local, and both files spell
 * them identically.
 */
static void set_opp_grav(wm_arcade_actor_t *actor, const wm_anim_env *env,
                         int32_t gravity) {
    (void)env;
    if (actor && actor->who_i_hit) actor->who_i_hit->gravity = gravity;
}

/*
 * `#go_high` -- "Go higher for last hit!". Pops the closest wrestler
 * upward, EXCEPT Yokozuna, whom the source declines with a two-word
 * explanation: "Yoko too fat".
 *
 * Doink's and Bret's copies use 5.0 and Razor's uses 4.0, so the amount
 * is the registry's param. Doink's copy also carries a commented-out
 * earlier version that read ATTACH_PROC instead, with the note "Got rid
 * of this because attach_proc is a zero after a hit" -- which is why all
 * three read the closest wrestler.
 */
static void go_high(wm_arcade_actor_t *actor, const wm_anim_env *env,
                    int32_t yvel) {
    wm_arcade_actor_t *opp = env ? env->opponent : NULL;
    (void)actor;
    if (!opp) return;
    if (opp->wrestler_num == WM_ROSTER_YOKO) return;    /* "Yoko too fat" */
    opp->y_vel = yvel;
}

/*
 * WRESTLE2.ASM:3669 target_whoihit -- aim the smart-attack system at the
 * man just hit, rather than at whoever is closest.
 */
static void target_whoihit(wm_arcade_actor_t *actor, const wm_anim_env *env,
                           int32_t param) {
    (void)env;
    (void)param;
    if (!actor) return;
    actor->status_flags |= WM_STATUS_SMART_ATTACK;
    actor->smart_target = actor->who_i_hit;
}

/* SHNSEQ3.ASM:3691 #set_opp_facing -- turn the held man around, by
   XOR-ing the two horizontal bits of his FACING_DIR. */
static void set_opp_facing(wm_arcade_actor_t *actor, const wm_anim_env *env,
                           int32_t param) {
    (void)env;
    (void)param;
    if (!actor || !actor->attach_proc) return;
    actor->attach_proc->facing_dir ^= (WM_MOVE_LEFT | WM_MOVE_RIGHT);
}

/* RZRSEQ2.ASM:1528 #blocked_vels -- bounced off a block: 3.0 up, and
   half the X velocity back the other way. */
static void blocked_vels(wm_arcade_actor_t *actor, const wm_anim_env *env,
                         int32_t param) {
    (void)env;
    (void)param;
    if (!actor) return;
    actor->y_vel = 0x30000;
    actor->x_vel = -(actor->x_vel >> 1);
}

/*
 * DCSSOUND.ASM:4398 MAYBE_BOUNCE_ROPE -- "into the ropes!", but only
 * sometimes. `MOVK 10,A0 / CALLA RNDRNG0 / MOVE A0,A0 / JRNZ` speaks
 * only when the draw lands exactly on zero, and RNDRNG0's maximum is
 * inclusive, so that is one time in eleven rather than one in ten.
 *
 * Its three siblings just below it in the source -- MAYBE_HIGH_RISK,
 * MAYBE_TOUGH_ENOUGH, MAYBE_SHOCKING -- are the same shape but end in
 * DIE rather than RETS: they are processes created elsewhere, and no
 * animation calls them, so they are not registered here.
 */
#define WM_VOICE_INTO_THE_ROPES 0x15Bu
#define WM_BOUNCE_ROPE_ONE_IN 10u

static void maybe_bounce_rope(wm_arcade_actor_t *actor,
                              const wm_anim_env *env, int32_t param) {
    (void)actor;
    (void)param;
    if (!env || !env->rng || !env->announcer) return;
    if (rnd0(env, WM_BOUNCE_ROPE_ONE_IN) != 0u) return;
    (void)wm_announcer_add_if_silent(env->announcer, WM_VOICE_INTO_THE_ROPES);
}

/*
 * `#set_trgt` -- where to land when climbing out onto the apron. Pure
 * geometry over the TGT_* offsets: the near side's apron X, mid-ring Z,
 * and the mat's own Y.
 *
 * SEVEN of the eight copies are identical at RING_X_CENTER +/- (0f8h+60).
 * Doink's is 0f8h+50 -- ten units further in. That is the whole reason
 * this registry is keyed on (name, file): resolving `#set_trgt` by bare
 * name would put Doink on everyone else's apron.
 */
#define WM_APRON_X_BASE 0x0F8

static void set_trgt(wm_arcade_actor_t *actor, const wm_anim_env *env,
                     int32_t apron_margin) {
    int32_t off = WM_APRON_X_BASE + apron_margin;
    (void)env;
    if (!actor) return;
    /* `cmpi RING_X_CENTER,a14 / jrlt #onlft` -- exactly on centre takes
       the RIGHT apron, since the test is strictly less-than. */
    actor->tgt_xoff = (actor->x_int < WM_RING_X_CENTER)
                          ? (WM_RING_X_CENTER - off)
                          : (WM_RING_X_CENTER + off);
    actor->tgt_zoff = WM_RING_Z_CENTER;
    actor->tgt_yoff = WM_MAT_Y;
}

/*
 * `#clrcnt` -- one clear, with the source's own note on why the field is
 * an odd one to use: "We are re-using BUT_COUNT in the player process".
 * Identical in all four files that define it.
 */
static void clrcnt(wm_arcade_actor_t *actor, const wm_anim_env *env,
                   int32_t param) {
    (void)env;
    (void)param;
    if (actor) actor->but_count = 0;
}

/*
 * HRTSEQ3.ASM:2896 #rope_check -- the roll-uppercut hitting the ropes.
 *
 * This is the only translated routine that writes ANIPC, the animation's
 * own program counter: `movi #stand,a14 / move a14,*a13(ANIPC),L`. ANIPC
 * is a field on the wrestler, so the routine sets it and the interpreter
 * applies it as soon as the routine returns.
 *
 * The target it names is worth spelling out. `#stand` is a label inside
 * hrt_roll_uppercut_anim, and #rope_check is a single SUBRP shared by
 * that animation AND by hrt_combo_roll_uppercut_anim, which has its own
 * `#standc` tail -- the one that does DO_COMBO_MESS and ANI_CLEAR_COMBO.
 * The routine jumps to `#stand` either way. So a COMBO roll-uppercut
 * that ends against the ropes runs the plain animation's tail and never
 * announces the combo or clears the count, and `#standc` is defined once
 * and branched to from nowhere -- dead code in the shipped ROM.
 *
 * Translated as written, because that is what the machine does.
 */
#define WM_ROPE_CHECK_SOUND 0x03Cu
static const char ROPE_CHECK_TARGET_PROGRAM[] = "hrt_roll_uppercut_anim";
static const char ROPE_CHECK_TARGET_LABEL[] = "#stand";

static void rope_check(wm_arcade_actor_t *actor, const wm_anim_env *env,
                       int32_t param) {
    int32_t against;
    int bank;
    (void)param;
    if (!actor) return;

    /* `andi MOVE_LEFT|MOVE_RIGHT,a1 / jrz #rets` -- CAN_MOVE_DIR still
       allows sideways movement, so he is not up against a rope. */
    against = actor->can_move_dir & (WM_MOVE_LEFT | WM_MOVE_RIGHT);
    if (against == 0) return;

    actor->anipc_program = ROPE_CHECK_TARGET_PROGRAM;
    actor->anipc_label = ROPE_CHECK_TARGET_LABEL;

    /* `btst MOVE_RIGHT_BIT,a1` picks which side wobbles. */
    bank = (against & WM_MOVE_RIGHT) ? WM_ROPE_RIGHT : WM_ROPE_LEFT;
    if (env && env->rope_command)
        env->rope_command(env->rope_user, bank, WM_ROPE_BOUNCE_IO, 0,
                          actor->z_fixed);
    play(env, WM_ROPE_CHECK_SOUND);
}

/* ================================================================== *
 * Targeting and drift: five more self-contained routines.
 *
 * Each reads and writes only the actor it is given, plus ring geometry,
 * which is why they translate one-for-one.
 * ================================================================== */

/*
 * BAMSEQ3.ASM:764 set_xdrift, with the source's own note: "Float / This
 * could become a leap at position command / Leap at the center of ring!"
 *
 * Only in the ring, and only if he is already more than 60h from the
 * screen midline -- inside that he is close enough. Then a flat 3.0 of X
 * velocity toward the middle.
 *
 * The INRING test is `jrnz #ok`, and PLYR.EQU:103 says INRING is 0 for IN
 * the ring and 1 for outside, so the source skips when he is OUT. This
 * port stores the ordinary boolean, so the test flips.
 */
#define WM_XDRIFT_DEADBAND 0x60
#define WM_XDRIFT_VEL 0x30000

static void set_xdrift(wm_arcade_actor_t *actor, const wm_anim_env *env,
                       int32_t param) {
    int32_t dx;
    (void)env;
    (void)param;
    if (!actor) return;
    if (!actor->in_ring) return;              /* `jrnz #ok`, inverted */

    dx = actor->x_int - WM_RING_X_MID;
    if (dx < 0) dx = -dx;                     /* `abs a0` */
    if (dx < WM_XDRIFT_DEADBAND) return;

    /* `cmpi RING_X_MID,a0 / jrgt #onrgt` -- exactly on the midline takes
       the left branch and drifts right. */
    actor->x_vel = (actor->x_int > WM_RING_X_MID) ? -WM_XDRIFT_VEL
                                                  : WM_XDRIFT_VEL;
}

/*
 * DNKSEQ2.ASM:5303 set_buckoff_vels -- thrown off the turnbuckle. X and Z
 * are pushed toward the middle of the ring and he pops 5.0 upward. Both
 * tests are `jrle`, so a wrestler exactly on centre takes the positive
 * branch.
 */
#define WM_BUCKOFF_XVEL 0x20000
#define WM_BUCKOFF_ZVEL 0x40000
#define WM_BUCKOFF_YVEL 0x50000

static void set_buckoff_vels(wm_arcade_actor_t *actor, const wm_anim_env *env,
                             int32_t param) {
    (void)env;
    (void)param;
    if (!actor) return;
    actor->x_vel = (actor->x_int > WM_RING_X_CENTER) ? -WM_BUCKOFF_XVEL
                                                     : WM_BUCKOFF_XVEL;
    actor->z_vel = (actor->z_int > WM_RING_Z_CENTER) ? -WM_BUCKOFF_ZVEL
                                                     : WM_BUCKOFF_ZVEL;
    actor->y_vel = WM_BUCKOFF_YVEL;
}

/*
 * DNKSEQ2.ASM:938 skick_delay. Stamp LAST_SKICK with PCNT, and if the
 * previous super kick was less than two seconds ago set MODE_STATUS --
 * the source's own comment: "This blocked fling attempt is too close (in
 * terms of time) to most recent grab".
 *
 * The royal-rumble early-out (`move @royal_rumble,a0 / jrnz #ok`) skips
 * the check entirely in that mode. This port has no royal rumble, so the
 * flag is 0 and the check always applies -- which is the shipped
 * behaviour of every match this port can actually run.
 *
 * Note the stamp is written BEFORE the comparison, so it records this
 * attempt whether or not the attempt is allowed.
 */
#define WM_SKICK_WINDOW (2 * 60)

static void skick_delay(wm_arcade_actor_t *actor, const wm_anim_env *env,
                        int32_t param) {
    uint32_t previous, now;
    (void)param;
    if (!actor) return;
    now = env ? env->pcnt : 0u;
    previous = actor->last_skick;
    actor->last_skick = now;                  /* stamped either way */
    if ((uint32_t)(now - previous) >= (uint32_t)WM_SKICK_WINDOW) return;
    actor->anim_mode |= (uint16_t)WM_MODE_STATUS;
}

/*
 * WRESTLE2.ASM:1612 tgt_ground, whose whole body is one clear -- and
 * whose comment says when to use it: "Zero yer TGT_YOFF. Do this anytime
 * you target an opponent who's on the ground."
 */
static void tgt_ground(wm_arcade_actor_t *actor, const wm_anim_env *env,
                       int32_t param) {
    (void)env;
    (void)param;
    if (actor) actor->tgt_yoff = 0;
}

/*
 * SHNSEQ2.ASM:2566 tgt_tbukl -- aim a climb at the near turnbuckle. The
 * side is picked by which half of the ring he is in, the X and Z come
 * from that side's rope line (RING.ASM's own vln_*_rope, not
 * WRESTLE.ASM's vln_*_rope_r), Z is pulled 16 in, and Y is MAT_Y+80.
 */
#define WM_TBUKL_Z_INSET 16
#define WM_TBUKL_Y (WM_MAT_Y + 80)

static void tgt_tbukl(wm_arcade_actor_t *actor, const wm_anim_env *env,
                      int32_t param) {
    (void)env;
    (void)param;
    if (!actor) return;
    /* `cmpi RING_X_CENTER,a14 / jrgt #right` -- exactly on centre climbs
       the left one. */
    actor->tgt_xoff = (actor->x_int > WM_RING_X_CENTER)
                          ? WM_ROPE_LINE_RIGHT_X : WM_ROPE_LINE_LEFT_X;
    actor->tgt_zoff = WM_ROPE_LINE_TOP_Z - WM_TBUKL_Z_INSET;
    actor->tgt_yoff = WM_TBUKL_Y;
}

/* ================================================================== *
 * WRSNDX: the per-wrestler voices.
 *
 * `impact_sound` and `DO_GRUNT` are two lines of assembly each -- all the
 * behaviour is in DCSSOUND.ASM's tables (wm/wrestler_sound_tables.h). But
 * both are defined MORE THAN ONCE, with different bodies, and the
 * difference is exactly what SUBR vs SUBRP decides: SUBR emits a `.def`
 * and is global, SUBRP does not and is file-local (MACROS.H:246-255).
 *
 *   impact_sound   YOKSEQ3.ASM  SUBR   -- global; does an EXTRA
 *                                         `WRSNDX HDBUTT_L1,HDBUTT_L2` on
 *                                         the wrestler himself first
 *                  HRTSEQ4.ASM  SUBRP  -- local; the rug slam only
 *                  RZRSEQ3.ASM  SUBRP  -- local; the rug slam only
 *
 *   DO_GRUNT       SHNSEQ2.ASM  SUBR   -- global; WRSNDX on a13
 *                  LEXSEQ3.ASM  bare label, so also file-local -- and it
 *                                         uses WRSND with a FIXED W_LUGER
 *                                         rather than reading WRESTLERNUM
 *
 * So eleven of Bret's own animations call the Undertaker-file version of
 * impact_sound, with the headbutt sounds, and one calls Bret's own
 * without them. Resolving either by bare name would get one of the two
 * wrong for everybody.
 * ================================================================== */

/* The rug-slam half both impact_sound bodies share: it plays on the man
   being slammed (ATTACH_PROC), not on the one doing the slamming. */
static void impact_rugslam(wm_arcade_actor_t *actor, const wm_anim_env *env) {
    const wm_arcade_actor_t *victim = actor ? actor->attach_proc : NULL;
    if (!victim) return;                          /* `jrz #x` */
    (void)wm_wrsndx((int)victim->wrestler_num, WM_WRSND_RUGSLAM_YELL,
                    WM_WRSND_RUGSLAM_IMPACT, env ? env->rng : NULL,
                    env ? env->sound_user : NULL, env ? env->sound : NULL);
}

/* HRTSEQ4/RZRSEQ3's local copies: the rug slam and nothing else. */
static void impact_sound_local(wm_arcade_actor_t *actor,
                               const wm_anim_env *env, int32_t param) {
    (void)param;
    impact_rugslam(actor, env);
}

/* YOKSEQ3's global one, which everybody else reaches. */
static void impact_sound_global(wm_arcade_actor_t *actor,
                                const wm_anim_env *env, int32_t param) {
    (void)param;
    if (actor)
        (void)wm_wrsndx((int)actor->wrestler_num, WM_WRSND_HDBUTT_L1,
                        WM_WRSND_HDBUTT_L2, env ? env->rng : NULL,
                        env ? env->sound_user : NULL, env ? env->sound : NULL);
    impact_rugslam(actor, env);
}

/* SHNSEQ2's `WRSNDX GRABFLING_T1,GRABFLING_T2` on a13. */
static void do_grunt(wm_arcade_actor_t *actor, const wm_anim_env *env,
                     int32_t param) {
    (void)param;
    if (!actor) return;
    (void)wm_wrsndx((int)actor->wrestler_num, WM_WRSND_GRABFLING_T1,
                    WM_WRSND_GRABFLING_T2, env ? env->rng : NULL,
                    env ? env->sound_user : NULL, env ? env->sound : NULL);
}

/*
 * LEXSEQ3's own copy, which is WRSND rather than WRSNDX: the wrestler is
 * assembled in as W_LUGER instead of read from WRESTLERNUM. Only Luger's
 * animations reach it, so it lands on the same row either way -- but it
 * is a different instruction and is translated as one.
 */
#define WM_WRSND_W_LUGER 8

static void do_grunt_luger(wm_arcade_actor_t *actor, const wm_anim_env *env,
                           int32_t param) {
    (void)param;
    (void)actor;
    (void)wm_wrsndx(WM_WRSND_W_LUGER, WM_WRSND_GRABFLING_T1,
                    WM_WRSND_GRABFLING_T2, env ? env->rng : NULL,
                    env ? env->sound_user : NULL, env ? env->sound : NULL);
}

/* The CALL_x routines themselves: schedule the process and return. */
static bool announce_call(const wm_arcade_actor_t *actor,
                          const wm_anim_env *env,
                          const wm_announce_call *c) {
    const wm_announce_table *t = wm_announce_table_find(c->table);
    size_t i;

    if (!env || !env->announcer || !t) return true;   /* named, but silent */
    for (i = 0; i < WM_ANN_PENDING_SLOTS; ++i)
        if (!ann_pending[i].table) break;
    if (i == WM_ANN_PENDING_SLOTS) return true;       /* no process left */

    ann_pending[i].table = t;
    ann_pending[i].announcer = env->announcer;
    ann_pending[i].rng = env->rng;
    ann_pending[i].near_death = env->anyone_near_death;
    ann_pending[i].user = env->announcer_user;
    ann_pending[i].crowd_user = env->crowd_user;
    ann_pending[i].crowd_cheer = env->crowd_cheer;
    ann_pending[i].crowd_sound = env->crowd_sound;
    ann_pending[i].crowd_busy = env->crowd_busy;
    ann_pending[i].percent = c->percent;
    ann_pending[i].wrestler =
        (c->personal && actor) ? (int)actor->wrestler_num : -1;
    ann_pending[i].delay = c->sleep;
    /* A SLEEP of 0 (DO_REVERSAL does the work inline) fires this tick. */
    if (ann_pending[i].delay == 0u) {
        announce_fire(i);
        ann_pending[i].table = NULL;
    }
    return true;
}

void wm_anim_code_tick(void) {
    size_t i;
    if (push_speech_lockout) --push_speech_lockout;
    for (i = 0; i < WM_ANN_PENDING_SLOTS; ++i) {
        if (!ann_pending[i].table) continue;
        if (--ann_pending[i].delay) continue;
        announce_fire(i);
        ann_pending[i].table = NULL;
    }
}

void wm_anim_code_reset(void) {
    endless_sound = 0u;
    push_speech_lockout = 0u;
    memset(ann_pending, 0, sizeof(ann_pending));
}

uint16_t wm_anim_code_endless_sound(void) { return endless_sound; }

/*
 * DCSSOUND.ASM:4295 DO_BLOCKED -- a 5% chance (RNDPER's argument is per
 * mille) of the blocker saying something, from a per-wrestler table whose
 * spare slot is a real zero.
 */
static const uint16_t WHICH_BLOCK_SPEECH[9] = {
    0x236u, 0x280u, 0x23Du, 0x23Eu, 0x284u, 0x06Au, 0x212u, 0u, 0x287u
};

static void do_blocked(wm_arcade_actor_t *actor, const wm_anim_env *env,
int32_t param) {
    (void)param;
    if (!rndper(env, 50u)) return;
    play(env, by_wrestler(actor, WHICH_BLOCK_SPEECH, 9u));
}

/*
 * DCSSOUND.ASM:4319 MAKE_HIM_SCREAM / :4324 DO_SCREAM. Four screams per
 * wrestler, one picked at random. The two entry points differ only in
 * whose voice it is: MAKE_HIM_SCREAM screams as the wrestler he just hit
 * (WHOIHIT), DO_SCREAM as himself.
 *
 * The table's own comments mark which rows are borrowed -- Undertaker,
 * Shawn and Bam Bam all use Bret's screams, Lex uses Razor's -- and the
 * spare slot is four real zeros.
 */
static const uint16_t WHICH_SCREAM[9][4] = {
    { 0x265u, 0x266u, 0x262u, 0x263u },   /* Bret */
    { 0x268u, 0x269u, 0x26Fu, 0x26Cu },   /* Razor */
    { 0x265u, 0x266u, 0x262u, 0x263u },   /* Undertaker -- Bret's */
    { 0x268u, 0x269u, 0x26Fu, 0x26Cu },   /* Yokozuna -- Razor's */
    { 0x265u, 0x266u, 0x262u, 0x263u },   /* Shawn -- Bret's */
    { 0x265u, 0x266u, 0x262u, 0x263u },   /* Bam Bam -- Bret's */
    { 0x071u, 0x072u, 0x20Au, 0x20Cu },   /* Doink */
    { 0u,     0u,     0u,     0u     },   /* spare slot */
    { 0x268u, 0x269u, 0x26Fu, 0x26Cu }    /* Lex -- Razor's */
};

static void scream_as(const wm_arcade_actor_t *who, const wm_anim_env *env) {
    size_t i = who ? (size_t)who->wrestler_num : 0u;
    if (i >= 9u) return;
    play(env, WHICH_SCREAM[i][rnd0(env, 3u)]);
}

static void make_him_scream(wm_arcade_actor_t *actor, const wm_anim_env *env,
int32_t param) {
    (void)param;
    scream_as(actor ? actor->who_i_hit : NULL, env);
}

static void do_scream(wm_arcade_actor_t *actor, const wm_anim_env *env,
int32_t param) {
    (void)param;
    scream_as(actor, env);
}

/* DCSSOUND.ASM:4350 GOUGE_SOUND -- one fixed call, nothing else. */
static void gouge_sound(wm_arcade_actor_t *actor, const wm_anim_env *env,
int32_t param) {
    (void)param;
    (void)actor;
    play(env, 0x0A9u);
}

/*
 * DCSSOUND.ASM:4280 DO_RAZOR_RUG_SPEECH -- Razor's four lines as the rug
 * shake goes on, stepped by RPT_COUNT and silent once it has run past
 * them. RPT_COUNT 0 would index before the table in the ROM, so that case
 * plays nothing here rather than inventing what sat there.
 */
static const uint16_t RAZOR_RUG_TABLE[4] = { 0x27Du, 0x27Cu, 0x27Bu, 0x27Au };

static void do_razor_rug_speech(wm_arcade_actor_t *actor,
                                const wm_anim_env *env, int32_t param) {
    int32_t i;
    (void)param;
    i = (actor ? actor->rpt_count : 0) - 1;
    if (i < 0 || i >= 4) return;
    play(env, RAZOR_RUG_TABLE[i]);
}

/*
 * DCSSOUND.ASM:4377 CALL_BONE_BREAK -- one of three crunches. The source
 * then tests triple_sound's own carry (did the call actually get a
 * channel?) and, only if it did, spawns a process that sleeps 50 ticks and
 * has the announcer say "did you hear that". That follow-up needs both the
 * channel arbitration this port does not model and the speech queue, so
 * what is translated here is the crunch itself.
 */
static const uint16_t BONE_BREAK_SOUNDS[3] = { 0x01Du, 0x09Bu, 0x098u };

static void call_bone_break(wm_arcade_actor_t *actor, const wm_anim_env *env,
int32_t param) {
    (void)param;
    (void)actor;
    play(env, BONE_BREAK_SOUNDS[rnd0(env, 2u)]);
}

/* ================================================================== *
 * The self-contained actor-state routines.
 *
 * These live in whichever wrestler's sequence file happened to define them
 * first -- ckzpos in DNKSEQ2, no_bk_xvel and tbukl_flip in SHNSEQ2/3, the
 * palette pair in DNKSEQ3 -- but they are plain global labels, so every
 * wrestler's animations call them. Each reads and writes only the actor it
 * is given, which is why they translate one-for-one.
 * ================================================================== */

/*
 * DNKSEQ2.ASM:1886 ckzpos, with the source's own comment: "If falling near
 * the front or rear ropes, slide toward middle of the ring to allow
 * opponent to walk around him." Above 510h he slides up the screen, below
 * 442h he slides down, and in between he is already clear.
 */
static void ckzpos(wm_arcade_actor_t *actor, const wm_anim_env *env,
int32_t param) {
    (void)param;
    (void)env;
    if (!actor) return;
    if (actor->z_int > 0x510) { actor->z_vel = -0x24000; return; }
    if (actor->z_int > 0x442) return;
    actor->z_vel = 0x24000;
}

/*
 * SHNSEQ3.ASM:3260 no_bk_xvel: kill any x velocity that is carrying him
 * BACKWARD. The source negates the velocity when FACING_DIR's right bit is
 * clear -- turning it into a forward-relative figure -- and zeroes it if
 * that comes out negative.
 */
static void no_bk_xvel(wm_arcade_actor_t *actor, const wm_anim_env *env,
int32_t param) {
    (void)param;
    int32_t v;
    (void)env;
    if (!actor) return;
    v = actor->x_vel;
    if (!(actor->facing_dir & WM_MOVE_RIGHT)) v = -v;
    if (v < 0) actor->x_vel = 0;
}

/*
 * HRTSEQ4.ASM:1081 choose_2or4: report which facing bank the animation
 * should continue in, through MODE_STATUS -- clear for the 2-bank when
 * NEW_FACING_DIR points up, set for the 4-bank otherwise. The animation
 * then forks on it with an ordinary ANI_IFSTATUS.
 */
static void choose_2or4(wm_arcade_actor_t *actor, const wm_anim_env *env,
int32_t param) {
    (void)param;
    (void)env;
    if (!actor) return;
    if (actor->new_facing_dir & WM_MOVE_UP)
        actor->anim_mode &= (uint16_t)~WM_MODE_STATUS;
    else
        actor->anim_mode |= (uint16_t)WM_MODE_STATUS;
}

/*
 * DNKSEQ3.ASM:428 am_I_dead: report through MODE_STATUS whether this
 * wrestler is finished. On zero health it also puts him in MODE_DEAD
 * itself. The live path is subtler than "clear the bit": it clears
 * MODE_STATUS but sets it straight back if he is ALREADY in MODE_DEAD, so
 * a wrestler who died earlier keeps answering yes even once the lifebar
 * has been reset.
 */
static void am_i_dead(wm_arcade_actor_t *actor, const wm_anim_env *env,
int32_t param) {
    (void)param;
    (void)env;
    if (!actor) return;
    if (actor->life == 0) {
        actor->anim_mode |= (uint16_t)WM_MODE_STATUS;
        actor->player_mode = WM_PMODE_DEAD;
        return;
    }
    actor->anim_mode &= (uint16_t)~WM_MODE_STATUS;
    if (actor->player_mode == WM_PMODE_DEAD)
        actor->anim_mode |= (uint16_t)WM_MODE_STATUS;
}

/*
 * DNKSEQ3.ASM's palette and constant-colour routines -- Doink's buzzer
 * flash. make_white and make_black differ only in the OBJ_CONST value they
 * load; both turn on DISPLAY.EQU:104's M_CONNON, "replace non-zero data
 * with constant". make_norm puts the ordinary SYS.EQU DMAWNZ write-mode
 * back. All three clear the low four control bits first.
 */
#define WM_DMA_MODE_MASK  0x000Fu
#define WM_M_CONNON       0x0008u   /* DISPLAY.EQU:104 */
#define WM_DMAWNZ         0x8002u   /* SYS.EQU:215 */
#define WM_M_TEMP_PAL     0x0004u   /* PLYR.EQU:399/422, 1<<B_TEMP_PAL */

static void set_dma_mode(wm_arcade_actor_t *actor, uint16_t mode) {
    actor->obj_control =
        (uint16_t)((actor->obj_control & (uint16_t)~WM_DMA_MODE_MASK) | mode);
}

static void make_white(wm_arcade_actor_t *actor, const wm_anim_env *env,
int32_t param) {
    (void)param;
    (void)env;
    if (!actor) return;
    actor->obj_const = 0x0101u;
    set_dma_mode(actor, WM_M_CONNON);
}

/*
 * #make_black is written once per sequence file, and the source says why
 * at every copy: "This is a black color within the wrestler's pal. It is
 * different for each wrestler." Seven distinct values across the eight
 * files -- Bam Bam and Doink happen to share 0B0Bh -- so the value comes
 * from the registry row for the file the call was made from, and getting
 * that wrong paints six wrestlers in Doink's black.
 */
static void make_black(wm_arcade_actor_t *actor, const wm_anim_env *env,
                       int32_t param) {
    (void)env;
    if (!actor) return;
    actor->obj_const = (uint16_t)param;
    set_dma_mode(actor, WM_M_CONNON);
}

static void make_norm(wm_arcade_actor_t *actor, const wm_anim_env *env,
int32_t param) {
    (void)param;
    (void)env;
    if (!actor) return;
    /* `andni 01111b / ori DMAWNZ` -- DMAWNZ is 8002h, so this ORs a whole
       write-mode word back in, not just a low bit. */
    set_dma_mode(actor, WM_DMAWNZ);
}

static void set_skeleton_pal(wm_arcade_actor_t *actor, const wm_anim_env *env,
int32_t param) {
    (void)param;
    (void)env;
    if (!actor) return;
    actor->obj_pal = actor->skeleton_pal;
    actor->status_flags |= WM_M_TEMP_PAL;
}

static void set_my_pal(wm_arcade_actor_t *actor, const wm_anim_env *env,
int32_t param) {
    (void)param;
    (void)env;
    if (!actor) return;
    actor->obj_pal = actor->my_pal;
    actor->status_flags &= ~(uint32_t)WM_M_TEMP_PAL;
}

/*
 * SHNSEQ2.ASM:1556 tbukl_flip and its sibling entry point face_inside.
 *
 * On a turnbuckle, which way he faces depends on which corner he is in and
 * whether the opponent is in the ring at all. tbukl_flip reads the
 * opponent's INRING (0 in, 1 out); face_inside is the same code entered
 * with that answer forced to "in", i.e. always turn to face the ring.
 *
 * When the opponent IS outside, neither corner decides it -- the source
 * falls through to #out and goes by NEW_FACING_DIR's left bit instead.
 *
 * The last twist is the source's own: "doink is the opposite... so is
 * yoko." Both of those two have their artwork drawn facing the other way,
 * so the final flip is inverted for them.
 */
static void turnbuckle_face(wm_arcade_actor_t *actor, bool opponent_outside) {
    /* The source's #yes (mirror) against #no (don't). Both corners send an
       outside opponent to the same #out test, so which corner he is in
       only decides it while the opponent is still in the ring -- and there
       the right corner mirrors and the left does not. */
    bool mirror = opponent_outside
        ? (actor->new_facing_dir & WM_MOVE_LEFT) != 0
        : (actor->x_int >= WM_RING_X_CENTER);

    /* "doink is the opposite... so is yoko" -- the source's own comment.
       Their artwork is drawn facing the other way. */
    if (actor->wrestler_num == WM_ROSTER_DOINK ||
        actor->wrestler_num == WM_ROSTER_YOKO)
        mirror = !mirror;

    if (mirror) actor->obj_control |= (uint16_t)WM_OBJ_FLIPH;
    else        actor->obj_control &= (uint16_t)~WM_OBJ_FLIPH;
}

static void tbukl_flip(wm_arcade_actor_t *actor, const wm_anim_env *env,
int32_t param) {
    (void)param;
    bool outside = false;
    if (!actor) return;
    /* `calla get_opp_process / move *a0(INRING),a0`. PLYR.EQU's INRING is
       0 for "in the ring"; this port's in_ring is the ordinary boolean, so
       the test flips. With no opponent reachable the source would read a
       null process; treating that as in the ring keeps him facing inward
       rather than guessing. */
    if (env && env->opponent) outside = (env->opponent->in_ring == 0);
    turnbuckle_face(actor, outside);
}

static void face_inside(wm_arcade_actor_t *actor, const wm_anim_env *env,
int32_t param) {
    (void)param;
    (void)env;
    if (!actor) return;
    turnbuckle_face(actor, false);
}

/*
 * WRESTLE2.ASM:4967 free_toss_check -- report through MODE_STATUS whether
 * a free hiptoss is on. Two ways to earn it: the two wrestlers are within
 * 15 units of each other in z, or he is holding block. The block test is an
 * equality against PLAYER_BLOCK_VAL, not a bit test, so block AND anything
 * else does not count.
 *
 * The source's own commented-out lines show an earlier version that
 * required the stick pulled away instead; it was replaced by the block
 * test, and the dead lines are left in place there.
 */
static void free_toss_check(wm_arcade_actor_t *actor, const wm_anim_env *env,
int32_t param) {
    (void)param;
    int32_t dz;
    if (!actor) return;
    actor->anim_mode |= (uint16_t)WM_MODE_STATUS;
    if (env && env->opponent) {
        dz = env->opponent->z_fixed - actor->z_fixed;
        if (dz < 0) dz = -dz;
        if ((dz >> 16) < 15) return;
    }
    if (actor->but_val_cur == (uint16_t)WM_BTN_BLOCK) return;
    actor->anim_mode &= (uint16_t)~WM_MODE_STATUS;
}

/*
 * WRESTLE2.ASM:5004 setup_freetoss, with the source's own summary: "We're
 * gonna do a free hiptoss. Do all the neccesary setup here. Set our
 * PLYRMODE to normal, IMMOBILIZE the bad guy, clear velocities, etc."
 *
 * The SMRTTGT smart-target call at the end is a display service (it points
 * the camera's target at the victim) and is not modelled here.
 */
static void setup_freetoss(wm_arcade_actor_t *actor, const wm_anim_env *env,
int32_t param) {
    (void)param;
    (void)env;
    if (!actor) return;
    actor->player_mode = WM_PMODE_NORMAL;
    if (actor->who_i_hit) actor->who_i_hit->immobilize_time = 20;
}

/*
 * DNKSEQ2.ASM:5486 SET_DIR_FACE -- point NEW_FACING_DIR at the ring while
 * climbing in or out. The source's own note: "this is now used for both
 * climbins and climbouts. If we're outside, use an identical version, but
 * with the a0's switched." So the corner test is the same and only the two
 * answers trade places. 10 is DOWN|RIGHT, 6 is DOWN|LEFT.
 */
static void set_dir_face(wm_arcade_actor_t *actor, const wm_anim_env *env,
                         int32_t param) {
    bool left_of_centre;
    (void)env; (void)param;
    if (!actor) return;
    left_of_centre = actor->x_int < WM_RING_X_CENTER;
    /* `move *a13(INRING),a14 / jrz #method2` -- the source branches to its
       second version when INRING is 0, which is its own encoding for IN
       the ring. This port's in_ring is the ordinary boolean, so the test
       flips: in the ring takes #method2. */
    if (actor->in_ring != 0)
        actor->new_facing_dir = left_of_centre ? 6 : 10;    /* #method2 */
    else
        actor->new_facing_dir = left_of_centre ? 10 : 6;
}

/*
 * WRESTLE2.ASM:4951 set_tbukl_airmode -- leaping off a turnbuckle puts him
 * in MODE_INAIR2, the mode that says "this one is a turnbuckle leap", which
 * is what an opponent's own do_kick tests to answer it. Against a dead
 * opponent there is nothing to answer, so it is the plain MODE_INAIR.
 */
static void set_tbukl_airmode(wm_arcade_actor_t *actor, const wm_anim_env *env,
                              int32_t param) {
    (void)param;
    if (!actor) return;
    actor->player_mode =
        (env && env->opponent && env->opponent->player_mode == WM_PMODE_DEAD)
            ? WM_PMODE_INAIR : WM_PMODE_INAIR2;
}

/*
 * WRESTLE2.ASM:4527 check_raisearm_bit -- report through MODE_STATUS
 * whether he has NOT already done his raise-arm celebration. The sense is
 * inverted from what the name suggests: the bit being SET clears
 * MODE_STATUS, so the animation forks into the celebration only the first
 * time.
 */
#define WM_M_DID_RAISEARM (1u << 16)   /* PLYR.EQU:414 B_DID_RAISEARM */

static void check_raisearm_bit(wm_arcade_actor_t *actor,
                               const wm_anim_env *env, int32_t param) {
    (void)env; (void)param;
    if (!actor) return;
    if (actor->status_flags & WM_M_DID_RAISEARM)
        actor->anim_mode &= (uint16_t)~WM_MODE_STATUS;
    else
        actor->anim_mode |= (uint16_t)WM_MODE_STATUS;
}

/*
 * DNKSEQ3.ASM:1516 clear_opp_counts, with the source's own comment: "Zero
 * opponents buttons for later counting." It clears all five of the wrestler
 * he is HOLDING, which is what makes the mash gates in a grapple measure
 * struggling from the moment the hold starts rather than from the round.
 */
static void clear_opp_counts(wm_arcade_actor_t *actor, const wm_anim_env *env,
                             int32_t param) {
    (void)env; (void)param;
    if (!actor || !actor->attach_proc) return;
    wm_arcade_clear_button_presses(actor->attach_proc);
}

/*
 * DNKSEQ3.ASM:1509 head_grab_time -- stamp when this head hold started,
 * then fall straight through into clear_opp_counts. (The CALL_SETUP
 * announcer line between them belongs to the speech queue and is not
 * translated.) The stamp is what the head-hold monitor reads to decide
 * whether a repeat grab within 120 ticks becomes a fake hold instead.
 */
static void head_grab_time(wm_arcade_actor_t *actor, const wm_anim_env *env,
                           int32_t param) {
    if (!actor) return;
    actor->last_headhold = (env ? env->pcnt : 0u);
    clear_opp_counts(actor, env, param);
}

/*
 * WRESTLE2.ASM:1622 halve_bk_xvel -- the gentler twin of no_bk_xvel: where
 * that one zeroes a velocity carrying him backward, this one halves it.
 */
static void halve_bk_xvel(wm_arcade_actor_t *actor, const wm_anim_env *env,
                          int32_t param) {
    int32_t v;
    (void)env; (void)param;
    if (!actor) return;
    v = actor->x_vel;
    if (!(actor->facing_dir & WM_MOVE_RIGHT)) v = -v;
    if (v < 0) actor->x_vel >>= 1;      /* the source's own `sra 1` */
}


/*
 * ANI_CODE:  #set_zvel2 -- one constant Z velocity, written once per
 * sequence file with a DIFFERENT value. Six wrestlers get -5.0, Doink
 * -6.75 and the Undertaker -5.75, which is exactly why the registry is
 * keyed on (name, file) and the value rides in `param`.
 */
static void set_zvel2(wm_arcade_actor_t *actor, const wm_anim_env *env,
                      int32_t param) {
    (void)env;
    if (actor) actor->z_vel = param;
}

/* HRTSEQ3.ASM #half_vels: halve the X velocity (the source's own `sra 1`)
   and set a fixed 2.0 upward. */
static void half_vels(wm_arcade_actor_t *actor, const wm_anim_env *env,
                      int32_t param) {
    (void)env; (void)param;
    if (!actor) return;
    actor->x_vel >>= 1;
    actor->y_vel = 0x20000;
}

/*
 * SHNSEQ3.ASM #reverse_xvel: turn him round at a fraction of the speed --
 * `neg a14 / sra N,a14`, and N is the row's own parameter because the file
 * defines the routine TWICE, a quarter at 1279 and a half at 3651.
 */
static void reverse_xvel(wm_arcade_actor_t *actor, const wm_anim_env *env,
                         int32_t param) {
    (void)env;
    if (actor) actor->x_vel = (-actor->x_vel) >> param;
}

/* DNKSEQ2.ASM #zero_x -- the source's own comment: "Don't float if
   dropping straight down". Only kills the drift when the opponent is
   underneath rather than off to the side. */
static void zero_x(wm_arcade_actor_t *actor, const wm_anim_env *env,
                   int32_t param) {
    (void)env; (void)param;
    if (actor && actor->closest_xdist <= 0x40) actor->x_vel = 0;
}

/*
 * SHNSEQ3.ASM / YOKSEQ3.ASM #store_opp_xvel and #merge_xvels, a pair
 * sharing the file's own `#opp_xvel` word: remember what the opponent was
 * doing, then average it into your own -- (mine + his) >> 2, which is a
 * quarter rather than a half, as written.
 */
static int32_t stored_opp_xvel;

static void store_opp_xvel(wm_arcade_actor_t *actor, const wm_anim_env *env,
                           int32_t param) {
    (void)param;
    stored_opp_xvel = (env && env->opponent) ? env->opponent->x_vel : 0;
    (void)actor;
}

static void merge_xvels(wm_arcade_actor_t *actor, const wm_anim_env *env,
                        int32_t param) {
    (void)env; (void)param;
    if (actor) actor->x_vel = (stored_opp_xvel + actor->x_vel) >> 2;
}

/*
 * The "throw the man you just hit" routines. All of them read WHOIHIT and
 * push him AWAY from the way he is facing: `movi -[n,0]` then negate when
 * NEW_FACING_DIR is left, so facing right sends him left.
 *
 * `param` packs the three velocities the file's own copy uses, because
 * each file writes different ones: y in the low byte, z in the next, x in
 * the next, all in whole units.
 */
static void throw_opp(wm_arcade_actor_t *actor, const wm_anim_env *env,
                      int32_t param) {
    wm_arcade_actor_t *v;
    int32_t x;
    (void)env;
    if (!actor || !actor->who_i_hit) return;
    v = actor->who_i_hit;
    v->y_vel = ((param >> 0) & 0xff) << 16;
    if ((param >> 8) & 0xff) v->z_vel = (int32_t)((param >> 8) & 0xff) << 16;
    x = (int32_t)((param >> 16) & 0xff) << 16;
    v->x_vel = (v->new_facing_dir & WM_MOVE_RIGHT) ? -x : x;
}

/* DNKSEQ3.ASM's own #set_opp_y is just the lift, with no push at all. */
static void lift_opp(wm_arcade_actor_t *actor, const wm_anim_env *env,
                     int32_t param) {
    (void)env;
    if (actor && actor->who_i_hit)
        actor->who_i_hit->y_vel = param;
}


/*
 * #set_zvel1 and #ckspin, written separately in every sequence file with
 * the same body: MODE_STATUS says which way up he is. Bit 0 of FACING_DIR
 * is MOVE_UP, and the status is set when it is CLEAR -- facing down.
 * Whatever reads it afterwards branches on that.
 */
static void status_from_facing(wm_arcade_actor_t *actor,
                               const wm_anim_env *env, int32_t param) {
    (void)env; (void)param;
    if (!actor) return;
    if (actor->facing_dir & WM_MOVE_UP)
        actor->anim_mode &= (uint16_t)~WM_MODE_STATUS;
    else
        actor->anim_mode |= (uint16_t)WM_MODE_STATUS;
}

/*
 * DNKSEQ2.ASM/LEXSEQ2/RZRSEQ2/UNDSEQ2 #holdup: how long a leap may be
 * held up. BUT_COUNT counts the ticks; past the source's own limit of 25
 * ("Max time to hold up in air (*2 ticks)"), or the moment super kick is
 * released, MODE_STATUS clears and the animation moves on.
 */
static void holdup(wm_arcade_actor_t *actor, const wm_anim_env *env,
                   int32_t param) {
    int holding;
    (void)env; (void)param;
    if (!actor) return;
    ++actor->but_count;
    holding = actor->but_count <= 25 &&
              (actor->but_val_cur & (uint16_t)WM_BTN_SKICK);
    if (holding) actor->anim_mode |= (uint16_t)WM_MODE_STATUS;
    else actor->anim_mode &= (uint16_t)~WM_MODE_STATUS;
}

/* HRTSEQ2.ASM NOT_IN_RING -- a global, and one of the places PLYR.EQU's
   INRING polarity bites: the source writes 1 for OUTSIDE, this port's
   field is the ordinary boolean. */
static void not_in_ring(wm_arcade_actor_t *actor, const wm_anim_env *env,
                        int32_t param) {
    (void)env; (void)param;
    if (actor) actor->in_ring = 0;
}

/* DNKSEQ3/YOKSEQ2 #set_zvel: give the man he hit a little Z drift, but
   only if he has none of his own. */
static void set_zvel_if_still(wm_arcade_actor_t *actor,
                              const wm_anim_env *env, int32_t param) {
    (void)env;
    if (actor && actor->who_i_hit && actor->who_i_hit->z_vel == 0)
        actor->who_i_hit->z_vel = param;
}


/*
 * hiptoss_delay and fling_delay -- the same routine over two different
 * PCNT stamps. Each records when it last ran and sets MODE_STATUS if the
 * gap is under three seconds, which the source's own comment explains:
 * "This blocked fling attempt is too close (in terms of time) to most
 * recent grab". Whatever follows branches on the status to refuse.
 *
 * `param` picks the stamp: 0 = LAST_HIPTOSS, 1 = LAST_FLING.
 */
static void grab_rate_limit(wm_arcade_actor_t *actor,
                            const wm_anim_env *env, int32_t param) {
    uint32_t *stamp, now, since;
    if (!actor) return;
    stamp = param ? &actor->last_fling : &actor->last_hiptoss;
    now = env ? env->pcnt : 0u;
    since = now - *stamp;
    *stamp = now;
    if ((int32_t)since >= 3 * 60)
        actor->anim_mode &= (uint16_t)~WM_MODE_STATUS;
    else
        actor->anim_mode |= (uint16_t)WM_MODE_STATUS;
}


/* #set_opp_xflip: mirror the held wrestler's sprite. The source does not
   null-check ATTACH_PROC before reading through it -- benign on the
   original hardware, not here, so this guards. */
static void set_opp_xflip(wm_arcade_actor_t *actor, const wm_anim_env *env,
                          int32_t param) {
    (void)env; (void)param;
    if (actor && actor->attach_proc)
        actor->attach_proc->obj_control =
            (uint16_t)(actor->attach_proc->obj_control ^ WM_OBJ_FLIPH);
}

/* fix_bnc_flip: "Check to see if I'm against ropes" -- the mirror follows
   which side of the ring he is on, mirrored when left of centre. */
static void fix_bnc_flip(wm_arcade_actor_t *actor, const wm_anim_env *env,
                         int32_t param) {
    (void)env; (void)param;
    if (!actor) return;
    if (actor->x_int < WM_RING_X_CENTER)
        actor->obj_control |= (uint16_t)WM_OBJ_FLIPH;
    else
        actor->obj_control &= (uint16_t)~WM_OBJ_FLIPH;
}

/* DNKSEQ2.ASM #ckongrnd: MODE_STATUS says whether the man he is fighting
   is already down. */
static void ckongrnd(wm_arcade_actor_t *actor, const wm_anim_env *env,
                     int32_t param) {
    (void)param;
    if (!actor) return;
    if (env && env->opponent &&
        env->opponent->player_mode == WM_PMODE_ONGROUND)
        actor->anim_mode |= (uint16_t)WM_MODE_STATUS;
    else
        actor->anim_mode &= (uint16_t)~WM_MODE_STATUS;
}

/*
 * #inc_loop: count a held sequence up and clear MODE_STATUS while it is
 * still under the cap, setting it at `#breakout`. The cap is written per
 * file and Doink's is 2 where everyone else's is 3, so it rides in
 * `param`.
 */
static void inc_loop(wm_arcade_actor_t *actor, const wm_anim_env *env,
                     int32_t param) {
    (void)env;
    if (!actor) return;
    ++actor->usr_var1;
    if (actor->usr_var1 > param)
        actor->anim_mode |= (uint16_t)WM_MODE_STATUS;
    else
        actor->anim_mode &= (uint16_t)~WM_MODE_STATUS;
}

/*
 * set_position -- and the name is a lie worth recording. EVERY position
 * write in it is commented out in the source; what is left live is the
 * palette pair, so it moves nobody. Only the MY_PAL half is translated
 * here: SKELETON_PAL comes from `pal_getf` on a per-file palette symbol
 * (DNKBLU_P and friends), and this port has no palette system to resolve
 * one.
 */
static void set_position(wm_arcade_actor_t *actor, const wm_anim_env *env,
                         int32_t param) {
    (void)env; (void)param;
    if (actor) actor->my_pal = actor->obj_pal;
}


/*
 * #zero_butn -- the source's own comment: "Force player to start holding
 * his button down starting at the end of the current buzz sequence."
 * It zeroes one of WRESTLE.ASM's per-player button-hold timers, and WHICH
 * one differs by file: Bam Bam's copy clears powerp_dtime1, the other
 * three clear punch_dtime1. `param` picks it.
 */
static void zero_butn(wm_arcade_actor_t *actor, const wm_anim_env *env,
                      int32_t param) {
    (void)env;
    if (!actor) return;
    if (param) actor->powerp_dtime = 0;
    else actor->punch_dtime = 0;
}

/*
 * The registry. `file` NULL means a global label, which resolves the same
 * from anywhere; a non-NULL file scopes the row to that sequence file,
 * which is what a leading '#' in the source means.
 */
static const struct {
    const char *name;
    const char *file;      /* NULL = global */
    wm_anim_code_fn fn;
    int32_t param;
    /*
     * The source line of the definition this row IS, for a local label a
     * file defines more than once. 0 means "this file's only one".
     *
     * BAMSEQ2.ASM writes `#set_zvel2` twice, -5.0 in the block above
     * bam_climbthru_top_anim and +5.0 in the one above
     * bam_climbin_top_anim; every other file does the same, and three
     * files write two `#inc_loop` with different caps. A row keyed only
     * on (name, file) can be one of those or the other, never both.
     */
    int32_t line;
} code_table[] = {
    /*
     * #set_zvel2, one row per file because the constant differs:
     * BAM/HRT/LEX/RZR/SHN/YOK -5.0, DNK -6.75, UND -5.75.
     */
    /* ...and TWICE per file, with the sign reversed: the climb-through
       helper rolls him one way, the climb-in helper the other. */
    { "#set_zvel2", "BAMSEQ2.ASM", set_zvel2, -0x50000, 4287 },
    { "#set_zvel2", "BAMSEQ2.ASM", set_zvel2,  0x50000, 4371 },
    { "#set_zvel2", "HRTSEQ2.ASM", set_zvel2, -0x50000, 3113 },
    { "#set_zvel2", "HRTSEQ2.ASM", set_zvel2,  0x52000, 3191 },
    { "#set_zvel2", "LEXSEQ2.ASM", set_zvel2, -0x50000, 2916 },
    { "#set_zvel2", "LEXSEQ2.ASM", set_zvel2,  0x52000, 2994 },
    { "#set_zvel2", "RZRSEQ2.ASM", set_zvel2, -0x50000, 3075 },
    { "#set_zvel2", "RZRSEQ2.ASM", set_zvel2,  0x52000, 3150 },
    { "#set_zvel2", "SHNSEQ2.ASM", set_zvel2, -0x50000, 2328 },
    { "#set_zvel2", "SHNSEQ2.ASM", set_zvel2,  0x50000, 2409 },
    { "#set_zvel2", "YOKSEQ2.ASM", set_zvel2, -0x50000, 2103 },
    { "#set_zvel2", "YOKSEQ2.ASM", set_zvel2,  0x52000, 2185 },
    { "#set_zvel2", "DNKSEQ2.ASM", set_zvel2, -0x6c000, 5699 },
    { "#set_zvel2", "DNKSEQ2.ASM", set_zvel2,  0x42000, 5785 },
    { "#set_zvel2", "UNDSEQ2.ASM", set_zvel2, -0x5c000, 4586 },
    { "#set_zvel2", "UNDSEQ2.ASM", set_zvel2,  0x52000, 4652 },

    { "#half_vels", "HRTSEQ3.ASM", half_vels, 0, 0 },
    { "#reverse_xvel", "SHNSEQ3.ASM", reverse_xvel, 2, 1279 },
    { "#reverse_xvel", "SHNSEQ3.ASM", reverse_xvel, 1, 3651 },
    { "#zero_x", "DNKSEQ2.ASM", zero_x, 0, 0 },
    { "#store_opp_xvel", "SHNSEQ3.ASM", store_opp_xvel, 0, 0 },
    { "#store_opp_xvel", "YOKSEQ3.ASM", store_opp_xvel, 0, 0 },
    { "#merge_xvels", "SHNSEQ3.ASM", merge_xvels, 0, 0 },
    { "#merge_xvels", "YOKSEQ3.ASM", merge_xvels, 0, 0 },

    /* x/z/y in whole units, per the file's own copy. BAMSEQ3/LEXSEQ3's
       #set_opp_y is 5 up, 2 along Z and 3 away; BAMSEQ2's #set_opp_xy is
       2 up and 2 away with no Z; DNKSEQ3's #set_opp_y only lifts. */
    { "#set_opp_y", "BAMSEQ3.ASM", throw_opp, (3 << 16) | (2 << 8) | 5, 0 },
    /* LEXSEQ3.ASM writes it twice, byte-identically; both are rows so
       that neither call site falls through to nothing. */
    { "#set_opp_y", "LEXSEQ3.ASM", throw_opp, (3 << 16) | (2 << 8) | 5, 1688 },
    { "#set_opp_y", "LEXSEQ3.ASM", throw_opp, (3 << 16) | (2 << 8) | 5, 2311 },
    { "#set_opp_xy", "BAMSEQ2.ASM", throw_opp, (2 << 16) | (0 << 8) | 2, 0 },
    { "#set_opp_y", "DNKSEQ3.ASM", lift_opp, 0x40000, 0 },

    /* #set_zvel1 and #ckspin: same body, written once per file. */
    { "#set_zvel1", "BAMSEQ2.ASM", status_from_facing, 0, 0 },
    { "#ckspin", "BAMSEQ2.ASM", status_from_facing, 0, 0 },
    { "#set_zvel1", "DNKSEQ2.ASM", status_from_facing, 0, 0 },
    { "#ckspin", "DNKSEQ2.ASM", status_from_facing, 0, 0 },
    { "#set_zvel1", "HRTSEQ2.ASM", status_from_facing, 0, 0 },
    { "#ckspin", "HRTSEQ2.ASM", status_from_facing, 0, 0 },
    { "#set_zvel1", "LEXSEQ2.ASM", status_from_facing, 0, 0 },
    { "#ckspin", "LEXSEQ2.ASM", status_from_facing, 0, 0 },
    { "#set_zvel1", "RZRSEQ2.ASM", status_from_facing, 0, 0 },
    { "#ckspin", "RZRSEQ2.ASM", status_from_facing, 0, 0 },
    { "#set_zvel1", "SHNSEQ2.ASM", status_from_facing, 0, 0 },
    { "#ckspin", "SHNSEQ2.ASM", status_from_facing, 0, 0 },
    { "#set_zvel1", "UNDSEQ2.ASM", status_from_facing, 0, 0 },
    { "#ckspin", "UNDSEQ2.ASM", status_from_facing, 0, 0 },
    { "#set_zvel1", "YOKSEQ2.ASM", status_from_facing, 0, 0 },
    { "#ckspin", "YOKSEQ2.ASM", status_from_facing, 0, 0 },

    { "#set_zvel3", "DNKSEQ2.ASM", set_zvel2, -0x7c000, 0 },
    { "#set_zvel", "DNKSEQ3.ASM", set_zvel_if_still, 0x10000, 0 },
    { "#set_zvel", "YOKSEQ2.ASM", set_zvel_if_still, 0x10000, 0 },
    { "NOT_IN_RING", NULL, not_in_ring, 0, 0 },
    { "#holdup", "DNKSEQ2.ASM", holdup, 0, 0 },
    { "#holdup", "LEXSEQ2.ASM", holdup, 0, 0 },
    { "#holdup", "RZRSEQ2.ASM", holdup, 0, 0 },
    { "#holdup", "UNDSEQ2.ASM", holdup, 0, 0 },

    /* Both are SUBRs, so global: the same limiter over two stamps. */
    { "hiptoss_delay", NULL, grab_rate_limit, 0, 0 },
    { "fling_delay", NULL, grab_rate_limit, 1, 0 },
    { "#set_opp_xflip", "BAMSEQ3.ASM", set_opp_xflip, 0, 1378 },
    { "#set_opp_xflip", "BAMSEQ3.ASM", set_opp_xflip, 0, 2479 },
    { "#set_opp_xflip", "DNKSEQ3.ASM", set_opp_xflip, 0, 0 },
    { "#set_opp_xflip", "HRTSEQ3.ASM", set_opp_xflip, 0, 0 },
    { "#set_opp_xflip", "RZRSEQ3.ASM", set_opp_xflip, 0, 2428 },
    { "#set_opp_xflip", "RZRSEQ3.ASM", set_opp_xflip, 0, 2764 },
    { "fix_bnc_flip", NULL, fix_bnc_flip, 0, 0 },
    { "#ckongrnd", "DNKSEQ2.ASM", ckongrnd, 0, 0 },
    { "set_position", NULL, set_position, 0, 0 },
    /* #inc_loop: cap 3 everywhere except Doink's own copy, which is 2. */
    /* Three files write it twice, capped 3 in the first and 2 in the
       second; HRTSEQ3, LEXSEQ3 and YOKSEQ3 write it twice at 3 both
       times, and the rest once. */
    { "#inc_loop", "BAMSEQ3.ASM", inc_loop, 3, 679 },
    { "#inc_loop", "BAMSEQ3.ASM", inc_loop, 2, 1798 },
    { "#inc_loop", "SHNSEQ4.ASM", inc_loop, 3, 1140 },
    { "#inc_loop", "SHNSEQ4.ASM", inc_loop, 2, 1492 },
    { "#inc_loop", "UNDSEQ3.ASM", inc_loop, 3, 168 },
    { "#inc_loop", "UNDSEQ3.ASM", inc_loop, 2, 2888 },
    { "#inc_loop", "HRTSEQ3.ASM", inc_loop, 3, 166 },
    { "#inc_loop", "HRTSEQ3.ASM", inc_loop, 3, 773 },
    { "#inc_loop", "LEXSEQ3.ASM", inc_loop, 3, 138 },
    { "#inc_loop", "LEXSEQ3.ASM", inc_loop, 3, 403 },
    { "#inc_loop", "YOKSEQ3.ASM", inc_loop, 3, 272 },
    { "#inc_loop", "YOKSEQ3.ASM", inc_loop, 3, 628 },
    { "#inc_loop", "DNKSEQ2.ASM", inc_loop, 3, 4059 },
    { "#inc_loop", "RZRSEQ2.ASM", inc_loop, 3, 2456 },
    { "#inc_loop", "RZRSEQ3.ASM", inc_loop, 3, 894 },
    { "#inc_loop", "DNKSEQ3.ASM", inc_loop, 2, 1679 },

    { "#zero_butn", "BAMSEQ3.ASM", zero_butn, 1, 0 },
    { "#zero_butn", "DNKSEQ3.ASM", zero_butn, 0, 0 },
    { "#zero_butn", "SHNSEQ3.ASM", zero_butn, 0, 236 },
    { "#zero_butn", "SHNSEQ3.ASM", zero_butn, 0, 491 },
    { "#zero_butn", "UNDSEQ3.ASM", zero_butn, 0, 0 },
    { "ckzpos", NULL, ckzpos, 0, 0 },
    { "SET_DIR_FACE", NULL, set_dir_face, 0, 0 },
    { "set_tbukl_airmode", NULL, set_tbukl_airmode, 0, 0 },
    { "check_raisearm_bit", NULL, check_raisearm_bit, 0, 0 },
    { "clear_opp_counts", NULL, clear_opp_counts, 0, 0 },
    { "head_grab_time", NULL, head_grab_time, 0, 0 },
    { "halve_bk_xvel", NULL, halve_bk_xvel, 0, 0 },
    { "free_toss_check", NULL, free_toss_check, 0, 0 },
    { "setup_freetoss", NULL, setup_freetoss, 0, 0 },
    { "no_bk_xvel", NULL, no_bk_xvel, 0, 0 },
    { "choose_2or4", NULL, choose_2or4, 0, 0 },
    { "am_I_dead", NULL, am_i_dead, 0, 0 },
    { "make_white", NULL, make_white, 0, 0 },
    { "make_norm", NULL, make_norm, 0, 0 },
    { "set_skeleton_pal", NULL, set_skeleton_pal, 0, 0 },
    { "set_my_pal", NULL, set_my_pal, 0, 0 },
    { "tbukl_flip", NULL, tbukl_flip, 0, 0 },
    { "face_inside", NULL, face_inside, 0, 0 },
    { "HIT_THE_MAT", NULL, hit_the_mat, 0, 0 },
    { "DO_BLOCKED", NULL, do_blocked, 0, 0 },
    { "MAKE_HIM_SCREAM", NULL, make_him_scream, 0, 0 },
    { "DO_SCREAM", NULL, do_scream, 0, 0 },
    { "GOUGE_SOUND", NULL, gouge_sound, 0, 0 },
    { "DO_RAZOR_RUG_SPEECH", NULL, do_razor_rug_speech, 0, 0 },
    { "CALL_BONE_BREAK", NULL, call_bone_break, 0, 0 },
    { "SMALL_BOUNCE", NULL, small_bounce, 0, 0 },
    { "SMALL_RUN", NULL, small_run, 0, 0 },
    { "DO_FLAME_SND", NULL, do_flame_snd, 0, 0 },
    { "DO_FLAME_HIT_SND", NULL, do_flame_hit_snd, 0, 0 },
    { "DO_WAIL", NULL, do_wail, 0, 0 },
    { "DO_CHOKE", NULL, do_choke, 0, 0 },
    { "DO_NONO", NULL, do_nono, 0, 0 },
    { "DO_OTHERNONO", NULL, do_othernono, 0, 0 },
    { "DO_DOINK_SLAM", NULL, do_doink_slam, 0, 0 },
    { "FIND_AND_KILL_ENDLESS", NULL, find_and_kill_endless, 0, 0 },
    { "DO_RAZOR_PUSH", NULL, do_razor_push, 0, 0 },
    { "DO_DOINK_PUSH", NULL, do_doink_push, 0, 0 },
    { "DO_SHAWN_PUSH", NULL, do_shawn_push, 0, 0 },
    { "DO_BRET_PUSH", NULL, do_bret_push, 0, 0 },
    { "DO_LEX_PUSH", NULL, do_lex_push, 0, 0 },
    { "DO_COMBO_MESS", NULL, do_combo_mess, 0, 0 },
    /* SUBRP, so file-local -- and only HRTSEQ3.ASM calls it. */
    { "#rope_check", "HRTSEQ3.ASM", rope_check, 0, 0 },
    { "#check_xvel", "SHNSEQ3.ASM", check_xvel_local, 0, 0 },
    { "#grunt", "SHNSEQ3.ASM", shawn_grunt, 0, 0 },
    { "#hit_ground", "BAMSEQ2.ASM", hit_ground, 0, 0 },
    /* UNDSEQ3's `#set` is #delay_whoihit's shape with an eight-second
       window instead of 55 ticks. */
    { "#set", "UNDSEQ3.ASM", delay_whoihit_param, 8 * 60, 0 },
    /* YOKSEQ4's local #choose_2or4 is byte-identical to SHNSEQ4's global
       one, so it shares the body rather than getting a second copy. */
    { "#choose_2or4", "YOKSEQ4.ASM", choose_2or4, 0, 0 },
    { "spunch_delay", NULL, spunch_delay, 0, 0 },
    { "DO_CROWD_CHEER", NULL, do_crowd_cheer, 0, 0 },
    { "shake_all_ropes", NULL, shake_all_ropes, 0, 0 },
    { "get_leap", NULL, get_leap, 0, 0 },
    { "hit_nearest", NULL, hit_nearest, 0, 0 },
    { "set_tbukl_confine", NULL, set_tbukl_confine, 0, 0 },
    { "win_announce", NULL, win_announce, 0, 0 },
    { "grnd_hit", NULL, grnd_hit, 0, 0 },
    { "#setopp_deadanim", NULL, setopp_deadanim, 0, 0 },
    { "#zero_x_4", "SHNSEQ2.ASM", zero_x_4, 0, 0 },
    /* The local copy kills Z as well; the global no_bk_xvel does not. */
    { "#no_bk_xvel", "SHNSEQ3.ASM", no_bk_xvel_local, 0, 0 },
    { "#delay_whoihit", "YOKSEQ2.ASM", delay_whoihit_param, 55, 0 },
    { "#ck_flip", "LEXSEQ3.ASM", ck_flip, 0, 0 },
    { "#ck_dead_opp", "HRTSEQ3.ASM", ck_dead_opp, 0, 0 },
    { "#set_wrestler_xflip", "HRTSEQ4.ASM", set_wrestler_xflip_code, 0, 0 },
    /* Another SPCDMG, with its own pair. */
    { "#stop_dmg", "YOKSEQ3.ASM", reduce_dmg, WM_SPCDMG(2, 35), 0 },
    { "inc_loop", "UNDSEQ3.ASM", und_inc_loop, 0, 0 },
    { "check_xvel", NULL, check_xvel, 0, 0 },
    /* SPCDMG's two constants, packed: damage in the high half, ticks in
       the low. Three files, three pairs. */
    { "#reduce_dmg", "RZRSEQ3.ASM", reduce_dmg, WM_SPCDMG(22, 80), 0 },
    { "#reduce_dmg", "SHNSEQ3.ASM", reduce_dmg, WM_SPCDMG(6, 40), 0 },
    { "#reduce_dmg", "UNDSEQ2.ASM", reduce_dmg, WM_SPCDMG(8, 40), 0 },
    { "#reattach", "DNKSEQ3.ASM", reattach, 0, 0 },
    { "#reattach", "HRTSEQ3.ASM", reattach, 0, 0 },
    { "#reattach", "UNDSEQ3.ASM", reattach, 0, 0 },
    { "SET_OPP_GRAV_NORM", "RZRSEQ2.ASM", set_opp_grav, WM_GRAVITY, 0 },
    { "SET_OPP_GRAV_NORM", "UNDSEQ2.ASM", set_opp_grav, WM_GRAVITY, 0 },
    { "SET_OPP_GRAV_LOW", "RZRSEQ2.ASM", set_opp_grav, WM_GRAVITY - 0x1000, 0 },
    { "SET_OPP_GRAV_LOW", "UNDSEQ2.ASM", set_opp_grav, WM_GRAVITY - 0x1000, 0 },
    /* Doink and Bret pop him 5.0; Razor only 4.0. */
    { "#go_high", "DNKSEQ3.ASM", go_high, 0x50000, 0 },
    { "#go_high", "HRTSEQ2.ASM", go_high, 0x50000, 0 },
    { "#go_high", "RZRSEQ3.ASM", go_high, 0x40000, 0 },
    { "target_whoihit", NULL, target_whoihit, 0, 0 },
    { "#set_opp_facing", "SHNSEQ3.ASM", set_opp_facing, 0, 0 },
    { "#blocked_vels", "RZRSEQ2.ASM", blocked_vels, 0, 0 },
    { "MAYBE_BOUNCE_ROPE", NULL, maybe_bounce_rope, 0, 0 },
    /*
     * #set_trgt: seven files at 0f8h+60, Doink alone at 0f8h+50. The
     * param is that margin, so the difference is data rather than a
     * second body.
     */
    { "#set_trgt", "BAMSEQ2.ASM", set_trgt, 60, 0 },
    { "#set_trgt", "HRTSEQ2.ASM", set_trgt, 60, 0 },
    { "#set_trgt", "LEXSEQ2.ASM", set_trgt, 60, 0 },
    { "#set_trgt", "RZRSEQ2.ASM", set_trgt, 60, 0 },
    { "#set_trgt", "SHNSEQ2.ASM", set_trgt, 60, 0 },
    { "#set_trgt", "UNDSEQ2.ASM", set_trgt, 60, 0 },
    { "#set_trgt", "YOKSEQ2.ASM", set_trgt, 60, 0 },
    { "#set_trgt", "DNKSEQ2.ASM", set_trgt, 50, 0 },
    { "#clrcnt", "DNKSEQ2.ASM", clrcnt, 0, 0 },
    { "#clrcnt", "LEXSEQ2.ASM", clrcnt, 0, 0 },
    { "#clrcnt", "RZRSEQ2.ASM", clrcnt, 0, 0 },
    { "#clrcnt", "UNDSEQ2.ASM", clrcnt, 0, 0 },
    { "set_xdrift", NULL, set_xdrift, 0, 0 },
    { "set_buckoff_vels", NULL, set_buckoff_vels, 0, 0 },
    { "skick_delay", NULL, skick_delay, 0, 0 },
    { "tgt_ground", NULL, tgt_ground, 0, 0 },
    { "tgt_tbukl", NULL, tgt_tbukl, 0, 0 },
    /* SUBRP, so file-local: the rug slam without the headbutt. */
    { "impact_sound", "HRTSEQ4.ASM", impact_sound_local, 0, 0 },
    { "impact_sound", "RZRSEQ3.ASM", impact_sound_local, 0, 0 },
    /* YOKSEQ3.ASM's SUBR, which every other file reaches. */
    { "impact_sound", NULL, impact_sound_global, 0, 0 },
    /* LEXSEQ3.ASM's bare label shadows SHNSEQ2.ASM's SUBR. */
    { "DO_GRUNT", "LEXSEQ3.ASM", do_grunt_luger, 0, 0 },
    { "DO_GRUNT", NULL, do_grunt, 0, 0 },
    /* #make_black, once per file, each with its own palette black. */
    { "#make_black", "HRTSEQ4.ASM", make_black, 0x2F2F, 0 },
    { "#make_black", "RZRSEQ3.ASM", make_black, 0x0D0D, 0 },
    { "#make_black", "UNDSEQ3.ASM", make_black, 0x3F3F, 0 },
    { "#make_black", "YOKSEQ3.ASM", make_black, 0x0F0F, 0 },
    { "#make_black", "SHNSEQ4.ASM", make_black, 0x2121, 0 },
    { "#make_black", "BAMSEQ3.ASM", make_black, 0x0B0B, 0 },
    { "#make_black", "DNKSEQ3.ASM", make_black, 0x0B0B, 0 },
    { "#make_black", "LEXSEQ3.ASM", make_black, 0x1A1A, 0 },
};

bool wm_anim_code_run(wm_arcade_actor_t *actor, const wm_anim_env *env,
                      const char *name, const char *source_file,
                      int32_t def_line) {
    size_t i;
    const size_t n = sizeof(code_table) / sizeof(code_table[0]);
    if (!name) return false;
    /* Most specific first: this file AND this definition, then this file's
       unnumbered row, then a global of the same name. A local label really
       does shadow a global, and a second definition of the same local name
       really is a different routine, so resolving in that order is the
       assembler's own. */
    if (def_line)
        for (i = 0; i < n; ++i)
            if (code_table[i].line == def_line && code_table[i].file &&
                source_file &&
                strcmp(code_table[i].name, name) == 0 &&
                strcmp(code_table[i].file, source_file) == 0) {
                code_table[i].fn(actor, env, code_table[i].param);
                return true;
            }
    for (i = 0; i < n; ++i)
        if (code_table[i].file && code_table[i].line == 0 && source_file &&
            strcmp(code_table[i].name, name) == 0 &&
            strcmp(code_table[i].file, source_file) == 0) {
            code_table[i].fn(actor, env, code_table[i].param);
            return true;
        }
    for (i = 0; i < n; ++i)
        if (!code_table[i].file && strcmp(code_table[i].name, name) == 0) {
            code_table[i].fn(actor, env, code_table[i].param);
            return true;
        }
    /* The announcer group is data, not code: the name resolves against
       wm_announce_calls[] rather than against a hand-kept row, so a
       caller cannot be spelled one way here and another way there. */
    {
        const wm_announce_call *c = wm_announce_call_find(name);
        if (c) return announce_call(actor, env, c);
    }
    return false;
}

size_t wm_anim_code_count(void) {
    return sizeof(code_table) / sizeof(code_table[0]);
}
