#!/usr/bin/env sh
set -eu
ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
ORIG="$ROOT/original/wwf-wrestlemania"
if [ ! -f "$ORIG/ANIM.EQU" ] || [ ! -f "$ORIG/FINISEQ.ASM" ] || \
   [ ! -f "$ORIG/HRTSEQ1.ASM" ] || [ ! -f "$ORIG/HRTSEQ2.ASM" ] || \
   [ ! -f "$ORIG/ATTRACT.ASM" ] || [ ! -f "$ORIG/SELECT.ASM" ]; then
    sh "$ROOT/scripts/fetch_original.sh"
fi
python3 "$ROOT/tools/asmseq.py" \
    --equ "$ORIG/ANIM.EQU" \
    --source "$ORIG/FINISEQ.ASM" \
    --label hrt_finish1_move \
    --symbol wm_seq_hrt_finish1_move \
    --out "$ROOT/src/generated/finish_sequences.c"
python3 "$ROOT/tools/wlanim.py" \
    --source "$ORIG/HRTSEQ1.ASM" \
    --sequence hrt_stand2_anim wm_bret_stand2_anim bret_stand2_frames \
    --sequence hrt_stand4_anim wm_bret_stand4_anim bret_stand4_frames \
    --sequence hrt_torso2_anim wm_bret_torso2_anim bret_torso2_frames \
    --sequence hrt_torso4_anim wm_bret_torso4_anim bret_torso4_frames \
    --sequence hrt_torso6_anim wm_bret_torso6_anim bret_torso6_frames \
    --sequence hrt_torso8_anim wm_bret_torso8_anim bret_torso8_frames \
    --sequence hrt_walk1_f2_anim wm_bret_walk1_f2_anim bret_walk1_f2_frames \
    --sequence hrt_walk1_f4_anim wm_bret_walk1_f4_anim bret_walk1_f4_frames \
    --sequence hrt_walk2_f2_anim wm_bret_walk2_f2_anim bret_walk2_f2_frames \
    --sequence hrt_walk2_f4_anim wm_bret_walk2_f4_anim bret_walk2_f4_frames \
    --sequence hrt_walk4_f2_anim wm_bret_walk4_f2_anim bret_walk4_f2_frames \
    --sequence hrt_walk4_f4_anim wm_bret_walk4_f4_anim bret_walk4_f4_frames \
    --sequence hrt_walk5_f2_anim wm_bret_walk5_f2_anim bret_walk5_f2_frames \
    --sequence hrt_walk5_f4_anim wm_bret_walk5_f4_anim bret_walk5_f4_frames \
    --sequence hrt_walk6_f2_anim wm_bret_walk6_f2_anim bret_walk6_f2_frames \
    --sequence hrt_walk6_f4_anim wm_bret_walk6_f4_anim bret_walk6_f4_frames \
    --sequence hrt_walk8_f2_anim wm_bret_walk8_f2_anim bret_walk8_f2_frames \
    --sequence hrt_walk8_f4_anim wm_bret_walk8_f4_anim bret_walk8_f4_frames \
    --sequence hrt_2_to_4_turn_anim wm_bret_2_to_4_turn_anim bret_2_to_4_turn_frames \
    --sequence hrt_4_to_2_turn_anim wm_bret_4_to_2_turn_anim bret_4_to_2_turn_frames \
    --sequence hrt_4_to_6_turn_anim wm_bret_4_to_6_turn_anim bret_4_to_6_turn_frames \
    --sequence hrt_2_to_8_turn_anim wm_bret_2_to_8_turn_anim bret_2_to_8_turn_frames \
    --sequence hrt_4_to_8_turn_anim wm_bret_4_to_8_turn_anim bret_4_to_8_turn_frames \
    --sequence hrt_2_to_6_turn_anim wm_bret_2_to_6_turn_anim bret_2_to_6_turn_frames \
    --sequence hrt_2_to_4_turn2_anim wm_bret_2_to_4_turn2_anim bret_2_to_4_turn2_frames \
    --sequence hrt_4_to_2_turn2_anim wm_bret_4_to_2_turn2_anim bret_4_to_2_turn2_frames \
    --sequence hrt_4_to_6_turn2_anim wm_bret_4_to_6_turn2_anim bret_4_to_6_turn2_frames \
    --sequence hrt_2_to_8_turn2_anim wm_bret_2_to_8_turn2_anim bret_2_to_8_turn2_frames \
    --sequence hrt_4_to_8_turn2_anim wm_bret_4_to_8_turn2_anim bret_4_to_8_turn2_frames \
    --sequence hrt_2_to_6_turn2_anim wm_bret_2_to_6_turn2_anim bret_2_to_6_turn2_frames \
    --slice hrt_run_anim wm_bret_run_anim bret_run_frames true \
    --out "$ROOT/src/generated/bret_visuals.c"
python3 "$ROOT/tools/wlanim.py" \
    --source "$ORIG/HRTSEQ2.ASM" \
    --slice hrt_2_punch_anim wm_bret_light_punch2_anim bret_light_punch2_frames false \
    --slice hrt_4_punch_anim wm_bret_light_punch4_anim bret_light_punch4_frames false \
    --slice hrt_4_super_punch_anim wm_bret_power_punch_anim bret_power_punch_frames false \
    --slice hrt_2_super_punch2_anim wm_bret_super_punch2_2_anim bret_super_punch2_2_frames false \
    --slice hrt_4_super_punch2_anim wm_bret_super_punch2_4_anim bret_super_punch2_4_frames false \
    --slice hrt_2_kick_anim wm_bret_light_kick2_anim bret_light_kick2_frames false \
    --slice hrt_4_kick_anim wm_bret_light_kick4_anim bret_light_kick4_frames false \
    --slice hrt_2_super_kick_anim wm_bret_power_kick_anim bret_power_kick_frames false \
    --slice hrt_2_butt_anim wm_bret_butt2_anim bret_butt2_frames false \
    --slice hrt_4_butt_anim wm_bret_butt4_anim bret_butt4_frames false \
    --slice hrt_2_knee_anim wm_bret_knee2_anim bret_knee2_frames false \
    --slice hrt_4_knee_anim wm_bret_knee4_anim bret_knee4_frames false \
    --slice hrt_4_uppercut_anim wm_bret_uppercut4_anim bret_uppercut4_frames false \
    --slice hrt_2_stomp_anim wm_bret_stomp2_anim bret_stomp2_frames false \
    --slice hrt_4_stomp_anim wm_bret_stomp4_anim bret_stomp4_frames false \
    --slice hrt_2_ground_punch_anim wm_bret_ground_punch2_anim bret_ground_punch2_frames false \
    --slice hrt_4_ground_punch_anim wm_bret_ground_punch4_anim bret_ground_punch4_frames false \
    --slice hrt_4_push_anim wm_bret_push4_anim bret_push4_frames false \
    --slice hrt_4_jump_kick_anim wm_bret_jump_kick4_anim bret_jump_kick4_frames false \
    --slice hrt_4_knee_fall_anim wm_bret_knee_fall4_anim bret_knee_fall4_frames false \
    --slice hrt_kick_TB_anim wm_bret_kick_tb_anim bret_kick_tb_frames false \
    --slice hrt_4_knee_to_head_anim wm_bret_knee_to_head4_anim bret_knee_to_head4_frames false \
    --slice hrt_knees_to_head_anim wm_bret_knees_to_head_anim bret_knees_to_head_frames false \
    --slice hrt_2_pin_anim wm_bret_pin2_anim bret_pin2_frames false \
    --slice hrt_4_pin_anim wm_bret_pin4_anim bret_pin4_frames false \
    --slice hrt_2_butts_anim wm_bret_butts2_anim bret_butts2_frames false \
    --slice hrt_4_butts_anim wm_bret_butts4_anim bret_butts4_frames false \
    --slice hrt_flying_kick_anim wm_bret_flying_kick_anim bret_flying_kick_frames false \
    --slice hrt_tbukl_leap_anim wm_bret_tbukl_leap_anim bret_tbukl_leap_frames false \
    --slice hrt_running_ground_punch_anim wm_bret_running_ground_punch_anim bret_running_ground_punch_frames false \
    --slice hrt_combo_punch_anim wm_bret_combo_punch_anim bret_combo_punch_frames false \
    --slice hrt_combo_kick_anim wm_bret_combo_kick_anim bret_combo_kick_frames false \
    --out "$ROOT/src/generated/bret_attacks.c"
python3 "$ROOT/tools/wlanim.py" \
    --source "$ORIG/HRTSEQ4.ASM" \
    --slice hrt_4_block_anim wm_bret_block4_anim bret_block4_frames false \
    --slice hrt_fall_back_anim wm_bret_fall_back_anim bret_fall_back_frames false \
    --slice hrt_facedown_getup_anim wm_bret_facedown_getup_anim bret_facedown_getup_frames false \
    --slice hrt_faceup_getup_anim wm_bret_faceup_getup_anim bret_faceup_getup_frames false \
    --slice hrt_4_faceup_getup2_anim wm_bret_faceup_getup2_4_anim bret_faceup_getup2_4_frames false \
    --slice hrt_hitonground_facedown_anim wm_bret_hitonground_facedown_anim bret_hitonground_facedown_frames false \
    --out "$ROOT/src/generated/bret_defense.c"
python3 "$ROOT/tools/wlanim.py" \
    --source "$ORIG/HRTSEQ3.ASM" \
    --slice hrt_3_head_held_stand_anim wm_bret_head_held_stand3_anim bret_head_held_stand3_frames false \
    --slice hrt_3_fake_hold_anim wm_bret_fake_hold3_anim bret_fake_hold3_frames false \
    --slice hrt_3_pile_driver_anim wm_bret_pile_driver3_anim bret_pile_driver3_frames false \
    --out "$ROOT/src/generated/bret_grapple.c"
# ANI_SUPERSLAVE2's per-wrestler defender-frame tables -- the data behind
# every grapple, slam, suplex and throw. Emitted before the programs,
# because a program's ANI_SUPERSLAVE2 op carries an id into this table.
python3 "$ROOT/tools/wlpuppet.py" \
    --out "$ROOT/src/generated/puppet_tables.c"

# WRESTLE2.ASM:1290 do_roll's per-wrestler roll tables -- the frames a
# knocked-down wrestler shows while the player rolls him along Z.
python3 "$ROOT/tools/wlroll.py" \
    --out "$ROOT/src/generated/roll_frames.c"

# Each animation as the op stream ANIM.ASM runs (wm/anim_program.h), which
# is what the Bret backend actually executes -- this file used to be
# generated by hand, which is exactly how generated data drifts from the
# tool that makes it.
python3 "$ROOT/tools/wlprogram.py" \
    --slave-targets \
    --animation "$ORIG/WRESTLE2.ASM" xxx_dead_anim \
    --animation "$ORIG/HRTSEQ2.ASM" hrt_2_punch_anim \
    --animation "$ORIG/HRTSEQ2.ASM" hrt_4_punch_anim \
    --animation "$ORIG/HRTSEQ2.ASM" hrt_4_super_punch_anim \
    --animation "$ORIG/HRTSEQ2.ASM" hrt_2_super_punch2_anim \
    --animation "$ORIG/HRTSEQ2.ASM" hrt_4_super_punch2_anim \
    --animation "$ORIG/HRTSEQ2.ASM" hrt_2_kick_anim \
    --animation "$ORIG/HRTSEQ2.ASM" hrt_4_kick_anim \
    --animation "$ORIG/HRTSEQ2.ASM" hrt_2_super_kick_anim \
    --animation "$ORIG/HRTSEQ2.ASM" hrt_2_butt_anim \
    --animation "$ORIG/HRTSEQ2.ASM" hrt_4_butt_anim \
    --animation "$ORIG/HRTSEQ2.ASM" hrt_2_knee_anim \
    --animation "$ORIG/HRTSEQ2.ASM" hrt_4_knee_anim \
    --animation "$ORIG/HRTSEQ2.ASM" hrt_4_uppercut_anim \
    --animation "$ORIG/HRTSEQ2.ASM" hrt_2_stomp_anim \
    --animation "$ORIG/HRTSEQ2.ASM" hrt_4_stomp_anim \
    --animation "$ORIG/HRTSEQ2.ASM" hrt_2_ground_punch_anim \
    --animation "$ORIG/HRTSEQ2.ASM" hrt_4_ground_punch_anim \
    --animation "$ORIG/HRTSEQ2.ASM" hrt_4_push_anim \
    --animation "$ORIG/HRTSEQ2.ASM" hrt_4_jump_kick_anim \
    --animation "$ORIG/HRTSEQ2.ASM" hrt_4_knee_fall_anim \
    --animation "$ORIG/HRTSEQ2.ASM" hrt_kick_TB_anim \
    --animation "$ORIG/HRTSEQ2.ASM" hrt_4_knee_to_head_anim \
    --animation "$ORIG/HRTSEQ2.ASM" hrt_knees_to_head_anim \
    --animation "$ORIG/HRTSEQ2.ASM" hrt_2_pin_anim \
    --animation "$ORIG/HRTSEQ2.ASM" hrt_4_pin_anim \
    --animation "$ORIG/HRTSEQ2.ASM" hrt_2_butts_anim \
    --animation "$ORIG/HRTSEQ2.ASM" hrt_4_butts_anim \
    --animation "$ORIG/HRTSEQ2.ASM" hrt_flying_kick_anim \
    --animation "$ORIG/HRTSEQ2.ASM" hrt_tbukl_leap_anim \
    --animation "$ORIG/HRTSEQ2.ASM" hrt_running_ground_punch_anim \
    --animation "$ORIG/HRTSEQ2.ASM" hrt_combo_punch_anim \
    --animation "$ORIG/HRTSEQ2.ASM" hrt_combo_kick_anim \
    --animation "$ORIG/HRTSEQ3.ASM" hrt_3_head_held_stand_anim \
    --animation "$ORIG/HRTSEQ3.ASM" hrt_3_fake_hold_anim \
    --animation "$ORIG/HRTSEQ3.ASM" hrt_3_pile_driver_anim \
    --animation "$ORIG/HRTSEQ3.ASM" hrt_hiptoss_anim \
    --animation "$ORIG/HRTSEQ4.ASM" hrt_4_block_anim \
    --animation "$ORIG/HRTSEQ4.ASM" hrt_fall_back_anim \
    --animation "$ORIG/HRTSEQ4.ASM" hrt_facedown_getup_anim \
    --animation "$ORIG/HRTSEQ4.ASM" hrt_faceup_getup_anim \
    --animation "$ORIG/HRTSEQ4.ASM" hrt_4_faceup_getup2_anim \
    --animation "$ORIG/HRTSEQ4.ASM" hrt_hitonground_facedown_anim \
    --animation "$ORIG/BAMSEQ1.ASM" bam_run2_anim \
    --animation "$ORIG/BAMSEQ1.ASM" bam_stand2_anim \
    --animation "$ORIG/BAMSEQ1.ASM" bam_stand4_anim \
    --animation "$ORIG/BAMSEQ1.ASM" bam_torso2_anim \
    --animation "$ORIG/BAMSEQ1.ASM" bam_torso4_anim \
    --animation "$ORIG/BAMSEQ2.ASM" bam_2_butt_anim \
    --animation "$ORIG/BAMSEQ2.ASM" bam_2_butts_anim \
    --animation "$ORIG/BAMSEQ2.ASM" bam_2_fpunch_anim \
    --animation "$ORIG/BAMSEQ2.ASM" bam_2_kick_anim \
    --animation "$ORIG/BAMSEQ2.ASM" bam_2_knee_anim \
    --animation "$ORIG/BAMSEQ2.ASM" bam_2_lbowdrop_anim \
    --animation "$ORIG/BAMSEQ2.ASM" bam_2_pin_anim \
    --animation "$ORIG/BAMSEQ2.ASM" bam_2_punch_anim \
    --animation "$ORIG/BAMSEQ2.ASM" bam_2_raise_arm_anim \
    --animation "$ORIG/BAMSEQ2.ASM" bam_2_slap_anim \
    --animation "$ORIG/BAMSEQ2.ASM" bam_2_stomp_anim \
    --animation "$ORIG/BAMSEQ2.ASM" bam_4_block_anim \
    --animation "$ORIG/BAMSEQ2.ASM" bam_4_butt_anim \
    --animation "$ORIG/BAMSEQ2.ASM" bam_4_butts_anim \
    --animation "$ORIG/BAMSEQ2.ASM" bam_4_fpunch_anim \
    --animation "$ORIG/BAMSEQ2.ASM" bam_4_jumpkick_anim \
    --animation "$ORIG/BAMSEQ2.ASM" bam_4_kick_anim \
    --animation "$ORIG/BAMSEQ2.ASM" bam_4_knee_anim \
    --animation "$ORIG/BAMSEQ2.ASM" bam_4_lbowdrop_anim \
    --animation "$ORIG/BAMSEQ2.ASM" bam_4_pin_anim \
    --animation "$ORIG/BAMSEQ2.ASM" bam_4_punch_anim \
    --animation "$ORIG/BAMSEQ2.ASM" bam_4_push_anim \
    --animation "$ORIG/BAMSEQ2.ASM" bam_4_raise_arm_anim \
    --animation "$ORIG/BAMSEQ2.ASM" bam_4_slap_anim \
    --animation "$ORIG/BAMSEQ2.ASM" bam_4_stomp_anim \
    --animation "$ORIG/BAMSEQ2.ASM" bam_bellyflop_anim \
    --animation "$ORIG/BAMSEQ2.ASM" bam_fall_back_anim \
    --animation "$ORIG/BAMSEQ2.ASM" bam_flying_kick_anim \
    --animation "$ORIG/BAMSEQ3.ASM" bam_2_napalm_anim \
    --animation "$ORIG/BAMSEQ3.ASM" bam_3_head_held_stand_anim \
    --animation "$ORIG/BAMSEQ3.ASM" bam_3_head_hold2_anim \
    --animation "$ORIG/BAMSEQ3.ASM" bam_3_head_hold_anim \
    --animation "$ORIG/BAMSEQ3.ASM" bam_4_napalm_anim \
    --animation "$ORIG/BAMSEQ3.ASM" bam_climb_down_anim \
    --animation "$ORIG/DNKSEQ1.ASM" dnk_run2_anim \
    --animation "$ORIG/DNKSEQ1.ASM" dnk_stand2_anim \
    --animation "$ORIG/DNKSEQ1.ASM" dnk_stand4_anim \
    --animation "$ORIG/DNKSEQ1.ASM" dnk_torso2_anim \
    --animation "$ORIG/DNKSEQ1.ASM" dnk_torso4_anim \
    --animation "$ORIG/DNKSEQ2.ASM" dnk_2_box_anim \
    --animation "$ORIG/DNKSEQ2.ASM" dnk_2_butt_anim \
    --animation "$ORIG/DNKSEQ2.ASM" dnk_2_butts_anim \
    --animation "$ORIG/DNKSEQ2.ASM" dnk_2_kick_anim \
    --animation "$ORIG/DNKSEQ2.ASM" dnk_2_knee_anim \
    --animation "$ORIG/DNKSEQ2.ASM" dnk_2_lbowdrop_anim \
    --animation "$ORIG/DNKSEQ2.ASM" dnk_2_pin_anim \
    --animation "$ORIG/DNKSEQ2.ASM" dnk_2_punch_anim \
    --animation "$ORIG/DNKSEQ2.ASM" dnk_2_raise_arm_anim \
    --animation "$ORIG/DNKSEQ2.ASM" dnk_2_stomp_anim \
    --animation "$ORIG/DNKSEQ2.ASM" dnk_4_block_anim \
    --animation "$ORIG/DNKSEQ2.ASM" dnk_4_box_anim \
    --animation "$ORIG/DNKSEQ2.ASM" dnk_4_bstomp_anim \
    --animation "$ORIG/DNKSEQ2.ASM" dnk_4_butt_anim \
    --animation "$ORIG/DNKSEQ2.ASM" dnk_4_butts_anim \
    --animation "$ORIG/DNKSEQ2.ASM" dnk_4_hammer_anim \
    --animation "$ORIG/DNKSEQ2.ASM" dnk_4_kick_anim \
    --animation "$ORIG/DNKSEQ2.ASM" dnk_4_knee_anim \
    --animation "$ORIG/DNKSEQ2.ASM" dnk_4_lbowdrop_anim \
    --animation "$ORIG/DNKSEQ2.ASM" dnk_4_pin_anim \
    --animation "$ORIG/DNKSEQ2.ASM" dnk_4_punch_anim \
    --animation "$ORIG/DNKSEQ2.ASM" dnk_4_push_anim \
    --animation "$ORIG/DNKSEQ2.ASM" dnk_4_raise_arm_anim \
    --animation "$ORIG/DNKSEQ2.ASM" dnk_4_stomp_anim \
    --animation "$ORIG/DNKSEQ2.ASM" dnk_climb_down_anim \
    --animation "$ORIG/DNKSEQ2.ASM" dnk_diveofftb_anim \
    --animation "$ORIG/DNKSEQ2.ASM" dnk_fall_back_anim \
    --animation "$ORIG/DNKSEQ2.ASM" dnk_flying_kick_anim \
    --animation "$ORIG/DNKSEQ3.ASM" dnk_2_buzz2_anim \
    --animation "$ORIG/DNKSEQ3.ASM" dnk_2_buzz_anim \
    --animation "$ORIG/DNKSEQ3.ASM" dnk_2_earslap_anim \
    --animation "$ORIG/DNKSEQ3.ASM" dnk_2_slap_anim \
    --animation "$ORIG/DNKSEQ3.ASM" dnk_3_head_held_stand_anim \
    --animation "$ORIG/DNKSEQ3.ASM" dnk_3_head_hold2_anim \
    --animation "$ORIG/DNKSEQ3.ASM" dnk_3_head_hold_anim \
    --animation "$ORIG/DNKSEQ3.ASM" dnk_4_buzz2_anim \
    --animation "$ORIG/DNKSEQ3.ASM" dnk_4_buzz_anim \
    --animation "$ORIG/DNKSEQ3.ASM" dnk_4_earslap_anim \
    --animation "$ORIG/DNKSEQ3.ASM" dnk_4_slap_anim \
    --animation "$ORIG/DNKSEQ3.ASM" dnk_combo_uppercut_to_head_anim \
    --animation "$ORIG/LEXSEQ1.ASM" lex_run2_anim \
    --animation "$ORIG/LEXSEQ1.ASM" lex_stand2_anim \
    --animation "$ORIG/LEXSEQ1.ASM" lex_stand4_anim \
    --animation "$ORIG/LEXSEQ1.ASM" lex_torso2_anim \
    --animation "$ORIG/LEXSEQ1.ASM" lex_torso4_anim \
    --animation "$ORIG/LEXSEQ2.ASM" lex_2_butt_anim \
    --animation "$ORIG/LEXSEQ2.ASM" lex_2_clobber_anim \
    --animation "$ORIG/LEXSEQ2.ASM" lex_2_grabfling_anim \
    --animation "$ORIG/LEXSEQ2.ASM" lex_2_ground_punch_anim \
    --animation "$ORIG/LEXSEQ2.ASM" lex_2_kick_anim \
    --animation "$ORIG/LEXSEQ2.ASM" lex_2_pin_anim \
    --animation "$ORIG/LEXSEQ2.ASM" lex_2_punch_anim \
    --animation "$ORIG/LEXSEQ2.ASM" lex_2_raise_arm_anim \
    --animation "$ORIG/LEXSEQ2.ASM" lex_2_stomp_anim \
    --animation "$ORIG/LEXSEQ2.ASM" lex_3_clobber_anim \
    --animation "$ORIG/LEXSEQ2.ASM" lex_4_butt_anim \
    --animation "$ORIG/LEXSEQ2.ASM" lex_4_clobber_anim \
    --animation "$ORIG/LEXSEQ2.ASM" lex_4_grabfling_anim \
    --animation "$ORIG/LEXSEQ2.ASM" lex_4_ground_punch_anim \
    --animation "$ORIG/LEXSEQ2.ASM" lex_4_kick_anim \
    --animation "$ORIG/LEXSEQ2.ASM" lex_4_knee_anim \
    --animation "$ORIG/LEXSEQ2.ASM" lex_4_pin_anim \
    --animation "$ORIG/LEXSEQ2.ASM" lex_4_punch_anim \
    --animation "$ORIG/LEXSEQ2.ASM" lex_4_push_anim \
    --animation "$ORIG/LEXSEQ2.ASM" lex_4_raise_arm_anim \
    --animation "$ORIG/LEXSEQ2.ASM" lex_4_stomp_anim \
    --animation "$ORIG/LEXSEQ2.ASM" lex_buckle_leap_anim \
    --animation "$ORIG/LEXSEQ2.ASM" lex_flying_kick_anim \
    --animation "$ORIG/LEXSEQ3.ASM" lex_3_head_held_stand_anim \
    --animation "$ORIG/LEXSEQ3.ASM" lex_3_head_hold2_anim \
    --animation "$ORIG/LEXSEQ3.ASM" lex_3_head_hold_anim \
    --animation "$ORIG/LEXSEQ3.ASM" lex_climb_down_anim \
    --animation "$ORIG/LEXSEQ3.ASM" lex_sliding_elbow_anim \
    --animation "$ORIG/LEXSEQ4.ASM" lex_4_block_anim \
    --animation "$ORIG/LEXSEQ4.ASM" lex_fall_back_anim \
    --animation "$ORIG/SHNSEQ1.ASM" shn_run2_anim \
    --animation "$ORIG/SHNSEQ1.ASM" shn_stand2_anim \
    --animation "$ORIG/SHNSEQ1.ASM" shn_stand4_anim \
    --animation "$ORIG/SHNSEQ1.ASM" shn_torso2_anim \
    --animation "$ORIG/SHNSEQ1.ASM" shn_torso4_anim \
    --animation "$ORIG/SHNSEQ2.ASM" shn_2_butt_anim \
    --animation "$ORIG/SHNSEQ2.ASM" shn_2_falling_punch_anim \
    --animation "$ORIG/SHNSEQ2.ASM" shn_2_kick_anim \
    --animation "$ORIG/SHNSEQ2.ASM" shn_2_knee_anim \
    --animation "$ORIG/SHNSEQ2.ASM" shn_2_pin_anim \
    --animation "$ORIG/SHNSEQ2.ASM" shn_2_pummel_anim \
    --animation "$ORIG/SHNSEQ2.ASM" shn_2_punch_anim \
    --animation "$ORIG/SHNSEQ2.ASM" shn_2_raise_arm_anim \
    --animation "$ORIG/SHNSEQ2.ASM" shn_2_stomp_anim \
    --animation "$ORIG/SHNSEQ2.ASM" shn_4_butt_anim \
    --animation "$ORIG/SHNSEQ2.ASM" shn_4_falling_punch_anim \
    --animation "$ORIG/SHNSEQ2.ASM" shn_4_jump_kick_anim \
    --animation "$ORIG/SHNSEQ2.ASM" shn_4_kick_anim \
    --animation "$ORIG/SHNSEQ2.ASM" shn_4_knee_anim \
    --animation "$ORIG/SHNSEQ2.ASM" shn_4_pin_anim \
    --animation "$ORIG/SHNSEQ2.ASM" shn_4_pummel_anim \
    --animation "$ORIG/SHNSEQ2.ASM" shn_4_punch_anim \
    --animation "$ORIG/SHNSEQ2.ASM" shn_4_push_anim \
    --animation "$ORIG/SHNSEQ2.ASM" shn_4_raise_arm_anim \
    --animation "$ORIG/SHNSEQ2.ASM" shn_4_stomp_anim \
    --animation "$ORIG/SHNSEQ2.ASM" shn_belbow_anim \
    --animation "$ORIG/SHNSEQ2.ASM" shn_bstomp_anim \
    --animation "$ORIG/SHNSEQ2.ASM" shn_climb_down_anim \
    --animation "$ORIG/SHNSEQ2.ASM" shn_flying_kick_anim \
    --animation "$ORIG/SHNSEQ3.ASM" shn_3_head_hold2_anim \
    --animation "$ORIG/SHNSEQ3.ASM" shn_3_head_hold_anim \
    --animation "$ORIG/SHNSEQ3.ASM" shn_fstein_anim \
    --animation "$ORIG/SHNSEQ3.ASM" shn_knee_fstein_anim \
    --animation "$ORIG/SHNSEQ4.ASM" shn_3_head_held_stand_anim \
    --animation "$ORIG/SHNSEQ4.ASM" shn_4_block_anim \
    --animation "$ORIG/SHNSEQ4.ASM" shn_fall_back_anim \
    --animation "$ORIG/UNDSEQ1.ASM" und_run2_anim \
    --animation "$ORIG/UNDSEQ1.ASM" und_stand2_anim \
    --animation "$ORIG/UNDSEQ1.ASM" und_stand4_anim \
    --animation "$ORIG/UNDSEQ1.ASM" und_torso2_anim \
    --animation "$ORIG/UNDSEQ1.ASM" und_torso4_anim \
    --animation "$ORIG/UNDSEQ2.ASM" und_2_butt_anim \
    --animation "$ORIG/UNDSEQ2.ASM" und_2_butts_anim \
    --animation "$ORIG/UNDSEQ2.ASM" und_2_kick_anim \
    --animation "$ORIG/UNDSEQ2.ASM" und_2_knee_anim \
    --animation "$ORIG/UNDSEQ2.ASM" und_2_lbowdrop_anim \
    --animation "$ORIG/UNDSEQ2.ASM" und_2_punch_anim \
    --animation "$ORIG/UNDSEQ2.ASM" und_2_raise_arm_anim \
    --animation "$ORIG/UNDSEQ2.ASM" und_2_stomp_anim \
    --animation "$ORIG/UNDSEQ2.ASM" und_4_block_anim \
    --animation "$ORIG/UNDSEQ2.ASM" und_4_butt_anim \
    --animation "$ORIG/UNDSEQ2.ASM" und_4_butts_anim \
    --animation "$ORIG/UNDSEQ2.ASM" und_4_kick_anim \
    --animation "$ORIG/UNDSEQ2.ASM" und_4_knee_anim \
    --animation "$ORIG/UNDSEQ2.ASM" und_4_lbowdrop_anim \
    --animation "$ORIG/UNDSEQ2.ASM" und_4_pin2_anim \
    --animation "$ORIG/UNDSEQ2.ASM" und_4_punch_anim \
    --animation "$ORIG/UNDSEQ2.ASM" und_4_push_anim \
    --animation "$ORIG/UNDSEQ2.ASM" und_4_raise_arm_anim \
    --animation "$ORIG/UNDSEQ2.ASM" und_4_stomp_anim \
    --animation "$ORIG/UNDSEQ2.ASM" und_4_uppercut_anim \
    --animation "$ORIG/UNDSEQ2.ASM" und_fall_back_anim \
    --animation "$ORIG/UNDSEQ2.ASM" und_flying_kick_anim \
    --animation "$ORIG/UNDSEQ2.ASM" und_tbukl_butt_drop_anim \
    --animation "$ORIG/UNDSEQ3.ASM" und_3_head_held_stand_anim \
    --animation "$ORIG/UNDSEQ3.ASM" und_3_head_hold2_anim \
    --animation "$ORIG/UNDSEQ3.ASM" und_3_head_hold_anim \
    --animation "$ORIG/UNDSEQ3.ASM" und_climb_down_anim \
    --animation "$ORIG/UNDSEQ3.ASM" und_tombstone_smash_anim \
    --animation "$ORIG/YOKSEQ1.ASM" yok_run2_anim \
    --animation "$ORIG/YOKSEQ1.ASM" yok_stand2_anim \
    --animation "$ORIG/YOKSEQ1.ASM" yok_stand4_anim \
    --animation "$ORIG/YOKSEQ1.ASM" yok_torso2_anim \
    --animation "$ORIG/YOKSEQ1.ASM" yok_torso4_anim \
    --animation "$ORIG/YOKSEQ2.ASM" yok_2_gut_push_anim \
    --animation "$ORIG/YOKSEQ2.ASM" yok_2_jabs_anim \
    --animation "$ORIG/YOKSEQ2.ASM" yok_2_kick_anim \
    --animation "$ORIG/YOKSEQ2.ASM" yok_2_knee_anim \
    --animation "$ORIG/YOKSEQ2.ASM" yok_2_lbowdrop_anim \
    --animation "$ORIG/YOKSEQ2.ASM" yok_2_pin_anim \
    --animation "$ORIG/YOKSEQ2.ASM" yok_2_punch_anim \
    --animation "$ORIG/YOKSEQ2.ASM" yok_2_raise_arm_anim \
    --animation "$ORIG/YOKSEQ2.ASM" yok_2_run_slap_anim \
    --animation "$ORIG/YOKSEQ2.ASM" yok_2_slap2_anim \
    --animation "$ORIG/YOKSEQ2.ASM" yok_2_stomp_anim \
    --animation "$ORIG/YOKSEQ2.ASM" yok_4_gut_push_anim \
    --animation "$ORIG/YOKSEQ2.ASM" yok_4_jabs_anim \
    --animation "$ORIG/YOKSEQ2.ASM" yok_4_kick_anim \
    --animation "$ORIG/YOKSEQ2.ASM" yok_4_knee_anim \
    --animation "$ORIG/YOKSEQ2.ASM" yok_4_lbowdrop_anim \
    --animation "$ORIG/YOKSEQ2.ASM" yok_4_pin_anim \
    --animation "$ORIG/YOKSEQ2.ASM" yok_4_punch_anim \
    --animation "$ORIG/YOKSEQ2.ASM" yok_4_push_anim \
    --animation "$ORIG/YOKSEQ2.ASM" yok_4_raise_arm_anim \
    --animation "$ORIG/YOKSEQ2.ASM" yok_4_run_slap_anim \
    --animation "$ORIG/YOKSEQ2.ASM" yok_4_slap2_anim \
    --animation "$ORIG/YOKSEQ2.ASM" yok_4_stomp_anim \
    --animation "$ORIG/YOKSEQ2.ASM" yok_4_uppercut_anim \
    --animation "$ORIG/YOKSEQ2.ASM" yok_climb_down_anim \
    --animation "$ORIG/YOKSEQ2.ASM" yok_tbukl_buttdrop_anim \
    --animation "$ORIG/YOKSEQ3.ASM" yok_2_salt_anim \
    --animation "$ORIG/YOKSEQ3.ASM" yok_3_head_held_stand_anim \
    --animation "$ORIG/YOKSEQ3.ASM" yok_3_head_hold2_anim \
    --animation "$ORIG/YOKSEQ3.ASM" yok_3_head_hold_anim \
    --animation "$ORIG/YOKSEQ3.ASM" yok_4_salt_anim \
    --animation "$ORIG/YOKSEQ3.ASM" yok_heldheadbutt_rpt_anim \
    --animation "$ORIG/YOKSEQ3.ASM" yok_scissor_anim \
    --animation "$ORIG/YOKSEQ4.ASM" yok_4_block_anim \
    --animation "$ORIG/YOKSEQ4.ASM" yok_fall_back_anim \
    --animation "$ORIG/RZRSEQ1.ASM" rzr_run2_anim \
    --animation "$ORIG/RZRSEQ1.ASM" rzr_stand2_anim \
    --animation "$ORIG/RZRSEQ1.ASM" rzr_stand4_anim \
    --animation "$ORIG/RZRSEQ1.ASM" rzr_torso2_anim \
    --animation "$ORIG/RZRSEQ1.ASM" rzr_torso4_anim \
    --animation "$ORIG/RZRSEQ2.ASM" rzr_2_butt_anim \
    --animation "$ORIG/RZRSEQ2.ASM" rzr_2_grabfling_anim \
    --animation "$ORIG/RZRSEQ2.ASM" rzr_2_ground_punch_anim \
    --animation "$ORIG/RZRSEQ2.ASM" rzr_2_kick_anim \
    --animation "$ORIG/RZRSEQ2.ASM" rzr_2_knee_anim \
    --animation "$ORIG/RZRSEQ2.ASM" rzr_2_pin_anim \
    --animation "$ORIG/RZRSEQ2.ASM" rzr_2_pummel_anim \
    --animation "$ORIG/RZRSEQ2.ASM" rzr_2_punch_anim \
    --animation "$ORIG/RZRSEQ2.ASM" rzr_2_raise_arm_anim \
    --animation "$ORIG/RZRSEQ2.ASM" rzr_2_stomp_anim \
    --animation "$ORIG/RZRSEQ2.ASM" rzr_2_super_kick_anim \
    --animation "$ORIG/RZRSEQ2.ASM" rzr_3_dslash_anim \
    --animation "$ORIG/RZRSEQ2.ASM" rzr_3_uslash_anim \
    --animation "$ORIG/RZRSEQ2.ASM" rzr_4_bigboot_anim \
    --animation "$ORIG/RZRSEQ2.ASM" rzr_4_butt_anim \
    --animation "$ORIG/RZRSEQ2.ASM" rzr_4_grabfling_anim \
    --animation "$ORIG/RZRSEQ2.ASM" rzr_4_ground_punch_anim \
    --animation "$ORIG/RZRSEQ2.ASM" rzr_4_kick2_anim \
    --animation "$ORIG/RZRSEQ2.ASM" rzr_4_kick_anim \
    --animation "$ORIG/RZRSEQ2.ASM" rzr_4_knee_anim \
    --animation "$ORIG/RZRSEQ2.ASM" rzr_4_knee_fall_anim \
    --animation "$ORIG/RZRSEQ2.ASM" rzr_4_pin_anim \
    --animation "$ORIG/RZRSEQ2.ASM" rzr_4_pummel_anim \
    --animation "$ORIG/RZRSEQ2.ASM" rzr_4_punch_anim \
    --animation "$ORIG/RZRSEQ2.ASM" rzr_4_push_anim \
    --animation "$ORIG/RZRSEQ2.ASM" rzr_4_raise_arm_anim \
    --animation "$ORIG/RZRSEQ2.ASM" rzr_4_stomp_anim \
    --animation "$ORIG/RZRSEQ2.ASM" rzr_4_super_kick_anim \
    --animation "$ORIG/RZRSEQ2.ASM" rzr_4_uprcut_anim \
    --animation "$ORIG/RZRSEQ2.ASM" rzr_combo_kick_anim \
    --animation "$ORIG/RZRSEQ2.ASM" rzr_combo_punch_anim \
    --animation "$ORIG/RZRSEQ2.ASM" rzr_flying_elbow_anim \
    --animation "$ORIG/RZRSEQ2.ASM" rzr_flying_kick_anim \
    --animation "$ORIG/RZRSEQ2.ASM" rzr_kick_TB_anim \
    --animation "$ORIG/RZRSEQ2.ASM" rzr_tbukl_elbow_anim \
    --animation "$ORIG/RZRSEQ3.ASM" rzr_2_hair_pickup_anim \
    --animation "$ORIG/RZRSEQ3.ASM" rzr_2_hiptoss2_anim \
    --animation "$ORIG/RZRSEQ3.ASM" rzr_2_hiptoss_anim \
    --animation "$ORIG/RZRSEQ3.ASM" rzr_3_fake_hold_anim \
    --animation "$ORIG/RZRSEQ3.ASM" rzr_3_head_held_stand_anim \
    --animation "$ORIG/RZRSEQ3.ASM" rzr_3_head_hold2_anim \
    --animation "$ORIG/RZRSEQ3.ASM" rzr_3_head_hold_anim \
    --animation "$ORIG/RZRSEQ3.ASM" rzr_3_pile_driver_anim \
    --animation "$ORIG/RZRSEQ3.ASM" rzr_4_hair_pickup_anim \
    --animation "$ORIG/RZRSEQ3.ASM" rzr_4_hiptoss2_anim \
    --animation "$ORIG/RZRSEQ3.ASM" rzr_4_hiptoss_anim \
    --animation "$ORIG/RZRSEQ3.ASM" rzr_climb_down_anim \
    --animation "$ORIG/RZRSEQ3.ASM" rzr_dslashes_to_head_anim \
    --animation "$ORIG/RZRSEQ3.ASM" rzr_razors_edge_anim \
    --animation "$ORIG/RZRSEQ3.ASM" rzr_repeat_slash_anim \
    --animation "$ORIG/RZRSEQ3.ASM" rzr_rugshake_anim \
    --animation "$ORIG/RZRSEQ3.ASM" rzr_sliding_rug_anim \
    --animation "$ORIG/RZRSEQ3.ASM" rzr_uslashes_to_head_anim \
    --animation "$ORIG/RZRSEQ4.ASM" rzr_2_block_anim \
    --animation "$ORIG/RZRSEQ4.ASM" rzr_4_block_anim \
    --animation "$ORIG/RZRSEQ4.ASM" rzr_fall_back_anim \
    --out "$ROOT/src/generated/anim_programs.c"
if [ ! -f "$ORIG/IMG/BRET.LOD" ]; then
    sh "$ROOT/scripts/fetch_original.sh"
fi
# Per-frame geometry for the hurt box, across every wrestler now driven by
# a program. A program-driven wrestler has no wm_visual_sequence to collect
# frames from, so the generated program file is a source here too.
python3 "$ROOT/tools/bret_geometry_bundle.py" \
    --lod "$ORIG/IMG/BRET.LOD" \
    --lod "$ORIG/IMG/RAZOR.LOD" \
    --lod "$ORIG/IMG/TAKER.LOD" \
    --lod "$ORIG/IMG/YOKO.LOD" \
    --lod "$ORIG/IMG/SHAWN.LOD" \
    --lod "$ORIG/IMG/BAM.LOD" \
    --lod "$ORIG/IMG/DOINK.LOD" \
    --lod "$ORIG/IMG/LEX.LOD" \
    --img-dir "$ORIG/IMG" \
    --visual-source "$ROOT/src/generated/bret_visuals.c" \
    --visual-source "$ROOT/src/generated/bret_attacks.c" \
    --visual-source "$ROOT/src/generated/bret_defense.c" \
    --visual-source "$ROOT/src/generated/bret_grapple.c" \
    --visual-source "$ROOT/src/generated/anim_programs.c" \
    --visual-source "$ROOT/src/generated/puppet_tables.c" \
    --out "$ROOT/src/generated/frame_geometry.c"
python3 "$ROOT/tools/select_source.py" \
    --source "$ORIG/SELECT.ASM" \
    --out "$ROOT/src/generated/select_tables.c"
python3 "$ROOT/tools/attract_sequence.py" \
    --source "$ORIG/ATTRACT.ASM" \
    --out "$ROOT/src/generated/attract_sequence.c"
python3 "$ROOT/tools/port_manifest.py" \
    --manifest "$ROOT/port/translation_manifest.json" \
    --out-c "$ROOT/src/generated/port_status.c" \
    --out-md "$ROOT/docs/PORT_COVERAGE.md" \
    --source-root "$ORIG"
