/*
 * JJXM.H's opponent-mode move tables, and Doink routed through his own
 * six of them (DOINK.ASM:1881, :1983, :2131, :2229, :2444, :2580).
 *
 * What these replace is worth stating plainly, because it looked
 * finished. Each of the six dispatchers answered an attack button with
 * one hand-written approximation -- "is he on the ground and am I
 * close" -- which matches the two COMMON rows of a 22-row table and
 * nothing else. So Doink's super kick was literally his light kick
 * (`super_kick(){basic_kick();}`); his big boot against a running or
 * bouncing opponent did not exist; the turnbuckle spin kick against an
 * INAIR2 one did not exist; his entire running repertoire -- flying
 * clothesline, belly flop, running stomp -- did not exist, because
 * mode_running had a single label for kick and a call to the standing
 * punch for punch.
 *
 * The tables are generated by tools/wljjxm.py, so these tests check the
 * MACHINE and the WIRING rather than re-copying 1100 rows that a
 * generator already reads.
 */
#include <assert.h>
#include <stdio.h>
#include <string.h>

#include "wm_arcade_jjxm.h"
#include "wm_arcade_doink.h"
#include "wmania_ring_geometry.h"

/* ---- the tables themselves ------------------------------------- */

static void test_every_table_is_well_formed(void) {
    size_t i, j;
    size_t rows = 0;
    assert(wm_jjxm_table_count == 50);
    for (i = 0; i < wm_jjxm_table_count; ++i) {
        const wm_jjxm_table_t *t = &wm_jjxm_tables[i];
        assert(t->wrestler && t->file && t->section);
        assert(t->entry_count > 0);
        assert(t->target_count > 0);
        /* Every table in the game is the same 22 modes. */
        assert(t->row_count == 22);
        rows += t->row_count;
        for (j = 0; j < t->row_count; ++j) {
            const wm_jjxm_row_t *r = &t->rows[j];
            assert(r->less < t->target_count);
            assert(r->more < t->target_count);
            /* An unconditional row carries -1 in BOTH thresholds and
               names the same target either side. */
            if (r->dx < 0) { assert(r->dz < 0); assert(r->less == r->more); }
            else assert(r->dz >= 0);
        }
    }
    assert(rows == 1100);
}

/*
 * `cmpi DX,a1 / jrgt MORE` on a TMS34010 computes a1-DX and branches on
 * STRICTLY GREATER, so DX itself belongs to the near arm. An
 * approximation reaches for `<` and is wrong by exactly one pixel on
 * each axis -- which is the sort of thing that never shows up in play
 * and never stops being wrong.
 */
static void test_the_threshold_is_a_closed_interval(void) {
    const wm_jjxm_table_t *t = wm_jjxm_find("DOINK", "mode_normal", "#punch");
    assert(t);
    /* MODE_NORMAL row: 50, 45, #punch_hdbutt / #punch_punch. */
    assert(strcmp(wm_jjxm_select(t, 0, 50, 45), "#punch_hdbutt") == 0);
    assert(strcmp(wm_jjxm_select(t, 0, 51, 45), "#punch_punch") == 0);
    assert(strcmp(wm_jjxm_select(t, 0, 50, 46), "#punch_punch") == 0);
    /* And the unconditional row ignores distance entirely. */
    assert(strcmp(wm_jjxm_select(t, 11 /* CLIMBTURNBKL */, 0, 0),
                  "#punch_punch") == 0);
    assert(strcmp(wm_jjxm_select(t, 11, 9999, 9999), "#punch_punch") == 0);
}

/* JJXM_END is `LOCKUP / rets`: a mode nobody wrote a row for answers
   the button with nothing at all. MODE_CHOKING is that mode, in all
   fifty tables. */
static void test_a_mode_with_no_row_does_nothing(void) {
    size_t i;
    for (i = 0; i < wm_jjxm_table_count; ++i)
        assert(wm_jjxm_select(&wm_jjxm_tables[i], 25 /* CHOKING */, 0, 0)
               == NULL);
}

static void test_find_is_scoped_to_its_section(void) {
    const wm_jjxm_table_t *normal =
        wm_jjxm_find("DOINK", "mode_normal", "#super_punch");
    const wm_jjxm_table_t *running =
        wm_jjxm_find("DOINK", "mode_running", "#super_punch");
    assert(normal && running && normal != running);
    /* Local labels are scoped to the enclosing mode_* label, so the two
       sections' #punch_lbowdrop are different routines -- one is the
       standing elbow drop, the other is the belly flop. */
    assert(strcmp(wm_jjxm_select(running, 0, 0, 0), "#punch_clothesline") == 0);
    assert(wm_jjxm_find("DOINK", "mode_normal", "#no_such_label") == NULL);
    assert(wm_jjxm_find("ADAMBOMB", "mode_normal", "#punch") == NULL);
}

/* ---- Doink, driven through move_doink -------------------------- */

static const char *last_label;
static int label_calls;
static void cap_anim(wm_arcade_actor_t *a, const char *l, void *u) {
    (void)a; (void)u; last_label = l; ++label_calls;
}

static wm_arcade_doink_callbacks_t cbs(void) {
    wm_arcade_doink_callbacks_t c;
    memset(&c, 0, sizeof c);
    c.change_anim_label = cap_anim;
    return c;
}

static void actors(wm_arcade_actor_t *me, wm_arcade_actor_t *him) {
    memset(me, 0, sizeof *me);
    memset(him, 0, sizeof *him);
    me->active = him->active = 1;
    me->wrestler_num = WM_ROSTER_DOINK;
    me->player_mode = WM_PMODE_NORMAL;
    me->facing_dir = me->new_facing_dir = WM_MOVE_DOWN_RIGHT;
    me->x_int = WM_RING_X_MID;
    him->player_side = 1;
    him->player_mode = WM_PMODE_NORMAL;
    last_label = NULL;
    label_calls = 0;
}

/* `JJXM RUNNING, #skick_bigboot` and `JJXM INAIR2, #skick_TB` -- two
   rows with no distance test, which the old approximation could not
   express and so did not have. */
static void test_the_super_kick_is_not_the_light_kick(void) {
    wm_arcade_actor_t me, him;
    wm_arcade_doink_callbacks_t c = cbs();
    wm_arcade_doink_env_t e;
    memset(&e, 0, sizeof e);

    actors(&me, &him);
    me.but_val_down = WM_BTN_SKICK;
    him.player_mode = WM_PMODE_RUNNING;
    (void)wm_arcade_move_doink(&me, &him, &e, &c);
    assert(last_label && strcmp(last_label, "dnk_4_bigboot_anim") == 0);

    actors(&me, &him);
    me.but_val_down = WM_BTN_SKICK;
    him.player_mode = WM_PMODE_INAIR2;
    (void)wm_arcade_move_doink(&me, &him, &e, &c);
    assert(last_label && strcmp(last_label, "dnk_4_spin_kick_TB_anim") == 0);

    /* And the ordinary close row still reaches #skick_special, whose
       own stick test (STICK_VAL_CUR against NEW_FACING_DIR & 0Ch)
       picks the plain knee when the stick is not held toward him --
       so this did not trade one collapse for another. */
    actors(&me, &him);
    me.but_val_down = WM_BTN_SKICK;
    me.closest_xdist = 30; me.closest_zdist = 30;
    (void)wm_arcade_move_doink(&me, &him, &e, &c);
    assert(last_label && strcmp(last_label, "dnk_4_knee_anim") == 0);

    /* Held toward him, the same row is the knee-fall. */
    actors(&me, &him);
    me.but_val_down = WM_BTN_SKICK;
    me.closest_xdist = 30; me.closest_zdist = 30;
    me.stick_val_cur = (uint16_t)(me.new_facing_dir & 0x0c);
    (void)wm_arcade_move_doink(&me, &him, &e, &c);
    assert(last_label && strcmp(last_label, "dnk_4_knee_fall_anim") == 0);
}

/* The mode_running punch group: DOINK.ASM:2444. */
static void test_the_running_punch_is_a_clothesline(void) {
    wm_arcade_actor_t me, him;
    wm_arcade_doink_callbacks_t c = cbs();
    wm_arcade_doink_env_t e;
    memset(&e, 0, sizeof e);

    actors(&me, &him);
    me.player_mode = WM_PMODE_RUNNING;
    me.usr_var1 = 1;               /* skip the bounce_off_ropes arm */
    me.move_dir = WM_MOVE_RIGHT;
    me.but_val_down = WM_BTN_PUNCH;
    (void)wm_arcade_move_doink(&me, &him, &e, &c);
    assert(last_label && strcmp(last_label, "dnk_fly_cline_anim") == 0);
    assert(me.player_mode == WM_PMODE_INAIR);
    assert(me.run_time == 0);

    /* Against a man on the mat, the same button is the belly flop --
       and the table's 176/176 split has that same body either side of
       it, because #punch_lbowdrop and #punch_bellyflop are two labels
       on one instruction. */
    actors(&me, &him);
    me.player_mode = WM_PMODE_RUNNING;
    me.usr_var1 = 1;
    me.move_dir = WM_MOVE_RIGHT;
    me.but_val_down = WM_BTN_PUNCH;
    him.player_mode = WM_PMODE_ONGROUND;
    me.closest_xdist = 300; me.closest_zdist = 300;   /* past the split */
    (void)wm_arcade_move_doink(&me, &him, &e, &c);
    assert(last_label && strcmp(last_label, "dnk_belly_anim") == 0);
}

/* "Only allow clothesline if near centre of ring, and running toward
   opponent" -- both gates, neither of which the port had. */
static void test_the_clothesline_gates(void) {
    wm_arcade_actor_t me, him;
    wm_arcade_doink_callbacks_t c = cbs();
    wm_arcade_doink_env_t e;
    memset(&e, 0, sizeof e);

    /* Too far right while running right. */
    actors(&me, &him);
    me.player_mode = WM_PMODE_RUNNING;
    me.usr_var1 = 1;
    me.move_dir = WM_MOVE_RIGHT;
    me.x_int = WM_RING_X_MID + 0x70;
    me.but_val_down = WM_BTN_PUNCH;
    (void)wm_arcade_move_doink(&me, &him, &e, &c);
    assert(label_calls == 0);

    /* Running LEFT while facing right: running away from him. */
    actors(&me, &him);
    me.player_mode = WM_PMODE_RUNNING;
    me.usr_var1 = 1;
    me.move_dir = WM_MOVE_LEFT;
    me.new_facing_dir = WM_MOVE_DOWN_RIGHT;   /* 10 -> MOVE_LEFT_BIT */
    me.but_val_down = WM_BTN_PUNCH;
    (void)wm_arcade_move_doink(&me, &him, &e, &c);
    assert(label_calls == 0);

    /* Running left while facing left is fine. */
    actors(&me, &him);
    me.player_mode = WM_PMODE_RUNNING;
    me.usr_var1 = 1;
    me.move_dir = WM_MOVE_LEFT;
    me.facing_dir = me.new_facing_dir = WM_MOVE_DOWN_LEFT;  /* 6 */
    me.but_val_down = WM_BTN_PUNCH;
    (void)wm_arcade_move_doink(&me, &him, &e, &c);
    assert(last_label && strcmp(last_label, "dnk_fly_cline_anim") == 0);
}

/* The mode_running kick group: DOINK.ASM:2580. */
static void test_the_running_kick_stomps_a_downed_man(void) {
    wm_arcade_actor_t me, him;
    wm_arcade_doink_callbacks_t c = cbs();
    wm_arcade_doink_env_t e;
    memset(&e, 0, sizeof e);

    actors(&me, &him);
    me.player_mode = WM_PMODE_RUNNING;
    me.usr_var1 = 1;
    me.move_dir = WM_MOVE_RIGHT;
    me.but_val_down = WM_BTN_KICK;
    him.player_mode = WM_PMODE_ONGROUND;
    (void)wm_arcade_move_doink(&me, &him, &e, &c);
    assert(last_label && strcmp(last_label, "dnk_belly_anim") == 0);
    assert(me.run_time == 0);

    /* A standing opponent is the flying kick, which is the one member
       of this group that leaves RUN_TIME alone. */
    actors(&me, &him);
    me.player_mode = WM_PMODE_RUNNING;
    me.usr_var1 = 1;
    me.move_dir = WM_MOVE_RIGHT;
    me.but_val_down = WM_BTN_KICK;
    (void)wm_arcade_move_doink(&me, &him, &e, &c);
    assert(last_label && strcmp(last_label, "dnk_flying_kick_anim") == 0);
    assert(me.run_time == 1);
}

/* `JJXM HEADHELD, do_pile` -- a target in another section entirely,
   reachable only when a THIRD wrestler attacks a man someone else is
   holding, and gated on Doink's own repeated-uppercut flag. */
static void test_the_headheld_row_reaches_do_pile(void) {
    wm_arcade_actor_t me, him;
    wm_arcade_doink_callbacks_t c = cbs();
    wm_arcade_doink_env_t e;
    memset(&e, 0, sizeof e);

    actors(&me, &him);
    me.but_val_down = WM_BTN_SPUNCH;
    him.player_mode = WM_PMODE_HEADHELD;
    me.usr_var2 = 0;
    (void)wm_arcade_move_doink(&me, &him, &e, &c);
    assert(label_calls == 0);          /* `move USR_VAR2,a0 / jrz #z` */

    actors(&me, &him);
    me.but_val_down = WM_BTN_SPUNCH;
    him.player_mode = WM_PMODE_HEADHELD;
    me.usr_var2 = 1;
    me.stick_val_cur = WM_MOVE_DOWN;
    (void)wm_arcade_move_doink(&me, &him, &e, &c);
    assert(last_label && strcmp(last_label, "dnk_3_pile_driver_anim") == 0);
}

int main(void) {
    test_every_table_is_well_formed();
    test_the_threshold_is_a_closed_interval();
    test_a_mode_with_no_row_does_nothing();
    test_find_is_scoped_to_its_section();
    test_the_super_kick_is_not_the_light_kick();
    test_the_running_punch_is_a_clothesline();
    test_the_clothesline_gates();
    test_the_running_kick_stomps_a_downed_man();
    test_the_headheld_row_reaches_do_pile();
    printf("jjxm: ok\n");
    return 0;
}
