#!/usr/bin/env python3
from pathlib import Path
import sys
repo=Path(sys.argv[1]); p=repo/'src/fix39/wm_fix39_runtime.c'; t=p.read_text()
# Target-offset table is already generated by the CE pass, but the live runtime
# now calls it directly for source-local ANI_CODE helpers.
inc='#include "wm_arcade_target_offsets.h"\n'
if inc not in t:
    anchor='#include "wm_arcade_source_animation_catalog.h"\n'
    if anchor not in t: raise SystemExit('target-offset include anchor missing')
    t=t.replace(anchor,anchor+inc,1)
# Per-actor source PCNT history for fling/hiptoss/special delays.
field='    int32_t native_opp_xvel[WM_FIX39_ACTOR_COUNT];\n'
extra_fields='''    uint32_t native_last_fling[WM_FIX39_ACTOR_COUNT];\n    uint32_t native_last_hiptoss[WM_FIX39_ACTOR_COUNT];\n    uint32_t native_last_skick[WM_FIX39_ACTOR_COUNT];\n    uint32_t native_last_spunch[WM_FIX39_ACTOR_COUNT];\n    int32_t native_close_the_door;\n'''
if 'native_last_fling[WM_FIX39_ACTOR_COUNT]' not in t:
    if field not in t: raise SystemExit('native state field anchor missing')
    t=t.replace(field,field+extra_fields,1)
anchor='static void source_anim_code(wm_arcade_actor_t *a,const char *label,void *user)\n'
if anchor not in t: raise SystemExit('source_anim_code anchor missing')
if 'source_native_full_check_roll' not in t:
    pos=t.find(anchor)
    h=r'''/* Combat2DH: complete the remaining source-contained ANI_CODE state helpers.
 * These translations are constrained to bodies present in the supplied Midway
 * ASM payload. External-only audit/audio/effect symbols are left to their
 * existing event service rather than invented. */
static void source_native_status(wm_arcade_actor_t *a,int yes)
{
    if(!a)return;
    a->anim_mode&=(uint16_t)~WM_ARCADE_MODE_STATUS;
    if(yes)a->anim_mode|=WM_ARCADE_MODE_STATUS;
}
static void source_native_full_check_roll(wm_arcade_actor_t *a)
{
    if(!a)return;
    source_native_status(a,0);
    if(a->z_int>(WM_RING_Z_CENTER+20))return;
    a->stick_val_cur|=WM_MOVE_DOWN;
    a->z_vel=0x18000; /* WRESTLE2 do_roll MOVE_DOWN source value. */
    source_native_status(a,1);
}
static void source_native_full_delay(wm_arcade_actor_t *a,uint32_t *stamp,uint32_t ticks)
{
    uint32_t old,now;int i=actor_index(a);if(!a||i<0)return;
    old=stamp[i];now=g.status.pcnt;stamp[i]=now;source_native_status(a,(uint32_t)(now-old)<ticks);
}
static void source_native_full_elbow_tgt2(wm_arcade_actor_t *a)
{
    wm_arcade_actor_t *o=source_native_opp(a);int area;int16_t x,y,z;if(!a||!o)return;
    area=(((a->facing_dir^o->facing_dir)&(WM_MOVE_LEFT|WM_MOVE_RIGHT))==0)?0:2; /* head : groin */
    if(wm_source_target_offsets((uint16_t)o->player_mode,(uint8_t)o->wrestler_num,(uint16_t)area,&x,&y,&z)){
        a->tgt_xoff=x;a->tgt_yoff=y;a->tgt_zoff=z;
    }
}
static void source_native_full_set_target(wm_arcade_actor_t *a)
{
    wm_arcade_actor_t *o=source_native_opp(a);int area;int16_t x,y,z;if(!a||!o)return;
    if(a->closest_xdist<0x40)area=1; /* TGT_CHEST */
    else if(((a->obj_control^o->obj_control)&WM_OBJ_FLIPH)!=0)area=0; /* TGT_HEAD */
    else area=3; /* TGT_KNEES */
    if(wm_source_target_offsets((uint16_t)o->player_mode,(uint8_t)o->wrestler_num,(uint16_t)area,&x,&y,&z)){
        a->tgt_xoff=x;a->tgt_yoff=y;a->tgt_zoff=z;
    }
}
static void source_native_full_set_zvel(wm_arcade_actor_t *a)
{
    wm_arcade_actor_t *o=source_native_opp(a);int ticks;if(!a||!o)return;
    ticks=abs32(a->x_int-o->x_int)/7;if(ticks<=0){a->z_vel=0;return;}
    a->z_vel=((o->z_int-a->z_int)<<16)/ticks;
}
static void source_native_full_grnd_hit(wm_arcade_actor_t *a)
{
    static const char *hit[9]={"hrt_hitonground_anim","rzr_hitonground_anim","und_hitonground_anim","yok_hitonground_anim","shn_hitonground_anim","bam_hitonground_anim","dnk_hitonground_anim",0,"lex_hitonground_anim"};
    wm_arcade_actor_t *o=a?a->who_i_hit:0;int w;if(!a||!o)return;w=o->wrestler_num;
    if(w>=0&&w<=8&&hit[w])source_native_change_primary(o,hit[w]);
    if(a->wrestler_num!=2){a->z_fixed=o->z_fixed+(1<<16);a->z_int=a->z_fixed>>16;o->z_fixed-=2<<16;o->z_int=o->z_fixed>>16;}
}
static void source_native_full_set_new_position(wm_arcade_actor_t *a)
{
    static const int16_t pos[][4]={
      {WM_RING_X_CENTER,WM_RING_Z_CENTER,WM_MAT_Y,0},{WM_RING_TOP_LEFT,WM_RING_Z_CENTER,WM_MAT_Y,0},{WM_RING_TOP_RIGHT,WM_RING_Z_CENTER,WM_MAT_Y,0},
      {WM_RING_BOT_LEFT,WM_RING_BOT,WM_MAT_Y,0},{WM_RING_BOT_RIGHT,WM_RING_BOT,WM_MAT_Y,0},
      {675,1184,0,1},{1475,921,0,1},{965,683,0,1},{1253,656,0,1},{814,1648,0,1},{1415,1608,0,1},{1097,1648,0,1},{659,696,0,1},{528,1657,0,1},{1652,1615,0,1},{1709,699,0,1},{1791,1174,0,1},{1874,1548,0,1},
      {WM_RING_X_CENTER,WM_RING_Z_CENTER,WM_MAT_Y,0}};
    size_t i,chosen=(sizeof(pos)/sizeof(pos[0]))-1;int tl=(int)(g.camera.worldtlx_fp16>>16);if(!a)return;
    for(i=0;i+1<sizeof(pos)/sizeof(pos[0]);++i){if(pos[i][0]>=tl+25&&pos[i][0]<=tl+375){chosen=i;break;}}
    a->x_int=pos[chosen][0];a->z_int=pos[chosen][1];a->y_int=pos[chosen][2];a->ground_y=pos[chosen][2];a->in_ring=pos[chosen][3];
    a->x_fixed=a->x_int<<16;a->z_fixed=a->z_int<<16;a->y_fixed=a->y_int<<16;
}
static void source_native_full_set_speeds(wm_arcade_actor_t *a)
{
    int z;if(!a)return;a->x_vel=((1250+7-a->x_int)<<16)/16;z=a->z_int;if(z<((WM_RING_Z_CENTER+20+28)&0xfff)){z=((WM_RING_Z_CENTER+20+28)&0xfff);a->z_int=z;a->z_fixed=z<<16;}
    a->z_vel=((((WM_RING_Z_CENTER+20+28)&0xfff)-z)<<16)/16;
}
static void source_native_full_tbukl_confine(wm_arcade_actor_t *a)
{
    int i,enemy_out=0,enemy_alive=0;if(!a)return;
    if(a->wrestler_num==3){a->anim_mode&=(uint16_t)~WM_ARCADE_MODE_NOCONFINE;return;}
    for(i=0;i<(int)WM_FIX39_ACTOR_COUNT;i++){wm_arcade_actor_t *o=&g.actors[i];if(!o->active||o==a||o->player_side==a->player_side)continue;if(o->player_mode!=WM_PMODE_DEAD)enemy_alive=1;if(o->in_ring)enemy_out=1;}
    if(enemy_out){a->anim_mode|=WM_ARCADE_MODE_NOCONFINE;return;}
    a->anim_mode&=(uint16_t)~WM_ARCADE_MODE_NOCONFINE;
    if(a->in_ring){a->in_ring=0;a->ground_y=WM_MAT_Y;if(a->z_int<WM_RING_TOP)a->z_int=WM_RING_TOP;(void)enemy_alive;}
}
static void source_native_full_tgt_tbukl(wm_arcade_actor_t *a)
{
    const WmRingBoundarySeed *line;int x;if(!a)return;line=wm_ring_boundary_seed(a->x_int>WM_RING_X_CENTER?WM_RING_BOUNDARY_RIGHT_ROPE:WM_RING_BOUNDARY_LEFT_ROPE);
    x=wm_ring_calc_line_x(line,(int16_t)(WM_RING_Z_CENTER-16));a->tgt_xoff=x;a->tgt_zoff=WM_RING_Z_CENTER-16;a->tgt_yoff=WM_MAT_Y+80;
}
static void source_native_full_restore_pal(wm_arcade_actor_t *a){if(!a)return;a->obj_pal=a->my_pal;a->status_flags&=~WM_STATUS_TEMP_PAL;}
static void source_native_full_make_white(wm_arcade_actor_t *a){if(a)a->anim_mode&=(uint16_t)~(WM_ARCADE_MODE_INVISIBLE|WM_ARCADE_MODE_GHOST);}
static void source_native_full_close_door(wm_arcade_actor_t *a){(void)a;g.native_close_the_door=2;}
static void source_native_full_is_door_open(wm_arcade_actor_t *a){source_native_status(a,g.native_close_the_door!=0);}
static void source_native_full_effect(wm_arcade_actor_t *a,const char *label){source_anim_sound(a,label,0,0);}
'''
    t=t[:pos]+h+t[pos:]
needle='    if(!strcmp(label,"ck_flip")){source_native_ck_flip(a);return;}\n'
if 'if(!strcmp(label,"check_roll"))' not in t:
    if needle not in t: raise SystemExit('DG dispatch anchor missing')
    d=r'''    if(!strcmp(label,"check_roll")){source_native_full_check_roll(a);return;}
    if(!strcmp(label,"fling_delay")){source_native_full_delay(a,g.native_last_fling,3u*60u);return;}
    if(!strcmp(label,"hiptoss_delay")){source_native_full_delay(a,g.native_last_hiptoss,3u*60u);return;}
    if(!strcmp(label,"skick_delay")){source_native_full_delay(a,g.native_last_skick,2u*60u);return;}
    if(!strcmp(label,"spunch_delay")){source_native_full_delay(a,g.native_last_spunch,2u*60u);return;}
    if(!strcmp(label,"elbow_tgt2")){source_native_full_elbow_tgt2(a);return;}
    if(!strcmp(label,"set_target")){source_native_full_set_target(a);return;}
    if(!strcmp(label,"set_zvel")){source_native_full_set_zvel(a);return;}
    if(!strcmp(label,"grnd_hit")){source_native_full_grnd_hit(a);return;}
    if(!strcmp(label,"set_new_position")){source_native_full_set_new_position(a);return;}
    if(!strcmp(label,"set_speeds")){source_native_full_set_speeds(a);return;}
    if(!strcmp(label,"set_tbukl_confine")){source_native_full_tbukl_confine(a);return;}
    if(!strcmp(label,"tgt_tbukl")){source_native_full_tgt_tbukl(a);return;}
    if(!strcmp(label,"restore_pal")){source_native_full_restore_pal(a);return;}
    if(!strcmp(label,"make_white")||!strcmp(label,"make_black")){source_native_full_make_white(a);return;}
    if(!strcmp(label,"close_door")){source_native_full_close_door(a);return;}
    if(!strcmp(label,"is_door_open")){source_native_full_is_door_open(a);return;}
    if(!strcmp(label,"draw_ddt_name")||!strcmp(label,"win_announce")||!strcmp(label,"shake_all_ropes")||!strcmp(label,"start_smoke")||!strcmp(label,"start_sparks")||!strcmp(label,"set_pal")||!strcmp(label,"set_skeleton_pal")){source_native_full_effect(a,label);return;}
'''
    t=t.replace(needle,needle+d,1)
p.write_text(t)
print('Combat2DH source-contained ANI_CODE completion applied')
