#!/usr/bin/env python3
"""Recover exact historical source text surrounding reachable DRONE code seams.

Chunk 5f is intentionally a recovery/translation-input pass, not a semantic
shortcut.  It maps the exact command-5/EXGPC addresses generated by the same
DRONE.ASM image model back onto active historical source lines, producing a
reviewable body report for the next direct-C translation pass.
"""
from __future__ import annotations
import argparse
import re
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import fix39_drone_scripts as scripts  # type: ignore


def fail(msg: str) -> None:
    raise SystemExit(msg)


def strip_comment(s: str) -> str:
    return s.split(';', 1)[0].strip()


def service_labels(path: Path) -> list[str]:
    txt = path.read_text(encoding='utf-8', errors='replace')
    m = re.search(
        r'wm_fix39_drone_service_labels\[[^\]]+\]\s*=\s*\{(.*?)\};',
        txt, re.S)
    if not m:
        fail('generated service header missing service-label table')
    return re.findall(r'"([^"]+)"', m.group(1))


def active_address_map(source: Path):
    """Replay the generator's packed-data address model and retain line anchors."""
    lines = scripts.source_active_lines(source)
    labels: dict[str, int] = {}
    anchors: list[tuple[int, int]] = []  # (bit address, active-line index)
    bit = 0
    section_live = False

    def add_label(name: str) -> None:
        labels[scripts.symkey(name)] = bit

    for idx, raw in enumerate(lines):
        s = strip_comment(raw)
        if re.match(r'(?i)^\.(?:text|data)\b', s):
            section_live = True
            continue
        lab = scripts.ranges.is_label(raw)
        if lab is not None:
            add_label(lab)
            continue
        alias = scripts.address_equate(raw)
        if alias is not None:
            add_label(alias)
            continue
        subr_lab = scripts.subroutine_macro_label(raw)
        if subr_lab is not None:
            add_label(subr_lab)
            continue

        inline_lab, payload = scripts.inline_data_label(raw)
        if inline_lab is not None:
            add_label(inline_lab)
            raw_for_data = payload
        else:
            raw_for_data = raw

        d = scripts.directive(raw_for_data)
        packed = None if d is not None else scripts.packed_directive(raw_for_data)
        if d is None and packed is None:
            continue
        if not section_live:
            section_live = True
        anchors.append((bit, idx))
        if packed is not None:
            for kind, _expr in packed:
                bit += {'byte': 8, 'word': 16, 'long': 32}[kind]
        else:
            assert d is not None
            kind, vals = d
            bit += {'byte': 8, 'word': 16, 'long': 32}[kind] * len(vals)
    return lines, labels, anchors


def seam_addr(label: str, labels: dict[str, int]) -> tuple[int, str]:
    if '@EXGPC_' in label:
        base, off = label.rsplit('@EXGPC_', 1)
        key = scripts.symkey(base)
        if key not in labels:
            fail(f'EXGPC base label missing from active image: {base}')
        try:
            return labels[key] + int(off, 16), 'exgpc-inline'
        except ValueError:
            fail(f'invalid EXGPC offset: {label}')
    key = scripts.symkey(label)
    if key not in labels:
        fail(f'command-5 label missing from active image: {label}')
    return labels[key], 'call-code'


def anchor_for(addr: int, anchors: list[tuple[int, int]]) -> int | None:
    # Exact addresses normally land on a packed-data word.  If they point into
    # a data item, use the closest containing/prior directive as source anchor.
    prior = None
    for a, idx in anchors:
        if a > addr:
            break
        prior = idx
    return prior


def collect_source_window(lines: list[str], start: int, max_lines: int = 48) -> list[str]:
    out: list[str] = []
    began_code = False
    for raw in lines[start:start + max_lines]:
        s = strip_comment(raw)
        if not s:
            continue
        # Include the packed command/data anchor, then capture following
        # executable source until a clear routine/script boundary.
        is_data = scripts.directive(raw) is not None or scripts.packed_directive(raw) is not None
        # Boundary labels must be explicit here. ranges.is_label() intentionally
        # accepts Williams bare-label syntax, which can also resemble zero-operand
        # TMS instructions such as RETS.
        is_label = bool(re.match(r'^\s*#?[A-Za-z_][A-Za-z0-9_]*\s*:\s*$', strip_comment(raw))) or bool(re.match(r'^\s*#[A-Za-z_][A-Za-z0-9_]*\s*$', strip_comment(raw))) or scripts.subroutine_macro_label(raw) is not None
        if began_code and is_label:
            break
        if began_code and is_data:
            break
        out.append(raw.rstrip())
        if not is_data and not is_label and not re.match(r'(?i)^\.(?:text|data|even|def|ref)\b', s):
            began_code = True
        if began_code and re.search(r'(?i)\b(?:rets|retp|ret)\b|\bjruc\s+#?scplp\b', s):
            break
    return out


def extract(source: Path, services: Path, out: Path) -> tuple[int, int]:
    labels = service_labels(services)
    if not labels:
        fail('generated service registry is empty')
    lines, amap, anchors = active_address_map(source)
    report = [
        '# Fix39 V13e Chunk 5f — exact DRONE executable-body source recovery',
        '# Translation input only: no seam is marked executed by this report.',
        f'service_count={len(labels)}',
    ]
    extracted = 0
    unresolved = 0
    for label in labels:
        addr, kind = seam_addr(label, amap)
        idx = anchor_for(addr, anchors)
        if idx is None:
            report.append(f'body={label}|{kind}|addr=0x{addr:08x}|status=unresolved|lines=0')
            unresolved += 1
            continue
        body = collect_source_window(lines, idx)
        status = 'source-lines' if body else 'unresolved'
        report.append(f'body={label}|{kind}|addr=0x{addr:08x}|status={status}|lines={len(body)}')
        for line in body:
            report.append('  ' + line)
        if body:
            extracted += 1
        else:
            unresolved += 1
    report += [f'extracted={extracted}', f'unresolved={unresolved}']
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text('\n'.join(report) + '\n', encoding='utf-8')
    return extracted, unresolved


def self_test() -> None:
    with tempfile.TemporaryDirectory() as td:
        d = Path(td)
        src = d / 'DRONE.ASM'
        hdr = d / 'services.h'
        out = d / 'bodies.txt'
        src.write_text(
            '.text\n#foo\n.word 08009h\nmove a0,*a13(DRN_BUT)\nrets\n#bar\n.word 0,1\n',
            encoding='latin-1')
        hdr.write_text(
            '#define WM_FIX39_DRONE_SERVICE_COUNT 1\n'
            'static const char *const wm_fix39_drone_service_labels[1] = {\n'
            ' "foo@EXGPC_0000",\n};\n', encoding='utf-8')
        n, u = extract(src, hdr, out)
        txt = out.read_text(encoding='utf-8')
        assert n == 1 and u == 0
        assert 'body=foo@EXGPC_0000|exgpc-inline|' in txt
        assert 'move a0,*a13(DRN_BUT)' in txt
        assert 'rets' in txt
    print('Fix39 DRONE executable-body source recovery self-test: PASS')


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument('--source')
    ap.add_argument('--services')
    ap.add_argument('--out')
    ap.add_argument('--self-test', action='store_true')
    a = ap.parse_args()
    if a.self_test:
        self_test()
        return
    if not (a.source and a.services and a.out):
        fail('--source --services --out required')
    n, u = extract(Path(a.source), Path(a.services), Path(a.out))
    print(f'Recovered historical source windows for {n} DRONE executable seams; unresolved={u} -> {a.out}')


if __name__ == '__main__':
    main()
