#!/usr/bin/env python3
"""Every wrestler's `*_ani_init` -- the stand and torso animations he starts in.

Each wrestler's own .ASM has one of these and they are all the same
shape (BRET.ASM:1247, BAM.ASM:1203, and so on):

    bret_ani_init
        move  *a13(FACING_DIR),a0
        btst  PLAYER_RIGHT_BIT,a0
        jrnz  #p1
        movi  hrt_stand4_anim,a0 / calla change_anim1a   ; facing left
        movi  hrt_torso4_anim,a0 / calla change_anim2a
        ...
    #p1 movi  hrt_stand2_anim,a0 / calla change_anim1a   ; facing right
        movi  hrt_torso2_anim,a0 / calla change_anim2a

So: a primary animation and a SECONDARY one, chosen by facing. The `2`
suffix is the facing-right form and `4` the facing-left one, matching
the rest of the animation naming.

The secondary channel is the torso. Every wrestler has one and the port
only ever had it for Bret, so this is what the other seven need to get
one too.

Doink appears twice -- DNK.ASM and DOINK.ASM both define a
`dnk_ani_init` with identical labels -- and only one is linked.
"""
from __future__ import annotations
import argparse
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import wlanim  # noqa: E402
import port_coverage  # noqa: E402

INIT_RE = re.compile(r"^\s*SUBRP?\s+([a-z]+)_ani_init\s*$", re.I)
MOVI_RE = re.compile(r"^\s*movi\s+([a-z]+_(?:stand|torso)[24]_anim)\s*,\s*a0\s*$",
                     re.I)
CALL_RE = re.compile(r"^\s*calla\s+(change_anim[12]a?)\s*$", re.I)

# GAME.EQU roster order, as every other per-wrestler table in this port
# is indexed. Slot 7 is Adam Bomb, cut from the game.
ROSTER = ("hrt", "rzr", "und", "yok", "shn", "bam", "dnk", None, "lex")

# How far past the label to look. The routine is about thirty lines.
WINDOW = 40


def ani_inits() -> dict[str, dict]:
    """{prefix: {stand2, stand4, torso2, torso4, file, line}}."""
    # ADAM.ASM has an `adam_ani_init` with only half a body. Adam Bomb
    # was cut and WRESTLE.CMD does not link the file; one definition of
    # "linked", shared with tools/port_coverage.py.
    linked = port_coverage.linked_asm()
    out: dict[str, dict] = {}
    for path in sorted(wlanim.ORIG.glob("*.ASM")):
        if linked and path.name.upper() not in linked:
            continue
        lines = [wlanim.strip_comment(r)
                 for r in path.read_text(errors="replace").splitlines()]
        for i, line in enumerate(lines):
            m = INIT_RE.match(line)
            if not m:
                continue
            prefix = m.group(1).lower()
            found: dict[str, str] = {}
            pending: str | None = None
            for j in range(i + 1, min(i + 1 + WINDOW, len(lines))):
                mv = MOVI_RE.match(lines[j])
                if mv:
                    pending = mv.group(1)
                    continue
                cl = CALL_RE.match(lines[j])
                if cl and pending:
                    kind = "torso" if "torso" in pending else "stand"
                    facing = pending[-len("2_anim")]
                    channel = "2" if cl.group(1).startswith("change_anim2") \
                        else "1"
                    # A stand belongs to channel 1 and a torso to channel
                    # 2; if the source ever paired them the other way this
                    # would be the place to notice.
                    want = "2" if kind == "torso" else "1"
                    if channel != want:
                        raise ValueError(
                            "%s: %s goes to %s, expected channel %s"
                            % (path.name, pending, cl.group(1), want))
                    found["%s%s" % (kind, facing)] = pending
                    pending = None
            if len(found) != 4:
                raise ValueError("%s: %s_ani_init gave %s"
                                 % (path.name, prefix, sorted(found)))
            # Key on the ANIMATION prefix, not the routine's. They differ
            # for five of the eight -- bret_ani_init sets hrt_* frames,
            # taker_ani_init sets und_*, and so on -- and every other
            # per-wrestler table in this port is keyed on the animation
            # prefix.
            anim_prefix = found["stand2"].split("_", 1)[0]
            if anim_prefix in out and out[anim_prefix]["labels"] != found:
                raise ValueError("%s ani_init differs between files"
                                 % anim_prefix)
            out[anim_prefix] = {"labels": found, "routine": prefix,
                                "file": path.name, "line": i + 1}
    return out


def render_c() -> str:
    inits = ani_inits()
    out = [
        "/* Generated by tools/wlaniinit.py. Do not edit.",
        " *",
        " * Each wrestler's *_ani_init: the primary (stand) and SECONDARY",
        " * (torso) animation he starts in, one pair per facing. The `2`",
        " * form faces right and the `4` form faces left.",
        " */",
        '#include "wm/wrestler_backend.h"',
        "",
        "const wm_ani_init_row wm_ani_init_rows[WM_ANI_INIT_SLOTS] = {",
    ]
    for slot, prefix in enumerate(ROSTER):
        if prefix is None or prefix not in inits:
            out.append("    { NULL, NULL, NULL, NULL },"
                       "   /* %d Adam Bomb -- cut from the game */" % slot)
            continue
        lab = inits[prefix]["labels"]
        out.append('    { "%s", "%s", "%s", "%s" },   /* %d %s -- %s:%d */'
                   % (lab["stand2"], lab["stand4"], lab["torso2"],
                      lab["torso4"], slot, prefix,
                      inits[prefix]["file"], inits[prefix]["line"]))
    out.append("};")
    out.append("")
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out")
    ap.add_argument("--list", action="store_true")
    ns = ap.parse_args()
    inits = ani_inits()
    if ns.list:
        for prefix, info in sorted(inits.items()):
            print("%-4s %-18s %-14s:%-5d %s"
                  % (prefix, info["routine"] + "_ani_init", info["file"],
                     info["line"], sorted(info["labels"].values())))
        print("\n%d wrestlers" % len(inits))
        return 0
    text = render_c()
    if ns.out:
        pathlib.Path(ns.out).write_text(text)
        print("ani_init rows: %d wrestlers" % len(inits))
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
