#!/usr/bin/env python3
"""Extract the attract screens' own .string literals from ATTRACT.ASM.

The port already carries these screens' layout and timing, extracted and
correct -- copyright's FIRST_Y 110, X 200, LINE_STEP 12, its 9-then-10 line
split, aama's six lines. It carries the per-line LABELS too
(wm_attract_copyright_page1_labels, wm_attract_aama_labels), in the source's
own order. What it never carried is the TEXT those labels stand for, so a
screen with correct geometry and timing had no words to put in it.

WHY THE LABELS CANNOT BE RESOLVED BY NAME. Both routines number their lines
`#ln1`, `#ln2`, ... and `#` makes the label local to its routine. aama_message
has #ln1..#ln5 plus #ln2b; show_copyright has #ln1..#ln19. Resolving
"copyright_ln1" by searching ATTRACT.ASM for `#ln1` finds aama's first --
"AAMA PARENTAL ADVISORY" would appear at the top of the copyright page. So
extraction is scoped to each routine's extent, and the extent is bounded by
the next routine header or column-0 label, not by the next `.string`.
"""
from __future__ import annotations
import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
SRC = ROOT / "original" / "wwf-wrestlemania" / "ATTRACT.ASM"

# A routine header (` SUBR name` / ` SUBRP name`) or a column-0 label. Both end
# the routine above them: aama_message's extent ends at `do_the_grad_thang`,
# which is a bare label and not a SUBR, so matching SUBR alone would run the
# extent on into the next screen's strings.
BOUNDARY = re.compile(r"^\s*SUBRP?\s+([A-Za-z_]\w*)|^([A-Za-z_]\w*)\s*$")
# `#ln3   .string "(C) 1995 ASSIGNED TO ACCLAIM ENTERTAINMENT, INC.",0`
STRING = re.compile(r'^#(\w+)\s+\.string\s+"([^"]*)"\s*,\s*0\s*$')

# Which routine each port label group comes out of, and the port prefix its
# labels carry. The COUNT is asserted, not discovered: these arrays are
# declared with fixed sizes in wm/arcade/wmania_attract_data.h, and a source
# that stopped matching them is a finding rather than something to absorb.
GROUPS = [
    ("show_copyright", "copyright_", 19),
    ("aama_message", "aama_", 6),
]


def routine_extents(lines: list[str]) -> dict[str, tuple[int, int]]:
    """name -> (first_line, last_line), 1-based and inclusive."""
    starts: list[tuple[int, str]] = []
    for i, line in enumerate(lines):
        m = BOUNDARY.match(line)
        if m:
            starts.append((i + 1, m.group(1) or m.group(2)))
    out: dict[str, tuple[int, int]] = {}
    for idx, (ln, name) in enumerate(starts):
        end = starts[idx + 1][0] - 1 if idx + 1 < len(starts) else len(lines)
        # A name can repeat (ATTR.ASM-style duplicates inside one file do not
        # occur here, but a label reused later would silently win). Keep the
        # FIRST, and say so if a second turns up.
        out.setdefault(name, (ln, end))
    return out


def strings_in(lines: list[str], extent: tuple[int, int]) -> list[tuple[str, str, int]]:
    """(label, text, line_no) for each `#label .string "...",0` in extent."""
    lo, hi = extent
    found = []
    for n in range(lo, hi + 1):
        m = STRING.match(lines[n - 1])
        if m:
            found.append((m.group(1), m.group(2), n))
    return found


def c_quote(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def build() -> tuple[list[str], list[tuple[str, str, int]]]:
    lines = SRC.read_text(errors="replace").splitlines()
    extents = routine_extents(lines)
    rows: list[tuple[str, str, int]] = []
    for routine, prefix, expect in GROUPS:
        if routine not in extents:
            raise SystemExit(f"ATTRACT.ASM has no routine {routine}")
        got = strings_in(lines, extents[routine])
        if len(got) != expect:
            raise SystemExit(
                f"{routine} ({extents[routine][0]}-{extents[routine][1]}) has "
                f"{len(got)} .string lines, expected {expect}: "
                f"{[g[0] for g in got]}"
            )
        for label, text, line_no in got:
            rows.append((prefix + label, text, line_no))

    seen = {}
    for label, _text, line_no in rows:
        if label in seen:
            raise SystemExit(f"duplicate port label {label} (lines {seen[label]}, {line_no})")
        seen[label] = line_no

    out = [
        "/* Generated by tools/wlattracttext.py from ATTRACT.ASM. Do not edit.",
        "",
        "   The attract screens' own .string literals, keyed by the port label",
        "   wm/arcade/wmania_attract_data.h already uses for each line. Both",
        "   routines number their lines #ln1.. and `#` makes those local, so",
        "   the text is scoped to each routine's extent -- resolving by name",
        "   alone would put aama_message's first line atop the copyright page.",
        "*/",
        '#include "wm/arcade/wmania_attract_text.h"',
        "",
        "#include <string.h>",
        "",
        "static const wm_attract_text_entry s_entries[] = {",
    ]
    for label, text, line_no in rows:
        out.append(f"    {{ {c_quote(label)}, {c_quote(text)} }},"
                   f"  /* ATTRACT.ASM:{line_no} */")
    out += [
        "};",
        "",
        "const size_t wm_attract_text_count = "
        "sizeof s_entries / sizeof s_entries[0];",
        "",
        "const wm_attract_text_entry *wm_attract_text_entries(void) {",
        "    return s_entries;",
        "}",
        "",
        "const char *wm_attract_text(const char *label) {",
        "    size_t i;",
        "    if (!label) return NULL;",
        "    for (i = 0; i < wm_attract_text_count; ++i) {",
        "        if (strcmp(s_entries[i].label, label) == 0) {",
        "            return s_entries[i].text;",
        "        }",
        "    }",
        "    return NULL;",
        "}",
        "",
    ]
    return out, rows


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=pathlib.Path)
    ns = ap.parse_args()
    out, rows = build()
    text = "\n".join(out)
    if ns.out:
        ns.out.write_text(text)
        print(f"generated {len(rows)} attract text lines from ATTRACT.ASM")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
