#!/usr/bin/env python3
"""The colour tables CYCLE_TABLE walks, read out of HSTD.ASM.

UTIL.ASM:1174 CYCLE_TABLE animates a palette by writing a sliding
window of a fixed ROM word table into it, N colours at a time, every
few ticks. HSTD.ASM starts two of them on the high-score pages --
`hscore_colcyc` on BLUE and `hscore_colcyc2` on RUBYPAL, both
starting at colour 10, cycling 7, every 3 ticks.

The tables have a shape worth naming, because it is what makes the
cycle seamless and it is not written down anywhere in the source.
The loop restarts when the word it lands on is negative OR equal to
the table's FIRST word:

    ADDK  >10,A9
    MOVE  *A9,A0
    JRN   RESTUFF                 ; negative -> restart
    MOVE  *A13(PDATA+16),A1       ; the first word, saved on entry
    CMP   A0,A1
    jrne  #loop                   ; equal -> fall into RESTUFF

so the cycle length is the distance to the next repeat of word zero.
Everything past that point exists only so the seven-colour window
can be read from the last few positions without running off the end.
This reader works that length out rather than assuming it, and
refuses a table where word zero never repeats.
"""
import argparse
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import wlanim            # noqa: E402

SOURCE = "HSTD.ASM"

# HSTD.ASM:`movi [10,7],a8 / movi BLUE,a9 / movi COLTAB2,a10 / movk 3,a11`.
CYCLERS = [
    ("hscore_colcyc", "COLTAB2", "BLUE"),
    ("hscore_colcyc2", "COLTAB3", "RUBYPAL"),
]
START_COLOR = 10
CYCLE_COLORS = 7
CYCLE_TICKS = 3

_LABEL = re.compile(r"^([A-Za-z_]\w*)\s*$")
_WORD = re.compile(r"^\.word\s+(.+)$", re.I)
_HEX = re.compile(r"^0?([0-9A-Fa-f]+)[Hh]$")


class Refuse(Exception):
    """Something this reader does not understand. Never guessed at."""


def _lines():
    return (wlanim.ORIG / SOURCE).read_text(errors="replace").splitlines()


def read_table(label):
    lines = _lines()
    at = None
    for i, raw in enumerate(lines):
        line = wlanim.strip_comment(raw)
        m = _LABEL.match(line)
        if m and m.group(1) == label:
            at = i
            break
    if at is None:
        raise Refuse("no label %r" % label)

    words = []
    for raw in lines[at + 1:]:
        line = wlanim.strip_comment(raw)
        if not line:
            continue
        m = _WORD.match(line)
        if not m:
            break
        for tok in m.group(1).split(","):
            tok = tok.strip()
            h = _HEX.match(tok)
            if not h:
                raise Refuse("colour word %r in %s" % (tok, label))
            words.append(int(h.group(1), 16))
    if not words:
        raise Refuse("%s is empty" % label)

    # The cycle length: where word zero next appears.
    period = None
    for i in range(1, len(words)):
        if words[i] == words[0]:
            period = i
            break
    if period is None:
        raise Refuse("%s never repeats its first word, so CYCLE_TABLE "
                     "would never restart" % label)
    # And the tail has to be long enough for the read window.
    if len(words) - period < CYCLE_COLORS - 1:
        raise Refuse("%s has %d words past its period, too few for a "
                     "%d-colour window" % (label, len(words) - period,
                                           CYCLE_COLORS))
    # No word may be negative as a 16-bit value, or the JRN would
    # end the cycle early and the period above would be wrong.
    for i, w in enumerate(words[:period]):
        if w & 0x8000:
            raise Refuse("%s word %d has bit 15 set; CYCLE_TABLE's JRN "
                         "would restart there" % (label, i))
    return words, period


def emit_c(tables):
    o = []
    o.append("/* Generated by tools/wlcolcyc.py from HSTD.ASM."
             " Do not edit. */\n")
    o.append('#include "wm/arcade/wm_arcade_colcyc.h"\n\n')
    for (routine, label, pal), (words, period) in tables:
        o.append("/* %s: %d words, a %d-word cycle and a %d-word tail\n"
                 "   so the window can be read from the last position.\n"
                 "   Started by %s on %s. */\n"
                 % (label, len(words), period, len(words) - period,
                    routine, pal))
        o.append("static const uint16_t %s_words[] = {\n" % label.lower())
        for i in range(0, len(words), 8):
            o.append("    " + " ".join("0x%04x," % w
                                       for w in words[i:i + 8]) + "\n")
        o.append("};\n\n")
    o.append("const wm_colcyc_table_t wm_colcyc_tables[WM_COLCYC_TABLES] "
             "= {\n")
    for (routine, label, pal), (words, period) in tables:
        o.append('    { "%s", "%s", "%s", %s_words, %d, %d },\n'
                 % (routine, label, pal, label.lower(), len(words), period))
    o.append("};\n")
    return "".join(o)


def read_all():
    return [(c, read_table(c[1])) for c in CYCLERS]


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--out-c")
    ap.add_argument("--census", action="store_true")
    ns = ap.parse_args(argv)

    tables = read_all()
    if ns.census:
        for (routine, label, pal), (words, period) in tables:
            print("%-16s %-8s pal=%-8s %d words, period %d, tail %d"
                  % (routine, label, pal, len(words), period,
                     len(words) - period))
        return 0
    if ns.out_c:
        pathlib.Path(ns.out_c).write_text(emit_c(tables))
        print("wrote %d colour cycle table(s) -> %s" % (len(tables), ns.out_c))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
