#!/usr/bin/env python3
"""IMGPAL.ASM's palettes -- the colour data PAL.ASM hands to the hardware.

A palette in this game is one contiguous block: a count word, then that
many 16-bit colours.  Every routine in PAL.ASM reads it that way --

    move  *a1+,a14      ; # Colors
    move  a14,*a0+
    sll   32-9,a14      ; Remove any flags
    srl   32-9,a14      ; 9 bits needed for # colors

-- so the count word's top bits are flags and only its low nine are the
length.  pal_getf does the same thing when it sets up a transfer
(`move *a0+,a2  ;Get # colors in pal`).

Colours are RGB555 packed the way pal_fade unpacks them: blue in bits
0-4, green in 5-9, red in 10-14.  Bit 15 is not touched by any of the
fade code, which masks each channel to five bits and reassembles with
`sll 10` / `sll 5` / `or` -- so a palette that has bit 15 set loses it
the first time it is faded.  That is the arcade's behaviour and the data
is emitted here exactly as written, bit 15 included.
"""
from __future__ import annotations
import argparse
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import wlanim  # noqa: E402

SRC = wlanim.ORIG / "IMGPAL.ASM"

LABEL_RE = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*):\s*$")
WORD_RE = re.compile(r"^\s*\.word\s+(.+)$", re.I)

# PAL.ASM's 9-bit mask on the count word.
COUNT_MASK = 0x1FF


def _num(tok: str) -> int:
    tok = tok.strip()
    if not tok:
        raise ValueError("empty numeric token")
    if tok[-1] in "hH":
        return int(tok[:-1], 16)
    return int(tok, 10)


def palettes(path: pathlib.Path | None = None) -> dict[str, list[int]]:
    """Every labelled palette, as [count word] + colours.

    A label whose block does not hold exactly `count & 0x1FF` colours
    after the count word is refused rather than truncated or padded --
    that would mean this reader has misunderstood the layout.
    """
    path = path or SRC
    lines = [wlanim.strip_comment(r)
             for r in path.read_text(errors="replace").splitlines()]

    out: dict[str, list[int]] = {}
    name: str | None = None
    words: list[int] = []

    def close() -> None:
        nonlocal name, words
        if name is None:
            return
        if not words:
            raise ValueError(f"{name}: no data")
        want = words[0] & COUNT_MASK
        if len(words) - 1 != want:
            raise ValueError(
                f"{name}: count word {words[0]:#x} says {want} colours "
                f"but the block holds {len(words) - 1}")
        if name in out:
            raise ValueError(f"{name}: defined twice")
        out[name] = words
        name, words = None, []

    for line in lines:
        m = LABEL_RE.match(line)
        if m:
            close()
            name, words = m.group(1), []
            continue
        m = WORD_RE.match(line)
        if m:
            if name is None:
                continue        # data before the first label
            words += [_num(t) for t in m.group(1).split(",") if t.strip()]
            continue
        if line.strip() and not line.lstrip().startswith("."):
            # Anything else ends the current block.
            close()
    close()
    return out


def render_c() -> str:
    pals = palettes()
    out = [
        "/* Generated by tools/wlpal.py from IMGPAL.ASM. Do not edit.",
        " *",
        " * Each palette is a count word followed by that many RGB555",
        " * colours, which is exactly how PAL.ASM reads one. The count",
        " * word's low nine bits are the length; the rest are flags.",
        " */",
        '#include "wm/arcade/wm_arcade_pal.h"',
        "",
    ]
    for name in pals:
        words = pals[name]
        out.append("static const uint16_t pal_%s[] = {" % name)
        for base in range(0, len(words), 8):
            out.append("    " + ", ".join("0x%04X" % w
                                          for w in words[base:base + 8]) + ",")
        out.append("};")
    out.append("")
    out.append("/* Sorted by name so the lookup can bisect. */")
    out.append("const wm_palette wm_palettes[] = {")
    for name in sorted(pals):
        out.append('    { "%s", pal_%s },' % (name, name))
    out.append("};")
    out.append("")
    out.append("const int wm_palette_count = %d;" % len(pals))
    out.append("")
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out")
    ap.add_argument("--list", action="store_true")
    ns = ap.parse_args()
    pals = palettes()
    if ns.list:
        for name, words in pals.items():
            print("%-16s %3d colours  flags=%#06x"
                  % (name, words[0] & COUNT_MASK, words[0] & ~COUNT_MASK))
        print("\n%d palettes" % len(pals))
        return 0
    text = render_c()
    if ns.out:
        pathlib.Path(ns.out).write_text(text)
        print("palettes: %d from IMGPAL.ASM" % len(pals))
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
