#!/usr/bin/env python3
"""Extract WRESTLE2.ASM:1290 do_roll's per-wrestler `xxx_roll_frames`.

A wrestler knocked down rolls along Z while the player holds up or down,
and the frame he shows is picked from his own table by a running 8-bit
position. The table is three header values and a frame list:

     SUBR  hrt_roll_frames
         .word  7                    ;speed
         .long  50000h               ;z velocity
         .long  10000h*12/255        ;inv multiply (0-255 -> 0-12)
         .long  H3RL1A+FR1           ;0
         ...

do_roll adds `speed` to ROLL_POS (mod 256), multiplies by the inverse
multiplier and shifts right 16 to get an index into the frame list. The
lists are NOT in ascending frame order -- Bret's runs FR1 then FR13 down
to FR2, because that is the direction his artwork rolls.
"""
from __future__ import annotations
import argparse
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import wlanim  # noqa: E402

# WRESTLE2.ASM:1354 #roll_table, in WRESTLERNUM order (GAME.EQU W_*), with
# Adam Bomb's cut seventh slot written as a plain `.long 0`.
ROLL_TABLE = ["hrt", "rzr", "und", "yok", "shn", "bam", "dnk", None, "lex"]

WORD_RE = re.compile(r"^\s*\.word\s+(\S+)", re.I)
LONG_RE = re.compile(r"^\s*\.long\s+(\S+)", re.I)
FRAME_RE = re.compile(
    r"^\s*\.long\s+([A-Za-z_][A-Za-z0-9_]*)\s*\+\s*FR(\d+)\s*$", re.I)
ZERO_RE = re.compile(r"^\s*\.long\s+0(\s*,\s*0)*\s*$")


def _value(expr: str) -> int:
    """A header value, which may be an expression: `10000h*12/255`."""
    e = wlanim.HEX_SUFFIX_RE.sub(lambda m: "0x" + m.group(1), expr.strip())
    if not re.fullmatch(r"[0-9xXa-fA-F+*/() \t-]+", e):
        raise ValueError(f"unsupported roll-table value {expr!r}")
    return int(eval(e.replace("/", "//"), {"__builtins__": {}}, {}))


def table_for(who: str) -> dict:
    label = f"{who}_roll_frames"
    for path in wlanim.linked_files():
        lines = [wlanim.strip_comment(r)
                 for r in path.read_text(errors="replace").splitlines()]
        span = wlanim._routine_span(lines, label)
        if span is None:
            continue
        head: list[int] = []
        frames: list[str] = []
        for i in range(span[0], len(lines)):
            line = lines[i]
            if not line:
                continue
            if len(head) < 3:
                m = WORD_RE.match(line) or LONG_RE.match(line)
                if m:
                    head.append(_value(m.group(1)))
                continue
            m = FRAME_RE.match(line)
            if m:
                frames.append("%s%02d" % (m.group(1).upper(), int(m.group(2))))
                continue
            # The list ends in `.long 0,0,0,0,0,0` padding.
            if ZERO_RE.match(line) or wlanim.SUBR_RE.match(line):
                break
            if line.startswith("#") or line.startswith("*"):
                break
        if len(head) != 3:
            raise ValueError(f"{label}: expected speed/zvel/multiplier")
        if not frames:
            raise ValueError(f"{label}: no frames")
        # do_roll's index is (ROLL_POS * multiplier) >> 16 with ROLL_POS in
        # 0..255, so the largest index the table can ever produce is this.
        top = (255 * head[2]) >> 16
        if top >= len(frames):
            raise ValueError(
                f"{label}: multiplier reaches index {top} but the list has "
                f"only {len(frames)} frames")
        return {"who": who, "file": path.name, "speed": head[0],
                "zvel": head[1], "multiplier": head[2], "frames": frames,
                "top": top}
    raise ValueError(f"no routine {label}")


def tables() -> list[dict | None]:
    return [table_for(w) if w else None for w in ROLL_TABLE]


def render_c() -> str:
    rows = tables()
    out = ["/* Auto-generated by tools/wlroll.py from the original",
           "   WRESTLE2.ASM:1290 do_roll roll tables -- do not edit. */",
           '#include "wm/roll_frames.h"',
           ""]
    for r in rows:
        if not r:
            continue
        out.append(f"/* {r['file']}: {r['who']}_roll_frames, "
                   f"index 0..{r['top']} */")
        out.append(f"static const char *const {r['who']}_roll_frames[] = {{")
        for f in r["frames"]:
            out.append(f'    "{f}",')
        out += ["};", ""]
    out.append("const wm_roll_table wm_roll_tables[WM_ROLL_SLOTS] = {")
    for r in rows:
        if not r:
            out.append("    { 0, 0, 0, 0 },   /* Adam Bomb: `.long 0` */")
            continue
        out.append(f"    {{ {r['speed']}, {r['zvel']}, {r['multiplier']}, "
                   f"{r['who']}_roll_frames, "
                   f"sizeof({r['who']}_roll_frames) / "
                   f"sizeof({r['who']}_roll_frames[0]) }},")
    out += ["};", ""]
    return "\n".join(out)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out")
    ns = ap.parse_args(argv)
    if ns.out:
        pathlib.Path(ns.out).write_text(render_c())
        n = sum(1 for r in tables() if r)
        print(f"wrote {n} roll tables -> {ns.out}")
        return 0
    for r in tables():
        if not r:
            print("  (unused slot)")
            continue
        print(f"{r['who']:>4}  {r['file']:<12} speed={r['speed']} "
              f"zvel={r['zvel']:#x} mult={r['multiplier']} "
              f"frames={len(r['frames'])} top={r['top']}")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except (OSError, ValueError) as exc:
        print(f"wlroll: error: {exc}", file=sys.stderr)
        sys.exit(1)
