"""The global per-wrestler animation tables -- one animation per roster slot.

A lot of the game's shared behaviour is "everyone does this, but each in
his own animation", and the source spells that as a flat table indexed by
WRESTLERNUM:

    fall_back_tbl
        .long   hrt_fall_back_anim      ;0 Bret Hart
        .long   rzr_fall_back_anim      ;1 Razor Ramon
        ...
        .long   0                       ;7 spare
        .long   lex_fall_back_anim      ;8 Lex Luger

Slot 7 is Adam Bomb, cut from the game, and a tenth slot -- present in
some of these tables and not others -- is the Referee. Tables that carry
them sometimes hand both Doink's animation rather than nothing, so the
row count and the contents are both read rather than assumed.

tools/wlpuppet.py already extracts the tables that ANI_SLAVEANIM,
ANI_CHANGEANIM_TBL and friends name as command operands, resolving each
from its use site because those labels are `#local` and reused. These
are the other kind: plain globals reached by ordinary code
(`movi fall_back_tbl,a0`), which have exactly one definition each and so
need no use site to disambiguate. Anything defined more than once is
refused here rather than guessed at -- that is wlpuppet's job.
"""
from __future__ import annotations
import argparse
import collections
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import wlanim  # noqa: E402

ROSTER_SLOTS = 10           # 0..8 plus the Referee at 9

# The slot names, straight off the source's own end-of-line comments.
SLOT_NAMES = (
    "Bret Hart", "Razor Ramon", "Undertaker", "Yokozuna",
    "Shawn Michaels", "Bam Bam", "Doink", "Adam Bomb",
    "Lex Luger", "Referee",
)

LABEL_RE = re.compile(r"^\s*(?:SUBRP?\s+)?([A-Za-z_][A-Za-z0-9_]*):?\s*$")
LONG_RE = re.compile(r"^\s*\.long\s+(.+)$", re.I)

# A table has to be mostly animation labels to be one of these; the rest
# of the rows may be `0`, which is how a cut wrestler is spelled.
MIN_ANIM_ROWS = 5


def _blocks(path: pathlib.Path):
    """Every `label` followed by a run of .long rows, in one file."""
    lines = [wlanim.strip_comment(r)
             for r in path.read_text(errors="replace").splitlines()]
    i = 0
    while i < len(lines):
        m = LABEL_RE.match(lines[i]) if lines[i].strip() else None
        if not m:
            i += 1
            continue
        rows: list[str] = []
        j = i + 1
        while j < len(lines):
            if not lines[j].strip():
                j += 1
                continue
            lm = LONG_RE.match(lines[j])
            if not lm:
                break
            rows += [t.strip() for t in lm.group(1).split(",") if t.strip()]
            j += 1
        if rows:
            yield m.group(1), i + 1, rows
        i = max(j, i + 1)


def roster_tables() -> dict[str, tuple[str, int, list[str | None]]]:
    """{label: (file, line, rows)} for every unambiguous global table.

    Rows are padded to ROSTER_SLOTS with None so every table has the same
    shape in C; the real length is kept so a nine-row table is not
    silently claimed to name a Referee animation.
    """
    seen: dict[str, list[tuple[str, int, list[str]]]] = collections.defaultdict(list)
    for path in sorted(wlanim.ORIG.glob("*.ASM")):
        for name, line, rows in _blocks(path):
            if len(rows) not in (9, ROSTER_SLOTS):
                continue
            if sum(1 for r in rows if r.endswith("_anim")) < MIN_ANIM_ROWS:
                continue
            seen[name].append((path.name, line, rows))

    out: dict[str, tuple[str, int, list[str | None]]] = {}
    for name, defs in sorted(seen.items()):
        if len(defs) != 1:
            # Defined more than once: block-scoped, and only a use site
            # can say which one a given caller means. wlpuppet.py's
            # resolution handles those.
            continue
        fname, line, rows = defs[0]
        padded: list[str | None] = [None if r == "0" else r for r in rows]
        padded += [None] * (ROSTER_SLOTS - len(padded))
        out[name] = (fname, line, padded)
    return out


def _ambiguous() -> dict[str, int]:
    seen: dict[str, int] = collections.Counter()
    for path in sorted(wlanim.ORIG.glob("*.ASM")):
        for name, _line, rows in _blocks(path):
            if len(rows) in (9, ROSTER_SLOTS) and \
               sum(1 for r in rows if r.endswith("_anim")) >= MIN_ANIM_ROWS:
                seen[name] += 1
    return {k: v for k, v in seen.items() if v > 1}


def render_c() -> str:
    tables = roster_tables()
    out = [
        "/* Generated by tools/wlrostertbl.py. Do not edit.",
        " *",
        " * One animation per roster slot, indexed by WRESTLERNUM. Slot 7 is",
        " * Adam Bomb, cut from the game; slot 9 is the Referee and is only",
        " * present in the tables that declare ten rows. A NULL is a `.long 0`",
        " * in the source -- that slot has no animation at all.",
        " */",
        '#include "wm/arcade/wm_arcade_roster_anims.h"',
        "",
    ]
    for name, (fname, line, rows) in tables.items():
        out.append("/* %s:%d */" % (fname, line))
        out.append("static const char *const rows_%s[WM_ROSTER_ANIM_SLOTS] = {"
                   % name)
        for i, r in enumerate(rows):
            out.append('    %-28s /* %d %s */'
                       % (("NULL," if r is None else '"%s",' % r), i,
                          SLOT_NAMES[i]))
        out.append("};")
    out.append("")
    out.append("const wm_roster_anim_table wm_roster_anim_tables[] = {")
    for name, (fname, line, _rows) in tables.items():
        declared = ROSTER_SLOTS if _declared_ten(fname, line) else 9
        out.append('    { "%s", "%s", %d, %d, rows_%s },'
                   % (name, fname, line, declared, name))
    out.append("};")
    out.append("")
    out.append("const int wm_roster_anim_table_count = %d;" % len(tables))
    out.append("")
    return "\n".join(out)


_TEN_CACHE: dict[tuple[str, int], bool] = {}


def _declared_ten(fname: str, line: int) -> bool:
    """Did this table really write ten rows, or nine?

    A nine-row table has no Referee slot at all; a ten-row one may have
    written `0` there. The two are different statements and the emitted
    length says which.
    """
    key = (fname, line)
    if key not in _TEN_CACHE:
        path = wlanim.ORIG / fname
        for name, at, rows in _blocks(path):
            if at == line:
                _TEN_CACHE[key] = len(rows) == ROSTER_SLOTS
                break
        else:
            _TEN_CACHE[key] = False
    return _TEN_CACHE[key]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out")
    ap.add_argument("--list", action="store_true")
    ns = ap.parse_args()
    tables = roster_tables()
    if ns.list:
        for name, (fname, line, rows) in tables.items():
            print("%-24s %-16s:%-5d %d named, %d empty"
                  % (name, fname, line,
                     sum(1 for r in rows if r), sum(1 for r in rows if not r)))
        print("\n%d unambiguous global tables" % len(tables))
        amb = _ambiguous()
        print("%d labels defined more than once, left to tools/wlpuppet.py: %s"
              % (len(amb), ", ".join(sorted(amb))[:200]))
        return 0
    text = render_c()
    if ns.out:
        pathlib.Path(ns.out).write_text(text)
        print("roster animation tables: %d" % len(tables))
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
