#!/usr/bin/env python3
"""STRING.ASM's font tables -- which glyph each ASCII code draws.

Every message the game prints goes through one indirection.  A message
descriptor (MACROS.H:144 `JAM_STR FONT,SPACING,CSPACE,X,Y,PALETTE,METHOD`)
names a *font table* by label; `print_message` (STRING.ASM:686) parks that
pointer in `message_ascii`, and the printer then does, per character:

    sll  5,a0                     ; ASCII code * 32 bits -- one .long entry
    move @message_ascii,a1,L
    add  a1,a0
    move *a0,a2,L                 ; -> the glyph image, or 0 for "no glyph"

So a font table is exactly 128 `.long` slots, ASCII 0..127, each holding an
image symbol or zero.  Zero is not a space: `get_string_len` and the printer
both `jrz #next_char` on it, skipping the character *and* its inter-character
spacing entirely -- an unmapped character occupies no width at all.  Space
(32) never reaches the table; it is handled ahead of the lookup and costs
`mess_space_width`.  Code 1 is the newline.

Ten tables are live.  An eleventh, `sgmd8_ascii`, is commented out in the
source and is not emitted.  Two pairs are worth knowing about because they
differ in exactly one row each, and the difference is real:

  * `font9A_ascii` is `font9_ascii` with the digits swapped for the `FNT9_?A`
    variants; every letter is shared.
  * `win_ascii` is `ogmd10_ascii` with the digits swapped for `WFONT_?`.

Glyph *widths* are not in STRING.ASM.  The printer reads them out of the
image header at run time (`move *a1,a0  ;image width`), so they come from
the artwork -- and the artwork is here, in original/wwf-wrestlemania/IMG.
`--metrics-out` emits them, with two limits that are the tree's and not a
shortcut:

  * A WIMP image name field is eight characters, so a longer symbol is
    stored truncated.  `osgmd8_A`, `osgmd8_AND` and `osgmd8_APO` are all
    three stored as `osgmd8_A`.  Telling them apart needs the .LOD's
    packing order, and FONTS.LOD is zero bytes in this tree, so 46 such
    symbols get no width unless every candidate happens to agree on one
    (which resolves five of them outright).
  * The whole `osgmd10_*` family -- 49 symbols -- has no artwork in any
    container here at all.

That leaves 280 of the 375 symbols measured from the real images: every
letter and digit of every font, and most of the punctuation.  The rest
fall through to the port's width seam rather than being invented.
"""
from __future__ import annotations
import argparse
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import wlanim  # noqa: E402
import wimpimg  # noqa: E402

SRC = wlanim.ORIG / "STRING.ASM"
IMG_DIR = wlanim.ORIG / "IMG"

# The WIMP directory's name field.  A symbol longer than this is stored
# with its tail cut off, which is what makes some of them ambiguous.
NAME_FIELD = 8

TABLE_SLOTS = 128           # the .long table the `sll 5` index walks
LONG_RE = re.compile(r"^\s*\.long\s+(.+)$", re.I)
LABEL_RE = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*)\s*$")

# The order they appear in STRING.ASM.
TABLES = [
    "font9_ascii",
    "font9A_ascii",
    "font18_ascii",
    "osgemd_ascii",
    "osgmd8_ascii",
    "wgsf24_ascii",
    "wsf10_ascii",
    "wsf14_ascii",
    "ogmd10_ascii",
    "win_ascii",
]


def _lines() -> list[str]:
    """Comment-stripped source.  A leading `;` kills the whole line, which is
    what keeps the commented-out `sgmd8_ascii` out of the extraction."""
    return [wlanim.strip_comment(r)
            for r in SRC.read_text(errors="replace").splitlines()]


def font_table(name: str, lines: list[str] | None = None) -> list[str | None]:
    """The 128 ASCII slots of one `*_ascii` table.  None where the source
    has a bare 0 -- a code this font cannot draw."""
    lines = _lines() if lines is None else lines
    at = None
    for i, line in enumerate(lines):
        m = LABEL_RE.match(line)
        if m and m.group(1) == name:
            at = i
            break
    if at is None:
        raise ValueError(f"STRING.ASM: no {name}")
    slots: list[str | None] = []
    for line in lines[at + 1:]:
        if not line.strip():
            continue
        m = LONG_RE.match(line)
        if not m:
            break
        for tok in m.group(1).split(","):
            tok = tok.strip()
            if not tok:
                continue
            slots.append(None if tok == "0" else tok)
    if len(slots) != TABLE_SLOTS:
        raise ValueError(f"{name} has {len(slots)} slots, not {TABLE_SLOTS}")
    return slots


def font_tables() -> dict[str, list[str | None]]:
    lines = _lines()
    return {name: font_table(name, lines) for name in TABLES}


def _ident(name: str) -> str:
    return "wm_font_" + name.replace("_ascii", "").lower()


def render_c() -> str:
    tables = font_tables()
    out = [
        "/* Generated by tools/wlstring.py from STRING.ASM. Do not edit. */",
        "#include \"wm/arcade/wm_arcade_string.h\"",
        "",
    ]
    for name in TABLES:
        slots = tables[name]
        out.append(f"/* STRING.ASM {name} */")
        out.append(f"static const char *const {_ident(name)}_slots[128] = {{")
        for base in range(0, TABLE_SLOTS, 8):
            row = ", ".join("NULL" if s is None else '"%s"' % s
                            for s in slots[base:base + 8])
            out.append("    %s, /* $%02X */" % (row, base))
        out[-1] = out[-1].replace(", /* $78 */", "  /* $78 */")
        out.append("};")
        out.append(f"const wm_font_table {_ident(name)} = {{")
        out.append(f"    \"{name}\", {_ident(name)}_slots")
        out.append("};")
        out.append("")
    out.append("const wm_font_table *const wm_font_tables[] = {")
    for name in TABLES:
        out.append(f"    &{_ident(name)},")
    out.append("};")
    out.append("")
    out.append("const int wm_font_table_count = %d;" % len(TABLES))
    out.append("")
    return "\n".join(out)


def _containers() -> dict[str, list[tuple[str, int, int]]]:
    """Every image in every .IMG container, keyed by the (possibly
    truncated) name the container stores."""
    out: dict[str, list[tuple[str, int, int]]] = {}
    for path in sorted(IMG_DIR.glob("*.IMG")):
        try:
            _data, _hdr, images, _pals = wimpimg.parse_file(path)
        except Exception:
            # Not every .IMG in the tree is a WIMP container.
            continue
        for image in images:
            out.setdefault(image.name, []).append(
                (path.name, image.width, image.height))
    return out


def glyph_metrics() -> tuple[dict[str, int], list[str], list[str]]:
    """(measured, ambiguous, no-artwork) for every glyph the tables name.

    Width only: it is the one number STRING.ASM reads out of an image.

    A symbol is measured when the container can only mean it: either the
    stem it truncates to is claimed by one needed symbol and held by one
    image, or every image sharing the stem is the same width, in which
    case which one it is does not change the answer.  Anything else is
    left unmeasured -- picking one would be a guess.
    """
    needed: set[str] = set()
    for slots in font_tables().values():
        needed.update(s for s in slots if s)

    where = _containers()
    claims: dict[str, int] = {}
    for sym in needed:
        stem = sym[:NAME_FIELD]
        claims[stem] = claims.get(stem, 0) + 1

    measured: dict[str, int] = {}
    ambiguous: list[str] = []
    absent: list[str] = []
    for sym in sorted(needed):
        hits = where.get(sym[:NAME_FIELD], [])
        if not hits:
            absent.append(sym)
            continue
        widths = {w for _c, w, _h in hits}
        if (claims[sym[:NAME_FIELD]] == 1 and len(hits) == 1) or len(widths) == 1:
            measured[sym] = hits[0][1]
        else:
            ambiguous.append(sym)
    return measured, ambiguous, absent


def render_metrics_c() -> str:
    measured, ambiguous, absent = glyph_metrics()
    out = [
        "/* Generated by tools/wlstring.py from original/wwf-wrestlemania/IMG.",
        " * Do not edit.",
        " *",
        " * A glyph's pixel width is the image header's first word, which is",
        " * what STRING.ASM's printer reads (`move *a1,a0  ;image width`).",
        " * These come from the shipped .IMG containers.",
        " *",
        " * %d of %d symbols the font tables name are measured here."
        % (len(measured), len(measured) + len(ambiguous) + len(absent)),
        " * %d are stored under a name truncated to eight characters that more"
        % len(ambiguous),
        " * than one symbol shares, and telling them apart needs FONTS.LOD's",
        " * packing order -- that file is zero bytes in this tree:",
    ]
    for base in range(0, len(ambiguous), 6):
        out.append(" *   " + ", ".join(ambiguous[base:base + 6]))
    out.append(" * %d have no artwork in any container here:" % len(absent))
    for base in range(0, len(absent), 6):
        out.append(" *   " + ", ".join(absent[base:base + 6]))
    out.append(" */")
    out.append('#include "wm/arcade/wm_arcade_string.h"')
    out.append("")
    out.append("/* Sorted by name so the lookup can bisect. */")
    out.append("const wm_glyph_metric wm_glyph_metrics[] = {")
    for name in sorted(measured):
        out.append('    { "%s", %d },' % (name, measured[name]))
    out.append("};")
    out.append("")
    out.append("const int wm_glyph_metric_count = %d;" % len(measured))
    out.append("")
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out")
    ap.add_argument("--metrics-out")
    ap.add_argument("--list", action="store_true")
    ns = ap.parse_args()
    if ns.metrics_out:
        pathlib.Path(ns.metrics_out).write_text(render_metrics_c())
        measured, ambiguous, absent = glyph_metrics()
        print("glyph metrics: %d measured, %d ambiguous, %d without artwork"
              % (len(measured), len(ambiguous), len(absent)))
        if not ns.out:
            return 0
    if ns.list:
        for name, slots in font_tables().items():
            drawable = sum(1 for s in slots if s)
            print("%-16s %3d of 128 codes drawable  (e.g. 'A' -> %s)"
                  % (name, drawable, slots[ord("A")]))
        return 0
    text = render_c()
    if ns.out:
        pathlib.Path(ns.out).write_text(text)
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
