#ifndef WM_ANIM_PROGRAM_H
#define WM_ANIM_PROGRAM_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "wm/arcade/wm_arcade_combat.h"
#include "wm/anim_puppet.h"
#include "wm/arcade/wmania_rng.h"

/*
 * An animation as the program it is in ANIM.ASM, rather than as a flat list
 * of frames with side tables hung off frame indices.
 *
 * The flat model cannot express a branch: a routine that plays different
 * frames on a hit than on a miss has to be linearised into one list that no
 * playthrough ever plays. Every attack wired in this port carries at least
 * one such fork -- hrt_2_punch_anim's own ANI_SLIDE_BACK skips a frame when
 * the punch missed -- so the frames have been an approximation throughout.
 *
 * Ops are generated by tools/wlprogram.py with branch targets already
 * resolved to op indices, so the interpreter never needs the source text.
 */
typedef enum {
    WM_AOP_FRAME = 0,      /* text = source frame, a = ticks */
    WM_AOP_END,
    WM_AOP_REPEAT,

    /* branches; `target` is an op index in this same program */
    WM_AOP_GOTO,
    WM_AOP_IFSTATUS,       /* ANIM.ASM:29  MODE_STATUS set   -> branch */
    WM_AOP_IFNOTSTATUS,    /* ANIM.ASM:45  MODE_STATUS clear -> branch */
    WM_AOP_IFBLOCKED,      /* ANIM.ASM:83  hitblocker set    -> branch */
    WM_AOP_IF_RPTCOUNT,    /* ANIM.ASM:90  rpt_count nonzero -> branch */
    /* ANIM.ASM:3214/:3239 -- `a` is the button's PLYR.EQU:152-156 index
       (0 punch, 1 block, 2 super punch, 3 kick, 4 super kick), `b` the
       number of presses compared against. The mash mechanic: 239 uses
       across the eight playable wrestlers' sequence files. */
    WM_AOP_IF_BUTCOUNT_GE, /* ANIM.ASM:88  count >= b -> branch */
    WM_AOP_IF_BUTCOUNT_LT, /* ANIM.ASM:89  count <  b -> branch */
    WM_AOP_SLIDE_BACK,     /* MODE_STATUS clear -> branch (no slide) */

    /* become another animation */
    WM_AOP_CHANGEANIM,     /* text = target animation's source label */
    WM_AOP_IFBUTTONS,      /* a = button mask, text = target label */

    /* repeat counter */
    WM_AOP_SET_RPTCOUNT,   /* a = count */
    WM_AOP_DEC_RPTCOUNT,

    /* attack boxes */
    WM_AOP_ATTACK_ON,      /* mode = AMODE, a..d = x,y,w,h */
    WM_AOP_ATTACK_ON_Z,    /* mode = AMODE, a..f = x,y,z,w,h,d */
    WM_AOP_ATTACK_OFF,

    /* instant state, all translated in src/core/anim_frame_commands.c */
    WM_AOP_SETMODE,        /* a = ANIMODE bits, absolute */
    WM_AOP_SETPLYRMODE,    /* a = player mode */
    WM_AOP_SETFACING,
    WM_AOP_XFLIP,
    WM_AOP_ZEROVELS,
    WM_AOP_ZERO_XZVELS,
    WM_AOP_SET_XVEL,       /* mode = AM_*, a = value */
    WM_AOP_SET_YVEL,
    WM_AOP_SET_ZVEL,
    WM_AOP_MIN_YVEL,
    WM_AOP_FRICTION,
    WM_AOP_OFFSET,         /* a,b,c = x,y,z */
    WM_AOP_SETSPEED,
    WM_AOP_STARTATTACK,    /* a = AT_ type, b = ticks */
    WM_AOP_FACEUP,
    WM_AOP_FACEDOWN,
    WM_AOP_SET_WRESTLER_XFLIP,
    WM_AOP_CLR_BUTCOUNT,
    WM_AOP_SAFE_TIME,
    WM_AOP_GRAVITY_ON,
    WM_AOP_CLR_STATUS,

    /* ANIM.ASM:1277 _ani_code -- `move *a4+,a0,L / call a0`: an ordinary
       subroutine call, zero ticks, with a13 still the wrestler. `text` is
       the routine's own name; src/core/anim_code.c holds the ones this
       port has translated and wm_anim_code_find reports the rest as the
       named gaps they are. 2303 uses across the eight playable wrestlers,
       but only 145 distinct targets. */
    WM_AOP_CODE,

    /* ANIM.ASM:2681 _ani_superslave2 -- one animation driving BOTH
       wrestlers, which is what a grapple, slam, suplex or throw IS. `a` is
       the tick count, `text` the attacker's own frame, `b` the puppet
       table id (wm/anim_puppet.h) and `c` the row index within it. Yields
       like a frame, because it is one: it sets OANICNT and stops. 927 uses
       across the eight playable wrestlers. */
    WM_AOP_SUPERSLAVE2,

    /* The rest of the attach machinery -- what makes a grapple START and
       END rather than merely animate. */
    WM_AOP_SET_ATTACH,     /* ANIM.ASM:4156 :113  link to WHOIHIT, both ways */
    WM_AOP_DETACH,         /* ANIM.ASM:851  :10   break the link, both ways */
    WM_AOP_ATTACHZ,        /* ANIM.ASM:1039 :18   a,b,c = x,y,z attach offsets */
    WM_AOP_SETOPPMODE,     /* ANIM.ASM:2888 :80   a = ANIMODE bits to set */
    WM_AOP_CLROPPMODE,     /* ANIM.ASM:2912 :81   a = ANIMODE bits to clear */
    WM_AOP_IMMOBILIZE,     /* ANIM.ASM:3933 :108  a = ticks */
    WM_AOP_IFOPPMODE,      /* ANIM.ASM:2417 :70   a = PLYRMODE, or ~mode */
    WM_AOP_SETOPPVELS,     /* ANIM.ASM:3997 :110  a,b,c = x,y,z, the throw */
    WM_AOP_DAMAGEOPP,      /* ANIM.ASM:2175 :66   a,b = full, reduced */
    WM_AOP_SLAVEANIM,      /* ANIM.ASM:2130 :64   a = slave table id */

    /* Present in the source but needing a system this port does not have
       (a renderer, paired actors, a callback bridge). Carried so the
       program stays a faithful record, executed as no-ops. */
    WM_AOP_UNTRANSLATED
} wm_anim_opcode;

typedef struct {
    uint8_t op;
    uint8_t mode;
    int16_t target;        /* branch destination op index, else -1 */
    int32_t a, b, c, d, e, f;
    const char *text;      /* frame name, or a target animation's label */
} wm_anim_op;

typedef struct {
    const char *source_label;
    const char *source_file;
    const wm_anim_op *ops;
    size_t op_count;
} wm_anim_program;

/* Execution state. One per actor track. */
/*
 * What an ANI_CODE routine can reach beyond the actor itself.
 *
 * The source's own routines run with a13 = this wrestler and the whole
 * machine addressable around them; this is the subset the translated ones
 * genuinely use. Every field may be NULL -- a routine whose service is
 * missing does nothing rather than inventing a result, which is why the
 * host tests can run programs with no environment at all.
 */
typedef struct wm_anim_env {
    /* The wrestler this one is fighting, for the routines that read
       *a13(ATTACH_PROC) or the opponent's own fields. */
    wm_arcade_actor_t *opponent;
    /* UTIL.ASM RNDRNG0/RNDPER, which the sound pickers use to choose
       between the entries of their real tables. */
    WmRng *rng;
    /* The source's own global PCNT, the free-running 32-bit frame counter
       the timestamping routines stamp with (head_grab_time's LAST_HEADHOLD,
       and the delay checks that read it back). */
    uint32_t pcnt;
    /* DCSSOUND.ASM triple_sound: `call` is the sound's own index into
       triple_sndtab, passed through unchanged. Channel arbitration and
       priority are triple_sound's own job and belong to a DCSSOUND port,
       not to this bridge. */
    void *sound_user;
    void (*sound)(void *user, uint16_t call);
    /*
     * ANIM.ASM:2130 ANI_SLAVEANIM makes the VICTIM start a whole animation
     * of his own -- the source literally swaps a13 to the victim and calls
     * change_anim1a. A slam does not pose him, it makes him run his own
     * landing. That needs a way to reach his backend, which only the
     * caller has.
     */
    void *slave_user;
    void (*change_opp_anim)(wm_arcade_actor_t *opp, const char *label,
                            void *user);
} wm_anim_env;

typedef struct {
    const wm_anim_program *program;
    size_t pc;             /* op index of the frame currently showing */
    size_t next_pc;        /* where execution resumes when it expires */
    uint16_t ticks_left;
    uint16_t rpt_count;
    bool ended;
    bool just_started;
    const char *become;    /* set when the program asks to become another */
    const wm_anim_env *env;   /* services ANI_CODE routines may reach for */
} wm_anim_exec;

const wm_anim_program *wm_anim_program_find(const char *source_label);

/*
 * An ANI_CODE routine. `param` is the constant its registry row carries,
 * for the routines the source writes once per file with a different value
 * in each -- see wm_anim_code_run.
 */
typedef void (*wm_anim_code_fn)(wm_arcade_actor_t *actor,
                                const wm_anim_env *env, int32_t param);

/*
 * Run the ANI_CODE routine `name`, as called from `source_file`. Returns
 * false for one this port has not translated -- the op is then the no-op
 * it has always effectively been, but a named and countable gap rather
 * than a line the extractor silently dropped.
 *
 * The file matters. A target beginning with '#' is a LOCAL label, scoped
 * to the file that defines it, and the sequence files reuse those names
 * freely: 22 of the 59 local ANI_CODE targets are defined in more than one
 * file, and they are not copies -- #make_black has SEVEN distinct bodies
 * across eight files, because (as the source says at each one) "this is a
 * black color within the wrestler's pal, it is different for each
 * wrestler". Resolving those by bare name hands one wrestler's routine to
 * all the others.
 */
bool wm_anim_code_run(wm_arcade_actor_t *actor, const wm_anim_env *env,
                      const char *name, const char *source_file);

/* How many ANI_CODE registry rows are translated, for coverage reporting.
   A routine written once per file counts once per file, since each is a
   different body. */
size_t wm_anim_code_count(void);

/* DCSSOUND.ASM's DUMMY_WAIT lockout, one tick. Call once per game tick. */
void wm_anim_code_tick(void);
/* Clear the ANI_CODE routines' own global state (ENDLESS_SOUND and that
   lockout) -- the source clears them between rounds. */
void wm_anim_code_reset(void);
/* DCSSOUND.ASM's ENDLESS_SOUND: the one looping sound the machine allows. */
uint16_t wm_anim_code_endless_sound(void);

/* Start `program`: runs its header commands and stops on the first frame.
   `env` is kept for the life of the animation, so it must outlive it; NULL
   means the ANI_CODE routines that need a service simply do nothing. */
void wm_anim_exec_start(wm_anim_exec *exec, const wm_anim_program *program,
                        wm_arcade_actor_t *actor, uint16_t round_tickcount,
                        const wm_anim_env *env);

/* Advance one tick. Runs commands and takes branches as the frame expires. */
void wm_anim_exec_tick(wm_anim_exec *exec, wm_arcade_actor_t *actor,
                       uint16_t round_tickcount);

/* The frame currently showing, or NULL once the program has ended. */
const char *wm_anim_exec_frame(const wm_anim_exec *exec);

#endif
