#ifndef WM_ANIM_PROGRAM_H
#define WM_ANIM_PROGRAM_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "wm/arcade/wm_arcade_combat.h"
#include "wm/anim_puppet.h"
#include "wm/arcade/wmania_rng.h"
#include "wm/arcade/wm_arcade_announcer.h"

/*
 * An animation as the program it is in ANIM.ASM, rather than as a flat list
 * of frames with side tables hung off frame indices.
 *
 * The flat model cannot express a branch: a routine that plays different
 * frames on a hit than on a miss has to be linearised into one list that no
 * playthrough ever plays. Every attack wired in this port carries at least
 * one such fork -- hrt_2_punch_anim's own ANI_SLIDE_BACK skips a frame when
 * the punch missed -- so the frames have been an approximation throughout.
 *
 * Ops are generated by tools/wlprogram.py with branch targets already
 * resolved to op indices, so the interpreter never needs the source text.
 */
typedef enum {
    WM_AOP_FRAME = 0,      /* text = source frame, a = ticks */
    WM_AOP_END,
    WM_AOP_REPEAT,

    /* branches; `target` is an op index in this same program */
    WM_AOP_GOTO,
    WM_AOP_IFSTATUS,       /* ANIM.ASM:29  MODE_STATUS set   -> branch */
    WM_AOP_IFNOTSTATUS,    /* ANIM.ASM:45  MODE_STATUS clear -> branch */
    WM_AOP_IFBLOCKED,      /* ANIM.ASM:83  hitblocker set    -> branch */
    WM_AOP_IF_RPTCOUNT,    /* ANIM.ASM:90  rpt_count nonzero -> branch */
    /* ANIM.ASM:3214/:3239 -- `a` is the button's PLYR.EQU:152-156 index
       (0 punch, 1 block, 2 super punch, 3 kick, 4 super kick), `b` the
       number of presses compared against. The mash mechanic: 239 uses
       across the eight playable wrestlers' sequence files. */
    WM_AOP_IF_BUTCOUNT_GE, /* ANIM.ASM:88  count >= b -> branch */
    WM_AOP_IF_BUTCOUNT_LT, /* ANIM.ASM:89  count <  b -> branch */
    WM_AOP_SLIDE_BACK,     /* MODE_STATUS clear -> branch (no slide) */

    /* become another animation */
    WM_AOP_CHANGEANIM,     /* text = target animation's source label */
    WM_AOP_IFBUTTONS,      /* a = button mask, text = target label */

    /* repeat counter */
    WM_AOP_SET_RPTCOUNT,   /* a = count */
    WM_AOP_DEC_RPTCOUNT,

    /* attack boxes */
    WM_AOP_ATTACK_ON,      /* mode = AMODE, a..d = x,y,w,h */
    WM_AOP_ATTACK_ON_Z,    /* mode = AMODE, a..f = x,y,z,w,h,d */
    WM_AOP_ATTACK_OFF,

    /* instant state, all translated in src/core/anim_frame_commands.c */
    WM_AOP_SETMODE,        /* a = ANIMODE bits, absolute */
    WM_AOP_SETPLYRMODE,    /* a = player mode */
    WM_AOP_SETFACING,
    WM_AOP_XFLIP,
    WM_AOP_ZEROVELS,
    WM_AOP_ZERO_XZVELS,
    WM_AOP_SET_XVEL,       /* mode = AM_*, a = value */
    WM_AOP_SET_YVEL,
    WM_AOP_SET_ZVEL,
    WM_AOP_MIN_YVEL,
    WM_AOP_FRICTION,
    WM_AOP_OFFSET,         /* a,b,c = x,y,z */
    WM_AOP_SETSPEED,
    WM_AOP_STARTATTACK,    /* a = AT_ type, b = ticks */
    WM_AOP_FACEUP,
    WM_AOP_FACEDOWN,
    WM_AOP_SET_WRESTLER_XFLIP,
    WM_AOP_CLR_BUTCOUNT,
    WM_AOP_SAFE_TIME,
    WM_AOP_GRAVITY_ON,
    /*
     * ANIM.ASM:890 _ani_waithitgnd. Not an instant command: it holds the
     * frame that is showing for one tick and re-tests, over and over,
     * until the wrestler is on the ground -- then plays SMALL_BOUNCE and
     * runs on. 767 uses across the eight playable wrestlers, the single
     * most common untranslated opcode in the machine, because it is how
     * every knockdown, slam and throw waits for the landing.
     */
    WM_AOP_WAITHITGND,
    /* ANIM.ASM:950 _ani_bounce: OBJ_YVEL = operand << 16. */
    WM_AOP_BOUNCE,
    /* ANIM.ASM:2300 _ani_waithitopp sets MODE_WAITHITOPP and hands its
       operands back to the dispatcher, so the frame that follows is an
       ordinary one -- landing (or hitting) cuts its hold short. */
    WM_AOP_WAITHITOPP,
    /* ANIM.ASM:3913 _ani_setlong writes a LONG into a process field.
       `a` is the field (0 = OBJ_GRAVITY, 1 = DEBRIS_X), `b` the value. */
    WM_AOP_SETLONG,
    /*
     * ANIM.ASM:2990 _ani_waitroll (171 uses) -- what a knocked-down
     * wrestler's animation parks on while the player rolls him. Like
     * ANI_WAITHITGND it holds the frame and re-tests every tick; unlike
     * it, the wrestler is not passive. Each tick it forces MODE_ONGROUND,
     * waits out IMMOBILIZE_TIME and GETUP_TIME, then calls do_roll --
     * and it is do_roll returning "did NOT roll" that lets the animation
     * move on, so letting go of the stick is what gets him up.
     */
    WM_AOP_WAITROLL,
    /*
     * ANIM.ASM:4441 _ani_rot -- "just sit and do nothing", the source's own
     * comment. It holds the current frame and never advances, so an
     * animation that reaches one is parked for good: WRESTLE2.ASM:3992
     * xxx_dead_anim ends on one, which is how a dead wrestler stays down.
     */
    WM_AOP_ROT,
    /* ANIM.ASM:_ani_getup (52): GETUP_TIME = operand, unless PLYR_DIZZY.
       ANI_WAITROLL is what waits it out. */
    WM_AOP_GETUP,
    /*
     * The combo meter (wm/arcade/wm_arcade_combo.h). ANI_ADD_MOVE (:4247,
     * 273 uses) grows the meter bar through ADD_TO_COMBO_COUNT;
     * ANI_INC_COMBO (:114, 183) bumps the COMBO_COUNT that adjust_health's
     * damage rule reads and locks the victim for 30 ticks; ANI_CLEAR_COMBO
     * (:115, 208) is both the start AND the end of a combo, depending on
     * whether COMBO_COUNT was already set.
     */
    WM_AOP_ADD_MOVE,
    WM_AOP_INC_COMBO,
    WM_AOP_CLEAR_COMBO,
    /*
     * The rest of the self-contained state commands -- no subsystem behind
     * any of them, the same class as ANI_SETSPEED and friends.
     *
     * ANI_FACE (ANIM.ASM:50, 81 uses) writes FACING_DIR, XOR-ing the
     * left/right bits when the sprite is mirrored. ANI_GRAVITY_OFF (:16,
     * 24) is ANI_GRAVITY_ON's other half. ANI_DAMAGE (:56, 25) calls
     * adjust_health with the operand NEGATED -- "positive a0 = health
     * increase", the source's own note. ANI_SETOPP_PLYRMODE (:105, 26)
     * and ANI_OPP_GETUP (:76, 22) and ANI_ATTACHVEL (:24, 17) all act on
     * the wrestler being held. ANI_SETWORD (:51, 40) is ANI_SETLONG's WORD
     * counterpart; `a` is the field (0 = USR_VAR1, 1 = USR_VAR2,
     * 2 = DELAY_METER), `b` the value.
     */
    WM_AOP_FACE,
    WM_AOP_GRAVITY_OFF,
    WM_AOP_DAMAGE,
    WM_AOP_SETOPP_PLYRMODE,
    WM_AOP_OPP_GETUP,
    WM_AOP_ATTACHVEL,
    WM_AOP_SETWORD,
    /* ANIM.ASM:91 _ani_ifnot_rptcount -- branch when RPT_COUNT has run
       out, the inverse of ANI_IF_RPTCOUNT. */
    WM_AOP_IFNOT_RPTCOUNT,
    /*
     * ANIM.ASM:26 _ani_sound (104 uses): the sound's own index straight
     * into triple_sound, through wm_anim_env::sound like every other
     * sound in this port. Two special cases in the source, one live and
     * one not: SOUND.H's run_snd (0C0h) is debounced against FOOT_PCNT so
     * footsteps cannot stack, and a NEGATIVE operand would go to
     * wrtable_sound's per-wrestler table instead -- no use across the
     * eight playable wrestlers is negative, so that branch is unreached
     * here rather than skipped.
     */
    WM_AOP_SOUND,
    /*
     * The ropes. ANIM.ASM:35 _ani_bouncerope and :37 _ani_bendrope both
     * pick the bank from which side of RING_X_CENTER the wrestler is on,
     * then call ROPES.ASM's rope_command -- side spring and down spring
     * respectively, and their RELEASE variants when the operand is
     * NEGATIVE (16 ANI_BENDROPE,-1 and 9 ANI_BOUNCEROPE,-1 across the
     * roster, so that branch is real). A bounce also plays sound 3Ch.
     * ANIM.ASM:41 _ani_rope_z picks the same bank and calls set_rope_z
     * with a strand and an action.
     *
     * These reach the rope subsystem through wm_anim_env::rope_command,
     * because the animation cannot own the rope processes.
     */
    WM_AOP_BOUNCEROPE,
    WM_AOP_BENDROPE,
    WM_AOP_ROPE_Z,
    /* ANIM.ASM:128 _ani_clear_climb: done climbing through the ropes, and
       one tick of SAFE_TIME so the collision that follows is skipped. */
    WM_AOP_CLEAR_CLIMB,
    /*
     * The last of the opponent-facing state commands, all behind the same
     * mutual-link check: ANIM.ASM:106 flips the held wrestler's sprite,
     * :85 snaps his FACING_DIR to his NEW_FACING_DIR, :112 writes his
     * X velocity with the same AM_* relative modes ANI_SET_XVEL uses.
     */
    WM_AOP_XFLIP_OPP,
    WM_AOP_SETOPPFACING,
    WM_AOP_SET_OPP_XVEL,
    /* ANIM.ASM:28 _ani_pause -- "hold current frame for a few ticks": it
       stuffs OANICNT and returns without a frame of its own. */
    WM_AOP_PAUSE,
    /* ANIM.ASM:129 _ani_setflag: STATUS_FLAGS |= operand, a LONG. */
    WM_AOP_SETFLAG,
    /* ANIM.ASM:49 _ani_checkword: MODE_STATUS from whether the named
       field is non-zero -- ANI_SETWORD's field ids, ANI_SETWORD's mirror. */
    WM_AOP_CHECKWORD,
    /*
     * ANIM.ASM:86 _ani_ifopp -- "sets STATUS if opponent is one of the
     * wrestlers in the list, else clears". The source list is variable
     * length and -1 terminated; `a` is those wrestler numbers as a bit
     * mask, because no use names more than two.
     */
    WM_AOP_IFOPP,
    /* ANIM.ASM:129 _ani_opp_face: the held wrestler's FACING_DIR, mirrored
       across left/right when HIS sprite is flipped -- ANI_FACE for him. */
    WM_AOP_FACE_OPP,
    /*
     * ANIM.ASM:103 _ani_hmbwait -- a three-way frame hold: `a` ticks if
     * the attack HIT, `b` if it MISSED, `c` if it was BLOCKED. A zero for
     * the chosen case falls straight through to the next command instead
     * of holding, which is the source's `jrz _next_command`.
     */
    WM_AOP_HMBWAIT,
    /*
     * ANIM.ASM:20 _ani_waitrelease -- park on this frame while the named
     * button is still held. It also keeps FACING_DIR and the sprite mirror
     * following NEW_FACING_DIR each tick, "since we do the flip here".
     * hrt_4_block_anim is the reason a block lasts as long as the player
     * holds block; the Bret backend had been special-casing exactly this.
     */
    WM_AOP_WAITRELEASE,
    /* ANIM.ASM:119 -- branch when RPT_COUNT is at least the operand. */
    WM_AOP_IF_RPTCOUNT_GE,
    /*
     * The three per-wrestler table opcodes (wm/anim_puppet.h). `a` is the
     * generated table id in each case. ANI_CHANGEANIM_TBL (ANIM.ASM:118)
     * hands off to the animation HIS OWN number selects; ANI_XFLIP_TBL
     * (:109) flips the held wrestler's sprite when the table says so for
     * HIM; ANI_OPPOFFSET (:82) reads an x/y pair for him.
     */
    WM_AOP_CHANGEANIM_TBL,
    WM_AOP_XFLIP_TBL,
    WM_AOP_OPPOFFSET,
    WM_AOP_CLR_STATUS,

    /* ANIM.ASM:1277 _ani_code -- `move *a4+,a0,L / call a0`: an ordinary
       subroutine call, zero ticks, with a13 still the wrestler. `text` is
       the routine's own name; src/core/anim_code.c holds the ones this
       port has translated and wm_anim_code_find reports the rest as the
       named gaps they are. 2303 uses across the eight playable wrestlers,
       but only 145 distinct targets. */
    WM_AOP_CODE,

    /* ANIM.ASM:2681 _ani_superslave2 -- one animation driving BOTH
       wrestlers, which is what a grapple, slam, suplex or throw IS. `a` is
       the tick count, `text` the attacker's own frame, `b` the puppet
       table id (wm/anim_puppet.h) and `c` the row index within it. Yields
       like a frame, because it is one: it sets OANICNT and stops. 927 uses
       across the eight playable wrestlers. */
    WM_AOP_SUPERSLAVE2,

    /* The rest of the attach machinery -- what makes a grapple START and
       END rather than merely animate. */
    WM_AOP_SET_ATTACH,     /* ANIM.ASM:4156 :113  link to WHOIHIT, both ways */
    WM_AOP_DETACH,         /* ANIM.ASM:851  :10   break the link, both ways */
    WM_AOP_ATTACHZ,        /* ANIM.ASM:1039 :18   a,b,c = x,y,z attach offsets */
    WM_AOP_SETOPPMODE,     /* ANIM.ASM:2888 :80   a = ANIMODE bits to set */
    WM_AOP_CLROPPMODE,     /* ANIM.ASM:2912 :81   a = ANIMODE bits to clear */
    WM_AOP_IMMOBILIZE,     /* ANIM.ASM:3933 :108  a = ticks */
    WM_AOP_IFOPPMODE,      /* ANIM.ASM:2417 :70   a = PLYRMODE, or ~mode */
    WM_AOP_SETOPPVELS,     /* ANIM.ASM:3997 :110  a,b,c = x,y,z, the throw */
    WM_AOP_DAMAGEOPP,      /* ANIM.ASM:2175 :66   a,b = full, reduced */
    WM_AOP_SLAVEANIM,      /* ANIM.ASM:2130 :64   a = slave table id */

    /* Present in the source but needing a system this port does not have
       (a renderer, paired actors, a callback bridge). Carried so the
       program stays a faithful record, executed as no-ops. */
    WM_AOP_UNTRANSLATED
} wm_anim_opcode;

typedef struct {
    uint8_t op;
    uint8_t mode;
    int16_t target;        /* branch destination op index, else -1 */
    int32_t a, b, c, d, e, f;
    const char *text;      /* frame name, or a target animation's label */
} wm_anim_op;

typedef struct {
    const char *source_label;
    const char *source_file;
    const wm_anim_op *ops;
    size_t op_count;
} wm_anim_program;

/* Execution state. One per actor track. */
/*
 * What an ANI_CODE routine can reach beyond the actor itself.
 *
 * The source's own routines run with a13 = this wrestler and the whole
 * machine addressable around them; this is the subset the translated ones
 * genuinely use. Every field may be NULL -- a routine whose service is
 * missing does nothing rather than inventing a result, which is why the
 * host tests can run programs with no environment at all.
 */
/* SOUND.H:12 run_snd -- the footstep _ani_sound debounces. */
#define WM_SND_RUN 0xC0u

typedef struct wm_anim_env {
    /* The wrestler this one is fighting, for the routines that read
       *a13(ATTACH_PROC) or the opponent's own fields. */
    wm_arcade_actor_t *opponent;
    /* UTIL.ASM RNDRNG0/RNDPER, which the sound pickers use to choose
       between the entries of their real tables. */
    WmRng *rng;
    /* The source's own global PCNT, the free-running 32-bit frame counter
       the timestamping routines stamp with (head_grab_time's LAST_HEADHOLD,
       and the delay checks that read it back). */
    uint32_t pcnt;
    /* DCSSOUND.ASM triple_sound: `call` is the sound's own index into
       triple_sndtab, passed through unchanged. Channel arbitration and
       priority are triple_sound's own job and belong to a DCSSOUND port,
       not to this bridge. */
    void *sound_user;
    void (*sound)(void *user, uint16_t call);
    /*
     * ANIM.ASM:2130 ANI_SLAVEANIM makes the VICTIM start a whole animation
     * of his own -- the source literally swaps a13 to the victim and calls
     * change_anim1a. A slam does not pose him, it makes him run his own
     * landing. That needs a way to reach his backend, which only the
     * caller has.
     */
    void *slave_user;
    void (*change_opp_anim)(wm_arcade_actor_t *opp, const char *label,
                            void *user);
    /*
     * ROPES.ASM's rope_command / set_rope_z. The animation says WHICH rope
     * and WHAT to do to it; the rope processes themselves belong to the
     * match, so the caller supplies this. `bank` is a WmRopeBank, `action`
     * a WmRopeAction, `selector` the source's own a2. For ANI_ROPE_Z the
     * action is WM_ROPE_Z_HIGH/NORM and `selector` is the strand.
     */
    /*
     * DCSSOUND.ASM's announcer queue (wm/arcade/wm_arcade_announcer.h).
     * ANI_INC_COMBO asks for HES_JUST_GONE_BERSERK at exactly eight hits,
     * and it asks through IF_SILENT_ADD_VOICE -- "say this only if the
     * announcer has nothing else to say" -- which is why it needed the
     * queue rather than a direct sound. The whole CALL_x announcer group
     * reaches it the same way, through wm/announce_tables.h.
     */
    wm_announcer_state *announcer;
    /* DO_END_STUFF's `get_health` sweep over every wrestler: is anybody
       under 40 health? NULL means "cannot tell", and the announcer then
       keeps walking the ordinary table exactly as a healthy roster does. */
    bool (*anyone_near_death)(void *user);
    void *announcer_user;

    /*
     * AWARD.ASM round_award, reached through JJXM.H's RND_AWARD macro.
     * DO_COMBO_MESS gives one; so does ANIM.ASM:2253's first hit, whose
     * own seam (wm_arcade_react.h) has been declared and unwired all
     * along because the award state lives in the app rather than the
     * match. `award_index` is a GAME.EQU *_AWD index.
     */
    void *award_user;
    void (*round_award)(void *user, int player_num, unsigned award_index);

    void *rope_user;
    void (*rope_command)(void *user, int bank, int action, int selector,
                         int32_t wrestler_z_fp16);
    void (*rope_set_z)(void *user, int bank, int strand, int action);
    /*
     * Wired in wm_match_tick to the real ROPES.ASM subsystem
     * (wm/arcade/wmania_rope_runtime.h). Getting there meant removing a
     * duplicate: this port used to carry TWO rope translations, and both
     * defined WM_ROPE_FRONT. The older wm/ropes.h was a 43-line stub whose
     * own comment said "TODO later: port command_table/sspring/dspring
     * script selection exactly after the original table labels are
     * converted into portable data IDs" -- which is exactly what the
     * arcade one then did, table corpus and runtime included. The stub is
     * deleted rather than reconciled.
     */
} wm_anim_env;

typedef struct {
    const wm_anim_program *program;
    size_t pc;             /* op index of the frame currently showing */
    size_t next_pc;        /* where execution resumes when it expires */
    uint16_t ticks_left;
    uint16_t rpt_count;
    bool ended;
    bool just_started;
    /*
     * The program is parked on an ANI_WAITHITGND, holding the frame that
     * is showing until the wrestler lands. Callers that keep a second,
     * flat frame track beside the program (wm/bret_backend.h) have to hold
     * it too while this is set, or the two drift apart by however long the
     * fall takes -- the same reason hrt_4_block_anim's ANI_WAITRELEASE
     * holds both.
     */
    bool waiting;
    const char *become;    /* set when the program asks to become another */
    const wm_anim_env *env;   /* services ANI_CODE routines may reach for */
} wm_anim_exec;

const wm_anim_program *wm_anim_program_find(const char *source_label);

/*
 * An ANI_CODE routine. `param` is the constant its registry row carries,
 * for the routines the source writes once per file with a different value
 * in each -- see wm_anim_code_run.
 */
typedef void (*wm_anim_code_fn)(wm_arcade_actor_t *actor,
                                const wm_anim_env *env, int32_t param);

/*
 * Run the ANI_CODE routine `name`, as called from `source_file`. Returns
 * false for one this port has not translated -- the op is then the no-op
 * it has always effectively been, but a named and countable gap rather
 * than a line the extractor silently dropped.
 *
 * The file matters. A target beginning with '#' is a LOCAL label, scoped
 * to the file that defines it, and the sequence files reuse those names
 * freely: 22 of the 59 local ANI_CODE targets are defined in more than one
 * file, and they are not copies -- #make_black has SEVEN distinct bodies
 * across eight files, because (as the source says at each one) "this is a
 * black color within the wrestler's pal, it is different for each
 * wrestler". Resolving those by bare name hands one wrestler's routine to
 * all the others.
 */
bool wm_anim_code_run(wm_arcade_actor_t *actor, const wm_anim_env *env,
                      const char *name, const char *source_file);

/* How many ANI_CODE registry rows are translated, for coverage reporting.
   A routine written once per file counts once per file, since each is a
   different body. */
size_t wm_anim_code_count(void);

/* DCSSOUND.ASM's DUMMY_WAIT lockout, one tick. Call once per game tick. */
void wm_anim_code_tick(void);
/* Clear the ANI_CODE routines' own global state (ENDLESS_SOUND and that
   lockout) -- the source clears them between rounds. */
void wm_anim_code_reset(void);
/* DCSSOUND.ASM's ENDLESS_SOUND: the one looping sound the machine allows. */
uint16_t wm_anim_code_endless_sound(void);

/* Start `program`: runs its header commands and stops on the first frame.
   `env` is kept for the life of the animation, so it must outlive it; NULL
   means the ANI_CODE routines that need a service simply do nothing. */
void wm_anim_exec_start(wm_anim_exec *exec, const wm_anim_program *program,
                        wm_arcade_actor_t *actor, uint16_t round_tickcount,
                        const wm_anim_env *env);

/* Advance one tick. Runs commands and takes branches as the frame expires. */
void wm_anim_exec_tick(wm_anim_exec *exec, wm_arcade_actor_t *actor,
                       uint16_t round_tickcount);

/* The frame currently showing, or NULL once the program has ended. */
const char *wm_anim_exec_frame(const wm_anim_exec *exec);

#endif
