#ifndef WM_ANIM_PROGRAM_H
#define WM_ANIM_PROGRAM_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "wm/arcade/wm_arcade_combat.h"

/*
 * An animation as the program it is in ANIM.ASM, rather than as a flat list
 * of frames with side tables hung off frame indices.
 *
 * The flat model cannot express a branch: a routine that plays different
 * frames on a hit than on a miss has to be linearised into one list that no
 * playthrough ever plays. Every attack wired in this port carries at least
 * one such fork -- hrt_2_punch_anim's own ANI_SLIDE_BACK skips a frame when
 * the punch missed -- so the frames have been an approximation throughout.
 *
 * Ops are generated by tools/wlprogram.py with branch targets already
 * resolved to op indices, so the interpreter never needs the source text.
 */
typedef enum {
    WM_AOP_FRAME = 0,      /* text = source frame, a = ticks */
    WM_AOP_END,
    WM_AOP_REPEAT,

    /* branches; `target` is an op index in this same program */
    WM_AOP_GOTO,
    WM_AOP_IFSTATUS,       /* ANIM.ASM:29  MODE_STATUS set   -> branch */
    WM_AOP_IFNOTSTATUS,    /* ANIM.ASM:45  MODE_STATUS clear -> branch */
    WM_AOP_IFBLOCKED,      /* ANIM.ASM:83  hitblocker set    -> branch */
    WM_AOP_IF_RPTCOUNT,    /* ANIM.ASM:90  rpt_count nonzero -> branch */
    WM_AOP_SLIDE_BACK,     /* MODE_STATUS clear -> branch (no slide) */

    /* become another animation */
    WM_AOP_CHANGEANIM,     /* text = target animation's source label */
    WM_AOP_IFBUTTONS,      /* a = button mask, text = target label */

    /* repeat counter */
    WM_AOP_SET_RPTCOUNT,   /* a = count */
    WM_AOP_DEC_RPTCOUNT,

    /* attack boxes */
    WM_AOP_ATTACK_ON,      /* mode = AMODE, a..d = x,y,w,h */
    WM_AOP_ATTACK_ON_Z,    /* mode = AMODE, a..f = x,y,z,w,h,d */
    WM_AOP_ATTACK_OFF,

    /* instant state, all translated in src/core/anim_frame_commands.c */
    WM_AOP_SETMODE,        /* a = ANIMODE bits, absolute */
    WM_AOP_SETPLYRMODE,    /* a = player mode */
    WM_AOP_SETFACING,
    WM_AOP_XFLIP,
    WM_AOP_ZEROVELS,
    WM_AOP_ZERO_XZVELS,
    WM_AOP_SET_XVEL,       /* mode = AM_*, a = value */
    WM_AOP_SET_YVEL,
    WM_AOP_SET_ZVEL,
    WM_AOP_MIN_YVEL,
    WM_AOP_FRICTION,
    WM_AOP_OFFSET,         /* a,b,c = x,y,z */
    WM_AOP_SETSPEED,
    WM_AOP_STARTATTACK,    /* a = AT_ type, b = ticks */
    WM_AOP_FACEUP,
    WM_AOP_FACEDOWN,
    WM_AOP_SET_WRESTLER_XFLIP,
    WM_AOP_CLR_BUTCOUNT,
    WM_AOP_SAFE_TIME,
    WM_AOP_GRAVITY_ON,
    WM_AOP_CLR_STATUS,

    /* Present in the source but needing a system this port does not have
       (a renderer, paired actors, a callback bridge). Carried so the
       program stays a faithful record, executed as no-ops. */
    WM_AOP_UNTRANSLATED
} wm_anim_opcode;

typedef struct {
    uint8_t op;
    uint8_t mode;
    int16_t target;        /* branch destination op index, else -1 */
    int32_t a, b, c, d, e, f;
    const char *text;      /* frame name, or a target animation's label */
} wm_anim_op;

typedef struct {
    const char *source_label;
    const char *source_file;
    const wm_anim_op *ops;
    size_t op_count;
} wm_anim_program;

/* Execution state. One per actor track. */
typedef struct {
    const wm_anim_program *program;
    size_t pc;             /* op index of the frame currently showing */
    size_t next_pc;        /* where execution resumes when it expires */
    uint16_t ticks_left;
    uint16_t rpt_count;
    bool ended;
    bool just_started;
    const char *become;    /* set when the program asks to become another */
} wm_anim_exec;

const wm_anim_program *wm_anim_program_find(const char *source_label);

/* Start `program`: runs its header commands and stops on the first frame. */
void wm_anim_exec_start(wm_anim_exec *exec, const wm_anim_program *program,
                        wm_arcade_actor_t *actor, uint16_t round_tickcount);

/* Advance one tick. Runs commands and takes branches as the frame expires. */
void wm_anim_exec_tick(wm_anim_exec *exec, wm_arcade_actor_t *actor,
                       uint16_t round_tickcount);

/* The frame currently showing, or NULL once the program has ended. */
const char *wm_anim_exec_frame(const wm_anim_exec *exec);

#endif
