#ifndef WM_DCS_PORT_BINDINGS_H
#define WM_DCS_PORT_BINDINGS_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/*
 * Generated by Combat2ES R35 from assets/dcs/catalog/DCS_PORT_BINDINGS.json.
 * This table is a runtime binding surface for the decoded R2B DCS assets:
 * command id -> decoded stream address -> DragonFS WAV64 path.
 * It does not synthesize or substitute audio. Missing commands remain unbound.
 */

typedef struct {
    uint16_t command;
    uint16_t stream_index;
    uint32_t stream_address;
    int8_t source_channel;
    const char *dragonfs_path;
} wm_dcs_port_binding;

size_t wm_dcs_port_binding_count(void);
const wm_dcs_port_binding *wm_dcs_port_binding_at(size_t index);
const wm_dcs_port_binding *wm_dcs_find_first_binding_for_command(uint16_t command);
bool wm_dcs_command_has_decoded_binding(uint16_t command);

uint32_t wm_dcs_decoded_stream_count(void);
uint32_t wm_dcs_command_program_rows(void);
uint32_t wm_dcs_command_stream_rows(void);
uint32_t wm_dcs_decoded_command_stream_bindings(void);

#endif
