#ifndef WM_WRESTLER_SOUND_TABLES_H
#define WM_WRESTLER_SOUND_TABLES_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "wm/arcade/wmania_rng.h"

#ifdef __cplusplus
extern "C" {
#endif

/*
 * SOUND.H's WRSNDX, and the three layers of table under it.
 *
 * Every wrestler grunts, yells and gets hurt in his own voice, and the
 * routines that do it (ANI_CODE's `impact_sound` and `DO_GRUNT`) are two
 * lines each -- all the behaviour is in the data:
 *
 *   1. MASTER_SOUND_TABLE is a 9 x 59 word grid, [WRESTLERNUM][move].
 *      The source's own note on the layout: "each row contains the
 *      triple_sound_table indices of the four sound calls associated with
 *      a given move. the first two are the noises a wrestler makes when
 *      he throws the move, and the second two are the noises he makes
 *      when he's hit with the move."
 *
 *   2. A NEGATIVE entry means DEFLT (8000h) -- read DEFAULT_SOUND_TABLE
 *      instead. A zero means no sound, on either table. The macro tests
 *      them in that order (`jrz DONE?`, then `jrp OKAY?`).
 *
 *   3. What comes out goes to table_sound (DCSSOUND.ASM:1330), which is
 *      NOT just triple_sound: `btst 12,a0` -- an index with bit 12 set
 *      names one of 67 random sub-tables, and the sound is drawn from it
 *      with RNDRNG0. Almost every per-wrestler entry has that bit set, so
 *      a wrestler's grunt is redrawn on every hit rather than fixed.
 *
 * Everything below is generated by tools/wlwrsnd.py from DCSSOUND.ASM and
 * SOUND.H; none of it is written by hand.
 */

/* SOUND.H:124 `LAST_MOVE equ YELL_THROW`; WRSNDXI strides by LAST_MOVE+1. */
#define WM_WRSND_MOVES 59
/* Nine WRESTLERNUM rows. Slot 7 is Adam Bomb, the wrestler who was cut;
   W_REF (9) has no row at all, and the referee never grunts. */
#define WM_WRSND_WRESTLERS 9
/* DCSSOUND.ASM:1083 `DEFLT .equ 8000h` -- negative as a 16-bit word. */
#define WM_WRSND_DEFLT 0x8000u
/* table_sound's `btst 12,a0`. */
#define WM_WRSND_RANDOM_BIT 0x1000u

/* The two move indexes the translated ANI_CODE routines ask for, from
   SOUND.H. Named here because the routines name them. */
#define WM_WRSND_GRABFLING_T1 32
#define WM_WRSND_GRABFLING_T2 33
#define WM_WRSND_HDBUTT_L1 6
#define WM_WRSND_HDBUTT_L2 7
#define WM_WRSND_RUGSLAM_YELL 54
#define WM_WRSND_RUGSLAM_IMPACT 55

typedef struct {
    const char *name;
    const uint16_t *entries;
    uint16_t last_index;   /* RNDRNG0's inclusive maximum */
    size_t count;          /* entries actually written */
} wm_wrsnd_random;

extern const uint16_t wm_wrsnd_default[WM_WRSND_MOVES];
extern const uint16_t wm_wrsnd_master[WM_WRSND_WRESTLERS][WM_WRSND_MOVES];
extern const wm_wrsnd_random wm_wrsnd_random_tables[];
extern const size_t wm_wrsnd_random_count;

/*
 * The MASTER-then-DEFAULT lookup, without playing anything. Returns 0 for
 * "no sound", which is what a zero entry on either table means. An out of
 * range wrestler or move is 0 too; the source indexes without a check
 * because WRESTLERNUM is always in range.
 */
uint16_t wm_wrsnd_lookup(int wrestler_num, int move_index);

/*
 * DCSSOUND.ASM:1330 table_sound: resolve one index to the sound that is
 * actually played. Without an RNG a random index cannot be drawn, so this
 * returns 0 rather than inventing a draw -- the same rule the rest of the
 * port's sound bridge follows.
 */
uint16_t wm_wrsnd_table_sound(uint16_t call, WmRng *rng);

/*
 * SOUND.H:184 WRSNDX itself: look both moves up for this wrestler and
 * play what comes out, in order. `move2` may be negative for the
 * one-sound form. Returns how many sounds were played.
 */
int wm_wrsndx(int wrestler_num, int move1, int move2, WmRng *rng,
              void *user, void (*sound)(void *user, uint16_t call));

#ifdef __cplusplus
}
#endif
#endif
