#ifndef WM_WRESTLER_ANIM_TABLES_H
#define WM_WRESTLER_ANIM_TABLES_H

#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Each wrestler's own turn, walk and torso animation tables.
 *
 * wm/roster_anim_tables.h holds the GLOBAL tables -- one animation per
 * roster slot, "everyone does this, each in his own animation". These
 * are the other half: three tables belonging to one wrestler, indexed
 * by where he is facing and where he is going. Generated by
 * tools/wlwrestlertbl.py from the source's own per-wrestler dispatch
 * lists (WRESTLE.ASM:5031, :5043, :5100), so the roster order is read
 * rather than assumed -- slot 7 is Adam Bomb, cut from the game, and
 * carries Doink's tables rather than nothing.
 *
 * Strings are source labels, resolved through wm_anim_program_find.
 */
typedef struct {
    /* [rows][cols] of source animation labels, or NULL for an empty
       slot -- the Referee has no rotate table (WRESTLE.ASM:5109). */
    const char *const *labels;
    int rows;
    int cols;
} wm_wrestler_anim_table;

#define WM_WRESTLER_ANIM_SLOTS 10

/*
 * WRESTLE.ASM:5062 set_rotate_anim -- turning on the spot, from the
 * idle (#zip) path. [old facing diagonal][new facing diagonal], 4x4:
 * the diagonal of the matrix is that facing's standing pose, every
 * other entry the turn animation between two diagonals. Played through
 * change_anim1, the primary channel.
 */
extern const wm_wrestler_anim_table
    wm_wrestler_rotate_anims[WM_WRESTLER_ANIM_SLOTS];

/*
 * WRESTLE.ASM:4973 change_walk_anim's torso half. Same 4x4 turn matrix
 * as rotate, in the `2` animation variants (hrt_2_to_4_turn2_anim
 * beside hrt_2_to_4_turn_anim), played through change_anim2 -- the
 * SECOND animation channel -- and skipped entirely when ANIMODE2
 * already has MODE_UNINT set.
 */
extern const wm_wrestler_anim_table
    wm_wrestler_torso_anims[WM_WRESTLER_ANIM_SLOTS];

/*
 * WRESTLE.ASM:5000 change_walk_anim's leg half.
 * [move direction][facing direction], 8x8 over the full compass rather
 * than the diagonals, played through change_anim1.
 */
extern const wm_wrestler_anim_table
    wm_wrestler_leg_anims[WM_WRESTLER_ANIM_SLOTS];

/*
 * The label at [row][col] of a slot's table, or NULL when the slot is
 * empty or the index is out of range. Indices are the CONVERTED compass
 * values the source computes (convert_facing, then `srl 1` for the 4x4
 * tables), not raw FACING_DIR bits.
 */
const char *wm_wrestler_anim_label(const wm_wrestler_anim_table *table,
                                   int row, int col);

#ifdef __cplusplus
}
#endif
#endif
