#ifndef WM_WRESTLER_ANIM_TABLES_H
#define WM_WRESTLER_ANIM_TABLES_H

#include <stdbool.h>
#include <stddef.h>

#include "wm/arcade/wm_arcade_combat.h"
#include "wm/arcade/wmania_rng.h"

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Each wrestler's own turn, walk and torso animation tables.
 *
 * wm/roster_anim_tables.h holds the GLOBAL tables -- one animation per
 * roster slot, "everyone does this, each in his own animation". These
 * are the other half: three tables belonging to one wrestler, indexed
 * by where he is facing and where he is going. Generated by
 * tools/wlwrestlertbl.py from the source's own per-wrestler dispatch
 * lists (WRESTLE.ASM:5031, :5043, :5100), so the roster order is read
 * rather than assumed -- slot 7 is Adam Bomb, cut from the game, and
 * carries Doink's tables rather than nothing.
 *
 * Strings are source labels, resolved through wm_anim_program_find.
 */
typedef struct {
    /* [rows][cols] of source animation labels, or NULL for an empty
       slot -- the Referee has no rotate table (WRESTLE.ASM:5109). */
    const char *const *labels;
    int rows;
    int cols;
} wm_wrestler_anim_table;

#define WM_WRESTLER_ANIM_SLOTS 10

/*
 * WRESTLE.ASM:5062 set_rotate_anim -- turning on the spot, from the
 * idle (#zip) path. [old facing diagonal][new facing diagonal], 4x4:
 * the diagonal of the matrix is that facing's standing pose, every
 * other entry the turn animation between two diagonals. Played through
 * change_anim1, the primary channel.
 */
extern const wm_wrestler_anim_table
    wm_wrestler_rotate_anims[WM_WRESTLER_ANIM_SLOTS];

/*
 * WRESTLE.ASM:4973 change_walk_anim's torso half. Same 4x4 turn matrix
 * as rotate, in the `2` animation variants (hrt_2_to_4_turn2_anim
 * beside hrt_2_to_4_turn_anim), played through change_anim2 -- the
 * SECOND animation channel -- and skipped entirely when ANIMODE2
 * already has MODE_UNINT set.
 */
extern const wm_wrestler_anim_table
    wm_wrestler_torso_anims[WM_WRESTLER_ANIM_SLOTS];

/*
 * WRESTLE.ASM:5000 change_walk_anim's leg half.
 * [move direction][facing direction], 8x8 over the full compass rather
 * than the diagonals, played through change_anim1.
 */
extern const wm_wrestler_anim_table
    wm_wrestler_leg_anims[WM_WRESTLER_ANIM_SLOTS];

/*
 * WRESTLE2.ASM:4079 #special_moves -- each wrestler's secret-move
 * processes. init_smoves walks the list at match start and spawns one
 * SMOVE_PID process per entry; each watches for its own joystick and
 * button pattern and fires the move. The list is 0-terminated in the
 * source and that terminator is not stored here; `count` is.
 *
 * These entries are ROUTINES, not animations, so unlike the three
 * tables above they are not resolvable through wm_anim_program_find.
 * What they are good for is knowing the real set, in the real order,
 * for each wrestler -- and knowing which entries the arcade actually
 * assembled.
 *
 * That last part is the reason this is generated. Every one of these
 * tables wraps its finishing-move entries in `.if NUM_<name>_FINISHES`,
 * and GAME.EQU:580-587 sets seven of the eight switches to 0 --
 * Undertaker's is the only 1. So exactly one finishing move exists in
 * the shipped game, und_finish_move1, and the other fifteen
 * *_finish_move1/2 routines are source text the assembler skipped.
 * Six of the port's hand-written lists carried eleven of them.
 */
typedef struct {
    const char *const *labels;   /* NULL for an empty slot */
    int count;
} wm_wrestler_smove_table;

extern const wm_wrestler_smove_table
    wm_wrestler_smoves[WM_WRESTLER_ANIM_SLOTS];

/*
 * DOINK.ASM:1632 #taunt_t -- the animation each wrestler plays for the
 * start-of-round taunt, indexed by WRESTLERNUM. Defined in DOINK.ASM
 * because do_taunt is, and every wrestler's control code CREATEs that
 * one shared routine.
 *
 * NULL for slot 7 (Adam Bomb, cut) and slot 9 (the Referee), both a
 * plain 0 in the source.
 */
extern const char *const wm_wrestler_taunt_anims[WM_WRESTLER_ANIM_SLOTS];

/*
 * DOINK.ASM:1594 do_taunt, spawned as a TAUNT_PID process at the start
 * of each round by all eight wrestlers' control code.
 *
 * A human taunts only if he is holding UP and BLOCK when the round
 * starts; a drone taunts on an RNDPER(250) draw -- a 25% chance. Either
 * way the answer is his row of #taunt_t, played through change_anim1a
 * (the UNGUARDED entry point, so it restarts even if the same animation
 * is already running).
 *
 * Returns the animation label to start, or NULL when he does not taunt.
 * `rng` may be NULL, in which case a drone never taunts rather than
 * taunting on a fabricated draw.
 */
const char *wm_wrestler_do_taunt(const wm_arcade_actor_t *actor,
                                 bool is_drone, WmRng *rng);

/*
 * The label at [row][col] of a slot's table, or NULL when the slot is
 * empty or the index is out of range. Indices are the CONVERTED compass
 * values the source computes (convert_facing, then `srl 1` for the 4x4
 * tables), not raw FACING_DIR bits.
 */
const char *wm_wrestler_anim_label(const wm_wrestler_anim_table *table,
                                   int row, int col);

#ifdef __cplusplus
}
#endif
#endif
